### ISSUE TITLE
ADD ANDROID SUPPORT FOR EMULATOR

### ISSUE THREAD

**Issue by FabriBertani** [AndreiMisiukevich/HotReload#1]
Hi @AndreiMisiukevich i found your plugin awsome, it works great on iOS but can't make it work on Android (i've installed the System.Threading.Tasks.Extensions v4.4.0), the observer register an update on my xaml but the emulator don't update the screen.

**Comment by AndreiMisiukevich** [comment]
@FabriBertani hi, thanks for feedback :)
I noticed this issue too. I will try to figure out, why it doesn't work

**Comment by AndreiMisiukevich** [comment]
Hope @1iveowl will help us https://github.com/1iveowl/SimpleHttpListener.Rx/issues/9

**Comment by AndreiMisiukevich** [comment]
Hi @FabriBertani 
Did you try on emulator, right?

**Comment by AndreiMisiukevich** [comment]
@FabriBertani could you please try on real device?
Make sure, that **observer** and **reloader** have the same url (it should be url with your device local ip _[http://{ip}:800 something like this]_, also PC/Mac and device must be in one local network)

**Comment by 1iveowl** [comment]
[SimpleHttpListener.Rx v6.1.0](https://www.nuget.org/packages/SimpleHttpListener.Rx/6.1.0) now depends on System.Reactive 4.0.0. This should work-round the issue until later versions of System.Reactive have been fixed to work on Android.

**Comment by 1iveowl** [comment]
Unfortunately, I don't know how to force the emulator to accept http requests.

**Comment by AndreiMisiukevich** [comment]
Hm, i think we can modify the flow for android emulator
Host httpListener on PC/Mac instead of doing it on device/emulator.
Call host every 1 sec for retrieving updates.

**Comment by AbdelrahmanGIT** [comment]
@AndreiMisiukevich Glad i was able to help, i will update the Readme file maybe tonight or tomorrow.

**Comment by AndreiMisiukevich** [comment]
Added workaround section to Readme file!

**Comment by AndreiMisiukevich** [comment]
@AbdelrahmanGIT hi
i changed implementation :)

Could you please assist with workaround now?
I use HttpListener isntead

**Comment by AbdelrahmanGIT** [comment]
> @AbdelrahmanGIT hi
> i changed implementation :)
> 
> Could you please assist with workaround now?
> I use HttpListener isnstead

@AndreiMisiukevich  i think the workaround should still work assuming it's still listening to `localhost` in the emulator to, i will look into it today and see if the workaround need changes :)

**Comment by AndreiMisiukevich** [comment]
@AbdelrahmanGIT yep) that's correct
Don't know why, but it doesn't work on genymotion emulator :( but fine on defaults

**Comment by AbdelrahmanGIT** [comment]
@AndreiMisiukevich That's weird it should work as it's an `adb` feature, i will download genymotion and see if/how we can fix this

**Comment by Carl-Wen** [comment]
> @AndreiMisiukevich That's weird it should work as it's an `adb` feature, i will download genymotion and see if/how we can fix this

Hello, did it work well with genymotion emulator for now?  I test it on genymotion emulator, it seems like not work.

**Comment by AndreiMisiukevich** [comment]
> > @AndreiMisiukevich That's weird it should work as it's an `adb` feature, i will download genymotion and see if/how we can fix this
> 
> Hello, did it work well with genymotion emulator for now? I test it on genymotion emulator, it seems like not work.

create separate ticket please. Maybe we will try to find solution.

need to add http://10.0.3.2/ support. It will be easy

**Comment by AndreiMisiukevich** [comment]
> > @AndreiMisiukevich That's weird it should work as it's an `adb` feature, i will download genymotion and see if/how we can fix this
> 
> Hello, did it work well with genymotion emulator for now? I test it on genymotion emulator, it seems like not work.

i will create myself

**Comment by DiegoVenancioVieira** [comment]
Hi, some update about genymotion? 

I'm trying now and not working. Thanks in advance

**Comment by AndreiMisiukevich** [comment]
> Hi, some update about genymotion?
> 
> I'm trying now and not working. Thanks in advance

hm, should be working

Check "adb" is added to PATH

**Comment by DiegoVenancioVieira** [comment]
> > Hi, some update about genymotion?
> > I'm trying now and not working. Thanks in advance
> 
> hm, should be working
> 
> Check "adb" is added to PATH

@AndreiMisiukevich Hi, dear. I post a question here: https://stackoverflow.com/q/58720801/4654957. Let me know if is better open other topic/issue here and if can I help u with tests. Maybe I'm missing something, but dont know whats.

**Comment by AndreiMisiukevich** [comment]
> VS -> TOOLS -> ANDROID -> PROMPT ANDROID adb forward tcp:15000 tcp:15000

you needn't have to do it. And DO NOT set DeviceUrlPort = 15000

Just ```HotReloader.Current.Run(this)```
