### ISSUE TITLE
Doesn't work on windows (XF UWP)

### ISSUE THREAD

**Issue by euandrebarbosa** [AndreiMisiukevich/HotReload#100]
Hi there,

I try to use on Visual Studio 2017, in a desktop application (just created for tests) and, even following the "start tutorial", it doesn't work!
The lightning icons appear, i click on it, the message "Extension has started to listen 17502 port for IP auto discovery" appears, but the changes have no effects.

![image](https://user-images.githubusercontent.com/24798901/61716205-02998c00-ad35-11e9-8942-578756de26bc.png)

Can you help me?

**Comment by AndreiMisiukevich** [comment]
https://github.com/AndreiMisiukevich/HotReload/issues/87#issuecomment-508484626

**Comment by Saccomani** [comment]
@AndreiMisiukevich , now are  working only on first XAML change, after lost the connection... we work togheter @euandrebarbosa  and me

**Comment by AndreiMisiukevich** [comment]
@Saccomani are you sure it's really lost?
Can you try to create new XF project with one page and try to play with it.

BTW, do you experience the same issue with Android and iOS ?

**Comment by Saccomani** [comment]
> @Saccomani are you sure it's really lost?
> Can you try to create new XF project with one page and try to play with it.
> 
> BTW, do you experience the same issue with Android and iOS ?

web can try iOS or Android, we work only with mac and windows... at my home works fine on mac!

**Comment by AndreiMisiukevich** [comment]
@Saccomani very strange.. hmmm. try to disable firewall please

**Comment by euandrebarbosa** [comment]
@AndreiMisiukevich we disabled the firewall as you said, but only the first change is applied.
We are debugging from one PC into other, we can provide any tip to us?

**Comment by AndreiMisiukevich** [comment]
@MagicAndre1981 can help, i think.

Unfortunately I'm mac user

**Comment by AndreiMisiukevich** [comment]
that's very strange .. it works only one time

**Comment by euandrebarbosa** [comment]
Thanks anyway, we gonna Fork your repository and try understand better.

**Comment by MagicAndre1981** [comment]
> We are debugging from one PC into other, we can provide any tip to us?

this would work. I also remote debug the app from Win10 VM on a Windows 10 tablet and use Hotreload. Only connecting to local device/simulator is failing for UWP.

**Comment by Saccomani** [comment]
i found an error: 

i just put the Xamarin.Forms.HotReload.Observer.exe in my Xamarin project root folder, and start the executable...

when i save the XAML i catch an error in Send File Method : 

[EXCEPTION IN SEND FILE] :System.IO.IOException: O processo não pode acessar o arquivo 'C:\hotreload\HotReload\Sample\Xamarin.Forms.HotReload.Sample\Pages\ItemPage.xaml' porque ele está sendo usado por outro processo.
   em System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   em System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   em System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   em System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   em System.IO.StreamReader..ctor(String path)
   em System.IO.File.OpenText(String path)
   em Xamarin.Forms.HotReload.Observer.FileObserver.<SendFile>d__9.MoveNext()

**Comment by MagicAndre1981** [comment]
`Xamarin.Forms.HotReload.Observer.exe` is not required with VS extension.

**Comment by AndreiMisiukevich** [comment]
Yeah. I will delete reloader

use extensions
