### ISSUE TITLE
[Solved] Not working after last update

### ISSUE THREAD

**Issue by JCKodel** [AndreiMisiukevich/HotReload#101]
Since the last update, nothing works anymore. Each time I try to change the xaml, the following error appears on logcat and the screen is blank.

```
I/mono-stdout(23760): System.ArgumentNullException: Value cannot be null.
I/mono-stdout(23760): Parameter name: value
I/mono-stdout(23760):   at Xamarin.Forms.HotReloader.ReloadElement (System.Object obj, Xamarin.Forms.HotReloader+ReloadItem reloadItem) [0x00377] in <613f3eb72762438d879b16aa8880d13f>:0
I/mono-stdout(23760):   at Xamarin.Forms.HotReloader+<>c__DisplayClass27_0.<ReloadElements>b__0 () [0x00027] in <613f3eb72762438d879b16aa8880d13f>:0
I/mono-stdout(23760): ### HOTRELOAD ERROR: CANNOT PARSE XAML ###
```

**Comment by AndreiMisiukevich** [comment]
@JCKodel would be easy to fix

Tell me please your Xamarin.Forms version.
if you provide me small sample i will fix it tonight

**Comment by AndreiMisiukevich** [comment]
@JCKodel can you provide sample please?

**Comment by JCKodel** [comment]
Xamarin Forms 4.1.0.581479

I cannot pinpoint exactly where it fails. I've downloaded the source code and I'll try to debug it and find the error, so I can help you with a solid case.

**Comment by AndreiMisiukevich** [comment]
@JCKodel would be amazing

**Comment by JCKodel** [comment]
![image](https://user-images.githubusercontent.com/379339/61718932-493db500-ad3a-11e9-8f81-a5c75f19a995.png)

When HotReloader runs this code, it triggers one of my components that renders Svg (it inherits Xamarin.Forms.Image).

My component have a bindable property called ResourceProperty (which is a string with the name of the svg).

Somehow, after the line 234 of HotReloader.cs, it triggers this code in my SvgImage component:
![image](https://user-images.githubusercontent.com/379339/61719103-a9ccf200-ad3a-11e9-8399-3ef59c6adefb.png)

Resource is a bindable property:
```
		public string Resource
		{
			get { return (string)GetValue(ResourceProperty); }
			set { SetValue(ResourceProperty, value); }
		}

		public static BindableProperty ResourceProperty =
			BindableProperty.Create(
				nameof(Resource),
				typeof(string),
				typeof(SvgImage),
				default(string),
				defaultBindingMode: BindingMode.OneWay,
				propertyChanged: ResourcePropertyChanged
			);
```

Somehow, HotReloader is causing my component to forget its state.
After I fix my offending code (checking if Resource is null and doing nothing in this case), HotReloader works fine. =)

Suggestion: 
As we're usually using HotReloader in debug enviroment, would be nice if a popup appears telling us the stack trace when something bad occurs (with this info, we can pinpoint the exactly code that is buggy (and it's our code), so we can fix it (or adapt it to use it with hotreloader). 

In debug environment, the stack trace is usefull and will show us our mistakes =)

**Comment by AndreiMisiukevich** [comment]
> ![image](https://user-images.githubusercontent.com/379339/61718932-493db500-ad3a-11e9-8f81-a5c75f19a995.png)
> 
> When HotReloader runs this code, it triggers one of my components that renders Svg (it inherits Xamarin.Forms.Image).
> 
> My component have a bindable property called ResourceProperty (which is a string with the name of the svg).
> 
> Somehow, after the line 234 of HotReloader.cs, it triggers this code in my SvgImage component (but the Resource property is null):
> ![image](https://user-images.githubusercontent.com/379339/61719103-a9ccf200-ad3a-11e9-8399-3ef59c6adefb.png)
> 
> Resource is a bindable property:
> 
> ```
> 		public string Resource
> 		{
> 			get { return (string)GetValue(ResourceProperty); }
> 			set { SetValue(ResourceProperty, value); }
> 		}
> 
> 		public static BindableProperty ResourceProperty =
> 			BindableProperty.Create(
> 				nameof(Resource),
> 				typeof(string),
> 				typeof(SvgImage),
> 				default(string),
> 				defaultBindingMode: BindingMode.OneWay,
> 				propertyChanged: ResourcePropertyChanged
> 			);
> ```
> 
> Somehow, HotReloader is causing my component to forget its state.
> After I fix my offending code (checking if Resource is null and doing nothing in this case), HotReloader works fine. =)
> 
> Suggestion:
> As we're usually using HotReloader in debug enviroment, would be nice if a popup appears telling us the stack trace when something bad occurs (with this info, we can pinpoint the exactly code that is buggy (and it's our code), so we can fix it (or adapt it to use it with hotreloader).
> 
> In debug environment, the stack trace is usefull and will show us our mistakes =)

hmmm, we can add one more property to config. So developer can decide if they want to see popups or not

**Comment by JCKodel** [comment]
@AndreiMisiukevich 

Line 444 (catch(Exception ex)) and line 498 (catch(Exception ex)), I've added:
```
ShowErrorAndStackTrace(ex);
```

Then, I've created this function:

```
private void ShowErrorAndStackTrace(Exception ex)
{
	Application.Current.MainPage.DisplayAlert(ex.Message, ex.StackTrace, "OK");
}
```

Now, I've made an intentional error (tried to write Padding in a Label component), it will show me the error (and the StackTrace will be usefull, if it contains code that I've wrote):

![image](https://user-images.githubusercontent.com/379339/61720938-0e3d8080-ad3e-11e9-9eeb-99ce25c0a8ce.png)

(you can also use https://github.com/aritchie/userdialogs, which is safer than Application.Current.MainPage)

As I use https://github.com/rotorgames/Rg.Plugins.Popup, I'll make myself a neat popup that is more readable than an alert. =)
