### ISSUE TITLE
[WORKAROUND] HotReload does not work on the latest VS for Mac update 8.2

### ISSUE THREAD

**Issue by iamlawrencev** [AndreiMisiukevich/HotReload#102]
I installed the Visual Studio 8.2 for Mac update and suddenly HotReload does not work both on iOS and Android. The application output does not report any errors regarding HotReload.

XF Version: 4.1.0.555618

**Comment by AndreiMisiukevich** [comment]
Have you tried to restart VS after installation?
also have you enabled extension ?

**Comment by ChasakisD** [comment]
I am having the exact same issue with VS for Mac 8.2. The issue is probably with the new XAML Editor. If you open a xaml file by Open With -> Source Code Editor, the file opens with the old editor, and then the extensions is working great.

**Comment by iamlawrencev** [comment]
@AndreiMisiukevich yes I have restarted and enabled extension. As @ChasakisD said this is most likely due to the new XAML editor. Thanks for the workaround @ChasakisD!

**Comment by AndreiMisiukevich** [comment]
Hmmm, thanks guys. Need to check what a hell is going on

**Comment by Saccomani** [comment]
> I am having the exact same issue with VS for Mac 8.2. The issue is probably with the new XAML Editor. If you open a xaml file by Open With -> Source Code Editor, the file opens with the old editor, and then the extension is working great.

this workaround works fine to me !

**Comment by AndreiMisiukevich** [comment]
download 1.4.0 extension version
