### ISSUE TITLE
HotReloader doesn't support MvxApplication in MVVMCross

### ISSUE THREAD

**Issue by Nikitajain1121** [AndreiMisiukevich/HotReload#103]
As |'m using the MVVM cross Forms. I'm unable to run this line of code  
> HotReloader.Current.Run(this);
As it extends the `MvxApplication`.So is there any other solution to implement the HotReloader in MVVM cross.

Using: xamarin forms: 4.1.0
Mvvm cross: 5.2.1

**Comment by AndreiMisiukevich** [comment]
@Nikitajain1121 yes, because you should call it with your XAMARIN.FORMS Application

Look:
https://github.com/martijn00/MvxForms/tree/master/MvxForms.Core

![image](https://user-images.githubusercontent.com/10124814/61944687-f452a680-afa6-11e9-9945-829e8e8adb09.png)

**Comment by AndreiMisiukevich** [comment]
![image](https://user-images.githubusercontent.com/10124814/61944752-164c2900-afa7-11e9-8e1e-489e226716d0.png)

**Comment by Nikitajain1121** [comment]
Okay sure, thank you!! It's working now

**Comment by AndreiMisiukevich** [comment]
@Nikitajain1121 great)
