### ISSUE TITLE
VS 2019 No refresh

### ISSUE THREAD

**Issue by CarrotSolutions** [AndreiMisiukevich/HotReload#105]
VS 2019 Still not refreshing

Downloaded extension.  Installed nuget.  Restarted everything multiple time.  Even tried with HotReload sample project.  Also tried with new project templater.  All fails.

Added to App.xaml.cs
 HotReloader.Current.Run(this);

Added to Android Project
var app = new App();
#if DEBUG
            HotReloader.Current.Run(app);
#endif

Added where needed
#if !DEBUG
 [XamlCompilation(XamlCompilationOptions.Compile)]
#endif

Added env var for adb at C:\Program Files (x86)\Android\android-sdk\platform-tools.  Confirmed correct location.  

Any ideas?

**Comment by AndreiMisiukevich** [comment]
Mac / Win ?

**Comment by CarrotSolutions** [comment]
Windows.  Any help would be much appreciated.  Been at this the last 4 hours.

**Comment by AndreiMisiukevich** [comment]
@CarrotSolutions do you try on VS Android emulator or genymotion?

**Comment by AndreiMisiukevich** [comment]
try to forward ports yourself

adb forward tcp:8000 tcp:8000

**Comment by CarrotSolutions** [comment]
Note when I click the green lightning bolt - it is now listening on port 15001 vs 15000

**Comment by CarrotSolutions** [comment]
VS Android emulator.  How do i forward ports?

**Comment by CarrotSolutions** [comment]
Where do i insert = 
adb forward tcp:8000 tcp:8000

**Comment by CarrotSolutions** [comment]
C:\Program Files (x86)\Android\android-sdk\platform-tools>adb forward tcp:8000 tcp:8000

**Comment by CarrotSolutions** [comment]
'/storage/emulated/0/Android/data/com.companyname.LittlePeachXamApp/files/.__override__/Xamarin.Forms.HotReload.Reloader.dll.so' not found: dlopen failed: library "/storage/emulated/0/Android/data/com.companyname.LittlePeachXamApp/files/.__override__/Xamarin.Forms.HotReload.Reloader.dll.so" not found
07-28 15:05:55.449 D/Mono    ( 5180): AOT: image '/Users/builder/jenkins/workspace/xamarin-android-d16-1/xamarin-android/external/mono/sdks/out/android-x86-release/lib/mono/aot-cache/x86/Xamarin.Forms.HotReload.Reloader.dll.so' not found: dlopen failed: library "/Users/builder/jenkins/workspace/xamarin-android-d16-1/xamarin-android/external/mono/sdks/out/android-x86-release/lib/mono/aot-cache/x86/Xamarin.Forms.HotReload.Reloader.dll.so" not found
07-28 15:05:55.450 D/Mono    ( 5180): Assembly Loader loaded assembly from location:

**Comment by CarrotSolutions** [comment]
07-28 15:06:05.068 I/mono-stdout( 5180): ### HOTRELOAD STARTED ON DEVICE's PORT: 8001 ###

C:\Program Files (x86)\Android\android-sdk\platform-tools>adb forward tcp:8001 tcp:8001
8001

WORKS! WORKS! WORKS! WORKS! WORKS! WORKS!

**Comment by AndreiMisiukevich** [comment]
@CarrotSolutions don't understand why ports are not autoforwarded.

**Comment by Saccomani** [comment]
In VS mac last 8.2 are not working after last update...

**Comment by AndreiMisiukevich** [comment]
@Saccomani https://github.com/AndreiMisiukevich/HotReload/issues/101

**Comment by AndreiMisiukevich** [comment]
@Saccomani https://github.com/AndreiMisiukevich/HotReload/issues/102

**Comment by CarrotSolutions** [comment]
Andrei - Thanks for the fast response and the help!
