### ISSUE TITLE
Can't run on VS Windows version

### ISSUE THREAD

**Issue by xamarindevelopervietnam** [AndreiMisiukevich/HotReload#107]
Hi @AndreiMisiukevich, I'm running VS 16.2.0, XF latest 4.1, Hot Reload nuget and extension are latest version as well.
The Hot Reload can't work on Android Simulator (tested on version 6.0 and 9.0).
Here is some information for you:
![Hot Reload Err1](https://user-images.githubusercontent.com/16578966/62099114-47826d00-b2b7-11e9-81a5-605327cd2991.PNG)
![Hot Reload Err2](https://user-images.githubusercontent.com/16578966/62099115-47826d00-b2b7-11e9-8153-57dc2fe0556b.PNG)
![Hot Reload Err3](https://user-images.githubusercontent.com/16578966/62099116-481b0380-b2b7-11e9-8a14-953bba27a613.PNG)
![Hot Reload Err4](https://user-images.githubusercontent.com/16578966/62099117-481b0380-b2b7-11e9-9922-0f83820e189a.PNG)

**Comment by IoTFier** [comment]
@xamarindevelopervietnam  what kind of error / issue are you facing ?
In my case, the app is stuck on Splash screen. Is that what you are facing too ?

@AndreiMisiukevich - I upgraded NuGet to 1.4.18 - not knowing features supporting c# but requiring some config. In both cases iOS and Android , I experienced Application instability - especially Android one - My App was totally frozen. In iOS it was crashing first time, but on 2nd or 3rd execution, it was coming up and running .. strange behavior.

**Comment by xamarindevelopervietnam** [comment]
> @xamarindevelopervietnam what kind of error / issue are you facing ?
> In my case, the app is stuck on Splash screen. Is that what you are facing too ?
> 
> @AndreiMisiukevich - I upgraded NuGet to 1.4.18 - not knowing features supporting c# but requiring some config. In both cases iOS and Android , I experienced Application instability - especially Android one - My App was totally frozen. In iOS it was crashing first time, but on 2nd or 3rd execution, it was coming up and running .. strange behavior.
> 
> Rolling back to 1.4.15 (7/22nd update) .. things got under control.

My problem is Hot Reload don't update UI

**Comment by AndreiMisiukevich** [comment]
> Hi @AndreiMisiukevich, I'm running VS 16.2.0, XF latest 4.1, Hot Reload nuget and extension are latest version as well.
> The Hot Reload can't work on Android Simulator (tested on version 6.0 and 9.0).
> Here is some information for you:
> ![Hot Reload Err1](https://user-images.githubusercontent.com/16578966/62099114-47826d00-b2b7-11e9-81a5-605327cd2991.PNG)
> ![Hot Reload Err2](https://user-images.githubusercontent.com/16578966/62099115-47826d00-b2b7-11e9-8153-57dc2fe0556b.PNG)
> ![Hot Reload Err3](https://user-images.githubusercontent.com/16578966/62099116-481b0380-b2b7-11e9-8a14-953bba27a613.PNG)
> ![Hot Reload Err4](https://user-images.githubusercontent.com/16578966/62099117-481b0380-b2b7-11e9-9922-0f83820e189a.PNG)

forward tcp:8000 tcp:8000 i gues

**Comment by xamarindevelopervietnam** [comment]
same problem with forward tcp:8000 tcp:8000
adb server die and very hard to restart

**Comment by AndreiMisiukevich** [comment]
> same problem with forward tcp:8000 tcp:8000
> adb server die and very hard to restart

frankly speaking autoforwarding should be automatic and you no need to do anything
try to restart VS (or even your PC)

**Comment by AndreiMisiukevich** [comment]
also you may use old extensions https://github.com/AndreiMisiukevich/HotReload#old-extensions-with-mannual-ip-entering

**Comment by AndreiMisiukevich** [comment]
https://github.com/AndreiMisiukevich/HotReload#additional-setup--troubleshooting

**Comment by xamarindevelopervietnam** [comment]
> > same problem with forward tcp:8000 tcp:8000
> > adb server die and very hard to restart
> 
> frankly speaking autoforwarding should be automatic and you no need to do anything
> try to restart VS (or even your PC)

After run: forward tcp:8000 tcp:8000, VS can't connect to simulator and I have to restart my PC

**Comment by AndreiMisiukevich** [comment]
```var values = HotReloader.Current.Run(this);
var port = values.SelectedDevicePort; // port which is selected by Reloader```
