### ISSUE TITLE
Problem with multiple devices

### ISSUE THREAD

**Issue by aocipriano** [AndreiMisiukevich/HotReload#108]
Hi @AndreiMisiukevich 

When I run my app in two devices, iOS Simulator and Android fisical device for example, it stops working.
I run the app in android device and it´s working, so I run the app in iOS simulator and android device stop updating changes.

I´m using VS Enterprise 2019 (16.2.0) and Xamarin Forms 4.1 and Hot reload plugin and extensions at latest versions.

**Comment by AndreiMisiukevich** [comment]
weird, but it works on Mac for me (iOS simulator + android Emulator)
