### ISSUE TITLE
Hot Reload not run in IOS Device

### ISSUE THREAD

**Issue by YovanyTabares** [AndreiMisiukevich/HotReload#109]
When Start debug of app in My Device With IOS the Hot Reload stop and not run the app.

IOS: 12.2

![Error_Hot_Reload](https://user-images.githubusercontent.com/51265971/62740324-262f2880-b9fd-11e9-95d6-1cebe625fd03.PNG)

**Comment by MagicAndre1981** [comment]
run [VS with /log switch](https://docs.microsoft.com/en-US/visualstudio/ide/reference/log-devenv-exe?view=vs-2019) and share the `activitylog.xml`

**Comment by YovanyTabares** [comment]
I Attach the log

[ActivityLog.zip](https://github.com/AndreiMisiukevich/HotReload/files/3486277/ActivityLog.zip)

**Comment by AndreiMisiukevich** [comment]
duplicated https://github.com/AndreiMisiukevich/HotReload/issues/79
