### ISSUE TITLE
ADDED POSSIBILITY TO INIT VIEW AFTER RELOADING

### ISSUE THREAD

**Issue by AndreiMisiukevich** [AndreiMisiukevich/HotReload#11]
Use ```IReloadable``` interface for achieving it
```csharp
    public partial class MainPage : ContentPage, IReloadable
    {
        public void OnLoaded()
        {
            Btn.Clicked += Handle_Clicked;
        }

        void Handle_Clicked(object sender, System.EventArgs e)
        {
            Btn.Text = (int.Parse(Btn.Text) + 1).ToString();
        }

    }
```

**Comment by MagicAndre1981** [comment]
I override OnAppearing and do here some tasks. How to handle the reload in such case? currently my page gets blank.

**Comment by AndreiMisiukevich** [comment]
@MagicAndre1981 good question.
Wait please new release. I am keen to create new version on this week

**Comment by MagicAndre1981** [comment]
ok.

I tried to call

```
Appearing += OnAppearing;
Disappearing += OnDisappearing;
```

in public void OnLoaded() but the breakpoint is not hit.

**Comment by MagicAndre1981** [comment]
ok, the OnLoaded() is called when I first start the app, but not when the XAML was changed.

It would be nice to have an async version:

public async Task  OnLoadedAsync() to do the async calls here. And after changing the XAML, make sure the OnLoadedAsync() gets called again so that I can do my async stuff again all time.

**Comment by AndreiMisiukevich** [comment]
@MagicAndre1981 i will check it.

Probably, i will refuse OnLoaded (obsolete it in next release)
And add OnReloaded 

As for async.. feel free to use **asyn void** or Task.Run

**Comment by MagicAndre1981** [comment]
In past this caused deadlocks for me, so I try to avoid it now.

**Comment by MagicAndre1981** [comment]
ok, it works now and I have no idea why it fails. Also OnLoaded() is called on XAML change in UWP. I use `public async void OnLoaded()` and it works so far. I hope it doesn't produce hangs in future.
