### ISSUE TITLE
HotReload Run method is not working

### ISSUE THREAD

**Issue by aijinrua** [AndreiMisiukevich/HotReload#110]
I use Xamarin.FFImageLoading.Forms Nuget.
By the way, using FFImage for Xaml File freezes at **`HotReloader.Current.Run (this);`**
There are no errors and the app doesn't quit.
It just stops as if waiting for something.

So I lowered the HotReload version to 1.4.15 and it started working.

![image](https://user-images.githubusercontent.com/10337369/62824404-1ddf1500-bbd8-11e9-9679-f298c8aa4605.png)

**Comment by AndreiMisiukevich** [comment]
Thanks

**Comment by AndreiMisiukevich** [comment]
can you please create small sample with issue?

**Comment by aijinrua** [comment]
[HotReloadTest.zip](https://github.com/AndreiMisiukevich/HotReload/files/3497266/HotReloadTest.zip)

use ffimageloading in MainPage.xaml.
and stop to InitializeComponent(); in MainPage.xaml.cs

**Comment by AndreiMisiukevich** [comment]
thanks i will take a look

**Comment by aijinrua** [comment]
I love you!!
Cheer up for you !!

**Comment by AndreiMisiukevich** [comment]
@aijinrua can you try 1.4.15 version instead? Does it work?
