### ISSUE TITLE
Stopped after upgrading Xamarin.Forms 4.1.0.673156

### ISSUE THREAD

**Issue by pbalbino** [AndreiMisiukevich/HotReload#111]
I was working normally, after upgrading to Xamarin.Forms version 4.1.0.673156 I get the following error while compiling.

Can not resolve reference: "System.Threading.Tasks.Extensions", referenced by "Microsoft.CodeAnalysis". Please add a NuGet package or assembly reference for "System.Threading.Tasks.Extensions", or remove the reference to "Microsoft.CodeAnalysis"

If I remove the Xamarin.HotReload package the compilation no longer generates an error.

Visual Studio 2017 - 15.9.14
![Hot](https://user-images.githubusercontent.com/25305220/62893529-3a3a9900-bd21-11e9-953e-d40a345b0987.PNG)

**Comment by MagicAndre1981** [comment]
why don't you simply add the required reference via NuGet?

**Comment by AndreiMisiukevich** [comment]
Hi. https://github.com/AndreiMisiukevich/HotReload/issues/112#issuecomment-520745318

all these bugs are related to code updates. need to investigate

**Comment by pbalbino** [comment]
> why don't you simply add the required reference via NuGet?


I tried to install the package requested by the error, but it was not enough, the error remains.

**Comment by AndreiMisiukevich** [comment]
yeah, it's known issue. There are problem and it needs to be solved)

**Comment by MagicAndre1981** [comment]
> > why don't you simply add the required reference via NuGet?
> 
> I tried to install the package requested by the error, but it was not enough, the error remains.

I have no issues when I add System.Threading.Tasks.Extensions. In Android the package is not really used, it is empty for monodroid (_._)

**Comment by pbalbino** [comment]
> > > why don't you simply add the required reference via NuGet?
> > 
> > 
> > I tried to install the package requested by the error, but it was not enough, the error remains.
> 
> I have no issues when I add System.Threading.Tasks.Extensions. In Android the package is not really used, it is empty for monodroid `(_._)`

First that when installing it says that it will update, still continue with the error.
![hot2](https://user-images.githubusercontent.com/25305220/62942630-1160e500-bdaf-11e9-9781-aee100184835.PNG)
![hot3](https://user-images.githubusercontent.com/25305220/62942671-2dfd1d00-bdaf-11e9-859d-0c58347fbb19.PNG)

**Comment by MagicAndre1981** [comment]
manually edit the packages.config

`<package id="System.Threading.Tasks.Extensions" version="4.5.3" targetFramework="monoandroid81" />`

reload the android part and delete obj/bin folders and build the android app again.

**Comment by pbalbino** [comment]
> manually edit the packages.config
> 
> `<package id="System.Threading.Tasks.Extensions" version="4.5.3" targetFramework="monoandroid81" />`
> 
> reload the android part and delete obj/bin folders and build the android app again.

Where can I find the packages.config file? In my project did not find.

**Comment by MagicAndre1981** [comment]
if you can't find it, you use the packagesreference.

Add this to csproj of .net standard 2.0 and android project:

`<PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.3" />`

**Comment by pbalbino** [comment]
> if you can't find it, you use the packagesreference.
> 
> Add this to csproj of .net standard 2.0 and android project:
> 
> `<PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.3" />`

I made the changes as the images below, even so the error continues.
![hot4](https://user-images.githubusercontent.com/25305220/62946642-77516a80-bdb7-11e9-9cd7-3cb4db9dd7df.PNG)
![hot5](https://user-images.githubusercontent.com/25305220/62946653-7d474b80-bdb7-11e9-8383-8a34aba224ea.PNG)
![hot6](https://user-images.githubusercontent.com/25305220/62946692-918b4880-bdb7-11e9-9415-8bf575de6197.PNG)

**Comment by MagicAndre1981** [comment]
delete the obj folder, here VS creates a project.assets.json for each project that uses PackageReference Include.

**Comment by AndreiMisiukevich** [comment]
don't think it will help
downgrade version to 1.4.15

**Comment by pbalbino** [comment]
> delete the obj folder, here VS creates a project.assets.json for each project that uses PackageReference Include.


I did it already, as you mentioned, I deleted the bin and obj folders for the net standard project and for android.

**Comment by pbalbino** [comment]
> don't think it will help
> downgrade version to 1.4.15

I will test this, I had tried downgrading to version 1.4.18 (which also generated the error), but let's see with this one.

**Comment by pbalbino** [comment]
> don't think it will help
> downgrade version to 1.4.15

It worked after downgrading to version 1.4.15, it's working ... Thanks!

**Comment by MagicAndre1981** [comment]
as I said, because of other issues I use packages.config and here I have no issues to compile it, but get the Mono.CSharp warning, but code reload doesn't work.

**Comment by pbalbino** [comment]
> as I said, because of other issues I use packages.config and here I have no issues to compile it, but get the Mono.CSharp warning, but code reload doesn't work.

Sorry for my lack of knowledge, but how do I work with the packages.config file as you mentioned?

**Comment by MagicAndre1981** [comment]
> Sorry for my lack of knowledge, but how do I work with the packages.config file as you mentioned?

Here is a [question and some answers about it](https://stackoverflow.com/questions/53335453/switch-back-to-packages-config-clarification-on-answer)

**Comment by MagicAndre1981** [comment]
@pbalbino have you tried packages.config way?

**Comment by taublast** [comment]
> 
> 
> > don't think it will help
> > downgrade version to 1.4.15
> 
> It worked after downgrading to version 1.4.15, it's working ... Thanks!

Yep still sitting at 1.4.15, can't make upper versions work. Installing System.Threading.Tasks.Extensions is not helping.

**Comment by AndreiMisiukevich** [comment]
@taublast  i will hide upper versions. Need to fix this issue first

**Comment by taublast** [comment]
Not sure your plugin is really to blame here, i got same error with some other nugets that compile ok on vs 2019 and give the above error on vs 2017. Was forced to switch to vs 2019 because of this.

**Comment by MagicAndre1981** [comment]
as I already wrote, it works for me when I use packages.config for Android app.

**Comment by AndreiMisiukevich** [comment]
try on newest version which would be released today

**Comment by akamud** [comment]
After upgrading to XF 4.2.0.848062 and HotReload 1.5.3 I started having this issue on Azure DevOps (which uses VS for Mac 8.3.1.18). It builds fine locally, but even when adding the `System.Threading.Tasks.Extensions` reference I still get the same exception:

```
"/Users/vsts/agent/2.158.0/work/1/s/src/MyApp.Droid/MyApp.Droid.csproj" (PackageForAndroid target) (1) ->
(_ResolveAssemblies target) -> 
  /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1898,2): error XA2002: Can not resolve reference: `System.Threading.Tasks.Extensions`, referenced by `Microsoft.CodeAnalysis`. Please add a NuGet package or assembly reference for `System.Threading.Tasks.Extensions`, or remove the reference to `Microsoft.CodeAnalysis`. [/Users/vsts/agent/2.158.0/work/1/s/src/MyApp.Droid/MyApp.Droid.csproj]
```

HotReload is the only package that references `Microsoft.CodeAnalysis.CSharp` in my project, I confirmed checking the dependencies with `dotnet depents`:
![image](https://user-images.githubusercontent.com/954102/66870791-9c5d8780-ef78-11e9-8fc7-418a734509fc.png)

I'll let you know if I find anything else related.

**Comment by akamud** [comment]
Update: in case anyone is reading, this doesn't seem to be an issue with HotReload at all, but I'm still trying to figure out a consistent cross-platform fix.

**Comment by AndreiMisiukevich** [comment]
@akamud probably I should remove "code reloading" parts at all and focus on xaml.
