### ISSUE TITLE
There was a conflict between "Mono.CSharp, Version=2.0.5.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756" and "Mono.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756"

### ISSUE THREAD

**Issue by MagicAndre1981** [AndreiMisiukevich/HotReload#112]
ok, I see this entry about a [Mono.Sharp](https://github.com/AndreiMisiukevich/HotReload/blob/aef8f31c89098784ac7a0c1ecc097db13ce3b23c/HotReload.nuspec#L23) conflict in error list as warning when I try to compile an the android app of xamarin.forms project which uses old `packages.config`:

```
There was a conflict between "Mono.CSharp, Version=2.0.5.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756" and "Mono.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756".
1>    "Mono.CSharp, Version=2.0.5.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756" was chosen because it was primary and "Mono.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756" was not.
1>    References which depend on "Mono.CSharp, Version=2.0.5.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756" [C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0\Mono.CSharp.dll].
1>        C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0\Mono.CSharp.dll
1>          Project file item includes which caused reference "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0\Mono.CSharp.dll".
1>            Mono.CSharp
1>    References which depend on "Mono.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756" [].
1>        D:\Foo.App\packages\Xamarin.HotReload.1.4.19\lib
1>etstandard2.0\Xamarin.Forms.HotReload.Reloader.dll
1>          Project file item includes which caused reference "D:\Foo.App\packages\Xamarin.HotReload.1.4.19\lib
1>etstandard2.0\Xamarin.Forms.HotReload.Reloader.dll".
1>            Xamarin.Forms.HotReload.Reloader, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL
1>            D:\Foo.App\Foo.App\Foo.App\bin\Debug\Foo.App.dll
1>Found conflicts between different versions of "Mono.CSharp" that could not be resolved. 
```

**Comment by AndreiMisiukevich** [comment]
for those guys who have the same issue, i suggest to stay on https://www.nuget.org/packages/Xamarin.HotReload/1.4.15 for now (WITHOUT CODE RELOADING)

**Comment by AndreiMisiukevich** [comment]
@MagicAndre1981 you can play with sample. try to build it on windows. perhaps we need to update nuspec file or something else... it won't be so easy

**Comment by MagicAndre1981** [comment]
I need to build a repro, which may take some time. Your demo uses packagesreference include, which causes [startup crash for me in Visual Studio 2017](https://github.com/xamarin/xamarin-android/issues/2076) because the reference assembly is used instead of real implementation.

You added the [reference here](https://github.com/AndreiMisiukevich/HotReload/commit/01303e583fb6639b140febaded1dda5a75be6890) , but in `Xamarin.Forms.HotReload.Reloader.csproj` you use `<PackageReference Include="Mono.CSharp" Version="4.0.0.143" />` I think here is the mismatch.

**Comment by AndreiMisiukevich** [comment]
@MagicAndre1981 feel free to make PR :)

**Comment by MagicAndre1981** [comment]
no sorry, this git shit annoys me all time.

**Comment by AndreiMisiukevich** [comment]
@MagicAndre1981 what shit do you mean?)

**Comment by MagicAndre1981** [comment]
using git at all and PR are terrible (rebase 🤮 )

**Comment by MagicAndre1981** [comment]
any update on this?

**Comment by MuhammadHamzaRajput** [comment]
Warning has gone When I down grade version to Xamarin.HotReload 1.4.15

**Comment by AndreiMisiukevich** [comment]
@MagicAndre1981 not yet

**Comment by MagicAndre1981** [comment]
> @MagicAndre1981 not yet

In VS2017 the code reload is not working for UWP and Android apps.

What are you trying now? Can you also setup a Windows 10 VM and test it there?

**Comment by AndreiMisiukevich** [comment]
i removed mono csharp

So code reloading may be unavailable for android.. or for windows at all

**Comment by MagicAndre1981** [comment]
so it was not possible to use the mono nuget all time?

**Comment by MagicAndre1981** [comment]
> So code reloading may be unavailable for android.. or for windows at all

same like before, changing code has no effect at all (Win10 VM, android part running on phone connected via adb over wifi)

**Comment by AndreiMisiukevich** [comment]
> so it was not possible to use the mono nuget all time?

then it causes compile errors or even errors during installation
