### ISSUE TITLE
HotReload

### ISSUE THREAD

**Issue by XamarinTounsi** [AndreiMisiukevich/HotReload#113]
Hello,

HotReload don't support UWP platform? I downloaded the extension, then I installed HotReload from nuget packages, after I added this code in  app.cs

  public App()
        {
            InitializeComponent();
            ServiceLocator.Add<ICloudService, AzureCloudService>();

            var CloudService = ServiceLocator.Instance.Resolve<ICloudService>();
            CloudService.StoredLoginAsync();

            MainPage = new NavigationPage(new Pages.EntryPage())
            {
                BarBackgroundColor = Color.FromHex("#FFFFFF")
            };
#if DEBUG
            HotReloader.Current.Run(this, new HotReloader.Configuration
            {
                ExtensionIpAddress = IPAddress.Parse("192.168.35.103") // IP for my local machine

            });
#endif
        }
i started HotReload and recived this message 
"Extension has started to listen 15000 for IP auto dicovery"

Cordially

**Comment by AndreiMisiukevich** [comment]
hi, it's limited https://github.com/AndreiMisiukevich/HotReload/issues/87

@MagicAndre1981 knows how to setup it. (as i understand it doesn't work on emulator, but you may debug on another PC. Am i correct?)

**Comment by XamarinTounsi** [comment]
@AndreiMisiukevich Thanks for your answer, @MagicAndre1981 can you explain explain step by step how did you do to make it work ?

Cordially

**Comment by MagicAndre1981** [comment]
you need to run the App on a remote device with [remote debugging](https://docs.microsoft.com/en-US/visualstudio/debugger/run-windows-store-apps-on-a-remote-machine?view=vs-2019). Local machine and simulator doesn't work.

**Comment by XamarinTounsi** [comment]
@MagicAndre1981, thanks for you ansewer, i can now debugg  from my distant machine, i activated the HotReload plugin, i had this message " Extension has started to listen 15001 port for IP auto disovery",
I added this code in my app.cs
#if DEBUG
            HotReloader.Current.Run(this, new HotReloader.Configuration
            {
                ExtensionIpAddress = IPAddress.Parse("192.168.00.01") // IP

            });
#endif
        }
And when i start to edit my Xaml, the HotReload dont work :/

**Comment by AndreiMisiukevich** [comment]
ExtensionIpAddress = IPAddress.Parse("192.168.00.01")  what is it?

**Comment by AndreiMisiukevich** [comment]
remove this line or put your PC IP (where visual studio is hosted)

https://www.groovypost.com/howto/news/microsoft-releases-new-mbsa-scanner-windows-7-server-r2/

**Comment by XamarinTounsi** [comment]
HotReloader.Current.Run(this);
Thank you very much, it work

**Comment by MagicAndre1981** [comment]
> HotReloader.Current.Run(this);
> Thank you very much, it work

nice to hear this.

**Comment by EmilAlipiev** [comment]
I have just tried using remote debugging on uwp but it is partly working. It is very slow and doesnt work on contentviews.
