### ISSUE TITLE
How do I disable HotReload for Release builds?

### ISSUE THREAD

**Issue by TingtingAn** [AndreiMisiukevich/HotReload#115]
I am happy to use HotReload for my Project. But it makes bigger size for android apk.

After unzipping the apk, I see  `Xamarin.Forms.HotReload.Reloader.dll` ,`Microsoft.CodeAnalysis.CSharp.dll` and `Microsoft.CodeAnalysis.dll` in assemblies folder.  
 
Any way to remove them? Thanks!

**Comment by AndreiMisiukevich** [comment]
Hi) Yeas, of course it's possible)

**Comment by AndreiMisiukevich** [comment]
can you share csproj file with me?

**Comment by AndreiMisiukevich** [comment]
Well, it looks like:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>pdbonly</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Xamarin.Forms" Version="4.1.0.555618" />
    <PackageReference Include="Xamarin.HotReload" Version="1.4.19" />
  </ItemGroup>

</Project>
```

You need to put HotReload to Debug ItemGroup section (create new one) like:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>pdbonly</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Xamarin.Forms" Version="4.1.0.555618" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PackageReference Include="Xamarin.HotReload" Version="1.4.19" />
  </ItemGroup>

</Project>
```

**Comment by AndreiMisiukevich** [comment]
Does it help?)

**Comment by TingtingAn** [comment]
I thought it should work.  But unfortunately, it did not disable the HotReload.  I still saw `Xamarin.Forms.HotReload.Reloader.dll` ,`Microsoft.CodeAnalysis.CSharp.dll` and `Microsoft.CodeAnalysis.dll` in assemblies folder.

I just added Xamarin.HotReload nuget to my portable project  and  did the changes.

  ```
<ItemGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PackageReference Include="Xamarin.HotReload" Version="1.4.19" />
  </ItemGroup>
  <ItemGroup Condition="'$(Configuration)|$(Platform)'=='Pro_Debug|AnyCPU'">
    <PackageReference Include="Xamarin.HotReload" Version="1.4.19" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Acr.UserDialogs" Version="7.0.4" />
    <PackageReference Include="CarouselView.FormsPlugin" Version="5.2.0" />
    <PackageReference Include="dotMorten.Xamarin.Forms.AutoSuggestBox" Version="0.7.0" />
    <PackageReference Include="Flurl.Http" Version="2.4.2" />
 <ItemGroup>
```

After that, I built a new apk by Visual Studio App Center and the apk still contains Xamarin.HotReload.

Any idea?  @AndreiMisiukevich

**Comment by AndreiMisiukevich** [comment]
@TingtingAn try to remove bin/obj and remove HotReload from platform projects (leave it only in portable), then try to build again

**Comment by TingtingAn** [comment]
@AndreiMisiukevich   Yea, I just kept Xamarin.HotReload in portable project and removed the bin/obj folders.   Still not work.

I created a  [demo project](https://github.com/TingtingAn/TestForHotReload).  Could you try to build the apk?

**Comment by AndreiMisiukevich** [comment]
@TingtingAn sure, it will take a look
thanks

**Comment by AndreiMisiukevich** [comment]
@TingtingAn , try ```ItemGroup Condition="'$(Configuration)' != 'Release'"```

Full:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>pdbonly</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup Condition="'$(Configuration)' != 'Release'"> 
    <PackageReference Include="Xamarin.HotReload" Version="1.4.15" />
  </ItemGroup> 

  <ItemGroup>
    <PackageReference Include="Xamarin.Forms" Version="4.1.0.555618" />
    <PackageReference Include="Xamarin.Essentials" Version="1.1.0" />
  </ItemGroup>
</Project>
```

**Comment by AndreiMisiukevich** [comment]
Hm, have you got any ideas how to work around it?

**Comment by AndreiMisiukevich** [comment]
Then try it.


And remember.

1) You change build target (e.g. from Debug to Release)
2) **You must force to restore packages by right click on solution -> Restore packages**

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>pdbonly</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <Choose>
    <When Condition="'$(Configuration)' == 'Debug'">
      <ItemGroup> 
        <PackageReference Include="Xamarin.HotReload" Version="1.4.15" />
      </ItemGroup> 
    </When>
  </Choose>

  <ItemGroup>
    <PackageReference Include="Xamarin.Forms" Version="4.1.0.555618" />
    <PackageReference Include="Xamarin.Essentials" Version="1.1.0" />
  </ItemGroup>
</Project>
```

**Comment by TingtingAn** [comment]
@AndreiMisiukevich   It does not work.  And I got the info here.   
 
https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#adding-a-packagereference-condition

You can use a condition to control whether a package is included, where conditions can use any MSBuild variable or a variable defined in the targets or props file. However, at presently, only the TargetFramework variable is supported.

**Comment by AndreiMisiukevich** [comment]
@TingtingAn agrh.. So, it's problem.

Okay, you for now you may comment this line in csproj and build the apk.. need to investigate

**Comment by simix-felipebaltazar** [comment]
linking assemblies don't solve this?

https://docs.microsoft.com/en-us/xamarin/android/deploy-test/linker

**Comment by rudyspano** [comment]
`  ...
    <PackageReference Include="Xamarin.Forms" Version="4.2.0.709249" />
  </ItemGroup>
  
  <ItemGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
	  <PackageReference Include="Xamarin.HotReload" Version="1.4.19" />
  </ItemGroup>`

**Comment by rudyspano** [comment]
```
   ...
    <PackageReference Include="Xamarin.Forms" Version="4.2.0.709249" />
  </ItemGroup>
  
  <ItemGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
	  <PackageReference Include="Xamarin.HotReload" Version="1.4.19" />
  </ItemGroup>
```

This solution seems to work on my side

**Comment by AndreiMisiukevich** [comment]
> ```
>    ...
>     <PackageReference Include="Xamarin.Forms" Version="4.2.0.709249" />
>   </ItemGroup>
>   
>   <ItemGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
> 	  <PackageReference Include="Xamarin.HotReload" Version="1.4.19" />
>   </ItemGroup>
> ```
> 
> This solution seems to work on my side.
> It is very important because of Microsoft.CodeAnalysis.* dependencies that adds 20Mo on our production apk (aot activated , 2 ABI).

so you don't see useless DLLs in your apk?

**Comment by rudyspano** [comment]
Yes. No more libaot-Microsoft.CodeAnalysis.CSharp.dll.so

**Comment by TingtingAn** [comment]
@rudyspano  In fact, commenting HotReload PackageReference is my only soultion.

https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#adding-a-packagereference-condition


According to the Microsoft documentation, we know only the TargetFramework variable is supported for packagereference condition. 

So I think your solution will not work.  I've tried it before and it really doesn't work.
And I am using Visual Studio App Center to build the apk and SDK version is Xamarin.Android 6.4

What is your build environment? Could you try to build the apk by Visual Studio App Center?

**Comment by rudyspano** [comment]
@TingtingAn It is working on Visual Studio for Mac "Archive For Publishing" feature (do not forget to manually delete obj and bin folders). And also in our on Premise CI Environment (Jenkins, MSBuild on Mac). In order to view the APK Package content, we use Android Studio.
The condition is set on ItemGroup and not on PackageReference as sent...

**Comment by TingtingAn** [comment]
Yes, it is working for Archive feature on my local Visual Studio.  So the issue is from Visual Studio App Center.
Let's close this.
Thanks very much! @rudyspano @AndreiMisiukevich
