### ISSUE TITLE
Call DisableExtension() in OnEnviromentSolutionClosed to avoid port change from 15000 to 15001 or 15002

### ISSUE THREAD

**Issue by MagicAndre1981** [AndreiMisiukevich/HotReload#116]
When you close an solution only the state of buttons for Hotrealod get changed, while Reloader still runs. If you open a new solution and click on connect, you now get a message that port is now 15001 instead of 15000 because prev is still running.

So in ExtensionCore.cs call [DisableExtension()](https://github.com/AndreiMisiukevich/HotReload/blob/a8547a0dbd1053092dcecb2f563781993949b0bc/Extension/Xamarin.Forms.HotReload.Extension/ExtensionCore.cs#L104) in [OnEnviromentSolutionClosed(object sender, EventArgs e)](https://github.com/AndreiMisiukevich/HotReload/blob/a8547a0dbd1053092dcecb2f563781993949b0bc/Extension/Xamarin.Forms.HotReload.Extension/ExtensionCore.cs#L129) before update the button state.

**Comment by MagicAndre1981** [comment]
not for this simple fix

**Comment by MagicAndre1981** [comment]
> @MagicAndre1981 feel free to make PR)

done [here](https://github.com/AndreiMisiukevich/HotReload/pull/117). Works so far from what I see.

**Comment by MagicAndre1981** [comment]
Have you released the [extension](https://marketplace.visualstudio.com/items?itemName=StanislavBavtovich.hotreloadxamarinforms) update? Here last update is still from July 2019

**Comment by AndreiMisiukevich** [comment]
@MagicAndre1981 not yet :(
I have no windows installed on my mac for doing it.

Maybe @stanbav will assist in his free time, not sure. Or you can build it, then I will push it to store

**Comment by MagicAndre1981** [comment]
you can setup a Windows VM or [Azure](https://azure.microsoft.com/en-us/services/devops/pipelines/)?

**Comment by AndreiMisiukevich** [comment]
@MagicAndre1981 so little time for that :(
I am trying to maintain 6 own opensource projects and contribute to XF. Sorry for big delays

**Comment by MagicAndre1981** [comment]
ok

**Comment by AndreiMisiukevich** [comment]
would be cool if you could build this package :)

**Comment by AndreiMisiukevich** [comment]
Or I will try to do it on the weekend
