### ISSUE TITLE
Errors after upgrading to Forms 4.2.x

### ISSUE THREAD

**Issue by InquisitorJax** [AndreiMisiukevich/HotReload#118]
I'm seeing this in the output:
Xamarin.Forms.Xaml.XamlParseException: Position 1:1533. An element with the name "_punchCard" already exists in this NameScope.

Downgrading to XForms 4.1.x solves the problem.

**Comment by InquisitorJax** [comment]
I logged a related issue on Forms for this https://github.com/xamarin/Xamarin.Forms/issues/7685

**Comment by AndreiMisiukevich** [comment]
@InquisitorJax don't think they will fix it since there is official hotReload

**Comment by InquisitorJax** [comment]
@AndreiMisiukevich ... I think this is breaking the official hot reload as well

**Comment by AndreiMisiukevich** [comment]
@InquisitorJax ah, got it.
I need to find a little time and update my HotReload.

BTW, i am going to remove "code reloading". Because it piece of s...t

**Comment by AndreiMisiukevich** [comment]
Going to close this ticket, since the same issue occurs on the official hotReload
