### ISSUE TITLE
More Microsoft.CodeAnalysis troubles

### ISSUE THREAD

**Issue by taublast** [AndreiMisiukevich/HotReload#120]
Cannot compile for iOS under Windows with HotReload version upper than 1.4.15 that needs Microsoft.CodeAnalysis. VS 2019.
Error: "The assembly  Microsoft.CSharp.CodeAnalysis.dll can't be AOT-compiled for 32-bit architectures because the native code is too big for the 32-bit ARM architecture."
Can it work without this analysis lib?

**Comment by AndreiMisiukevich** [comment]
![image](https://user-images.githubusercontent.com/10124814/66461162-1aa1c180-ea81-11e9-9796-b6c450e4b5e0.png)

Show me your settings please

**Comment by taublast** [comment]
![image](https://user-images.githubusercontent.com/25801194/66544133-e93bfb00-eb3f-11e9-8d24-799025fa4abf.png)

LLVM on-off same result

**Comment by AndreiMisiukevich** [comment]
![image](https://user-images.githubusercontent.com/10124814/66559083-6d50ab80-eb5d-11e9-960c-bb93a560b69e.png)

and play with supported architectures. Try ARM64 only (try all possible)
