### ISSUE TITLE
Upgrade from 1.4.19 -> 1.5.X = unhandled exceptions

### ISSUE THREAD

**Issue by InquisitorJax** [AndreiMisiukevich/HotReload#122]
### STR
- turn on all 'break on CLR exceptions' 
![image](https://user-images.githubusercontent.com/1822976/67264814-7e2de500-f4ac-11e9-88a1-b6a4c1f164cb.png)
- running on android API 28 emulator

The result is multiple exceptions similar to this
![image](https://user-images.githubusercontent.com/1822976/67264874-a289c180-f4ac-11e9-876c-4e024661c2a1.png)

The app becomes impossible to debug with this setting turned on, as it throws too many exceptions.

**Comment by AndreiMisiukevich** [comment]
@InquisitorJax Hi)
But they are not critical, aren't they?
Well, just need to suppress them

**Comment by InquisitorJax** [comment]
It's not critical in that it doesn't break the app (the exceptions are handled somewhere down the stack),
but being able to debug the app with this setting on is critical to finding real bugs, and this becomes impossible if the app keeps stopping on these other exceptions that are being thrown by dependent libraries.
For me, this is a show-stopper to upgrading.

**Comment by AndreiMisiukevich** [comment]
try 1.5.4-pre (i removed all code reloading stuff)

**Comment by AndreiMisiukevich** [comment]
@InquisitorJax does it work for you now?

**Comment by InquisitorJax** [comment]
sorry @AndreiMisiukevich - I haven't had a chance to test, as I moved on to the official hot reload from xamarin - which for the most part is working now.

**Comment by AndreiMisiukevich** [comment]
@InquisitorJax got it. That's fine. I think it's the right decision.
