### ISSUE TITLE
Was the 'same key already exists' introduced in 4.2 fixed?

### ISSUE THREAD

**Issue by asusralis** [AndreiMisiukevich/HotReload#124]
I'm using the official HR, but it seems this project had the same problem. I've read through the main issue on their repo [here](https://github.com/xamarin/Xamarin.Forms/issues/7833), but all they say is that it will be fixed in the latest HR release. Where exactly do you find that? Is it in the Forms Nuget or through a visual studio update? Both are at the latest for me but I still have this problem.

**Comment by AndreiMisiukevich** [comment]
how do you reproduce this issue?
I've fixed it in my latest nuget version

**Comment by asusralis** [comment]
Thanks for the quick response! I simply have an xaml file with any number of controls named. Even if it's just one control named it will tell me there's duplicate controls with the same name. 

So you've fixed it but they haven't yet? They said the "next HR release" but I have no idea if that's through the forms package or a visual studio release. That was over 2 months ago, I'm fully updated, and yet I have the exact problem described in that issue.

**Comment by AndreiMisiukevich** [comment]
@asusralis sorry, I cannot answer...
