### ISSUE TITLE
Compile fails as of version 1.6.1

### ISSUE THREAD

**Issue by westito** [AndreiMisiukevich/HotReload#125]
Error CS0426: The type name 'CSharpVisual' does not exist in the type 'HotReloader' (CS0426) 
As I see in commit history, hot reload stuff completly commend out of code (???)

https://github.com/AndreiMisiukevich/HotReload/commit/207b38b192068391ebb181031da0d2cb9f0abda9#diff-c0ad30a90ff5339063bc11314c3c9f8a

**Comment by AndreiMisiukevich** [comment]
@westito yes, that's true.
Code reloading was removed

Do you use it?

**Comment by westito** [comment]
Yes of course. What else this stuff used for?

**Comment by westito** [comment]
Code reload can be used without annotating every single class? I hate XAML. I make the UI with only code, build pages from components and widgets (react-like). This stuff works like a charm (except annotating all class). The official hotreload only works with XAML that's why it is nothing for me. Without code reload your component it's like the official one.

**Comment by AndreiMisiukevich** [comment]
> Code reload can be used without annotating every single class? I hate XAML. I make the UI with only code, build pages from components and widgets (react-like). This stuff works like a charm (except annotating all class). The official hotreload only works with XAML that's why it is nothing for me. Without code reload your component it's like the official one.

Well, then stay on the previous version.
I will release a separate nuget for code reload

**Comment by MagicAndre1981** [comment]
ok, so should we now remove the attribute and update to 1.6.1? 

Btw, with .NET 5 Microsoft [kills the Assembly.Load issue as it removes the AppX limitation](https://github.com/dotnet/coreclr/pull/27356/files#diff-ab08932c10f914421e9cfd958f5743d7L208). Now all platforms use same code.

> As of [PR #41759](https://github.com/dotnet/corefx/pull/41759), we no longer build the separate implementation for the UAP platform. So, this issue can't occur anymore with .NET 5 because we now will be using the same .NET Core implementation as on Windows, Linux, Mac.

So when UWP uses .net 5 as base this reload feature should work.

**Comment by AndreiMisiukevich** [comment]
@MagicAndre1981 I think it makes sense to create a separate nuget for code reloading

**Comment by MagicAndre1981** [comment]
maybe you can also create your own Assembly.Load implementation in this extra nugets to avoid the issue.

**Comment by MagicAndre1981** [comment]
> @MagicAndre1981 I think it makes sense to create a separate nuget for code reloading

will we ever get this? Or is the project dead now?

**Comment by AndreiMisiukevich** [comment]
> > @MagicAndre1981 I think it makes sense to create a separate nuget for code reloading
> 
> will we ever get this? Or is the project dead now?

for now, you can use the previous version.

**Comment by MagicAndre1981** [comment]
but here code reloading never worked

**Comment by AndreiMisiukevich** [comment]
Worked on Mac

**Comment by AndreiMisiukevich** [comment]
latest pre-release version

CSharp visual is not used anymore
