### ISSUE TITLE
Triggers and ViewCell issues

### ISSUE THREAD

**Issue by PauchardThomas** [AndreiMisiukevich/HotReload#126]
Hi,

Found 2 issues.

* Specs : 
 * XF : 3.6.0.539721
 * Xamarin.HotReload 1.5.4-pre 

### 1/ Triggers not working anymore after updating ContentView content.

No Exception.

### 2/ Controls inside ViewCell not found after updating ViewCell content.

Trace : 

> 12-31 14:16:27.943 I/mono-stdout(32615): Xamarin.Forms.Xaml.XamlParseException: Position 1:420. Type controls:MyControl not found in xmlns clr-namespace:HotReloadIssue.ControlsXamarin.Forms.Xaml.XamlParseException: Position 1:420. Type controls:MyControl not found in xmlns clr-namespace:HotReloadIssue.Controls
at Xamarin.Forms.HotReloader.ReloadElement (System.Object obj, Xamarin.Forms.HotReloader+ReloadItem reloadItem, System.Type csharpType) [0x0023f] in D:\a\1\s\Reloader\Xamarin.Forms.HotReload.Reloader\HotReloader.cs:673 12-31 14:16:27.944 I/mono-stdout(32615):   at Xamarin.Forms.HotReloader.ReloadElement (System.Object obj, Xamarin.Forms.HotReloader+ReloadItem reloadItem, System.Type csharpType) [0x0023f] in D:\a\1\s\Reloader\Xamarin.Forms.HotReload.Reloader\HotReloader.cs:673 
12-31 14:16:27.945 I/mono-stdout(32615):   at Xamarin.Forms.HotReloader+<>c__DisplayClass31_0.<ReloadElements>b__0 () [0x00025] in D:\a\1\s\Reloader\Xamarin.Forms.HotReload.Reloader\HotReloader.cs:528   at Xamarin.Forms.HotReloader+<>c__DisplayClass31_0.<ReloadElements>b__0 () [0x00025] in D:\a\1\s\Reloader\Xamarin.Forms.HotReload.Reloader\HotReloader.cs:528 
> ### HOTRELOAD ERROR: CANNOT PARSE XAML ###12-31 14:16:27.946 I/mono-stdout(32615): ### HOTRELOAD ERROR: CANNOT PARSE XAML ###

- **See my repo for reproduce : https://github.com/PauchardThomas/HotReloadIssue**

Thanks for you time

**Comment by AndreiMisiukevich** [comment]
![image](https://user-images.githubusercontent.com/10124814/71627335-ee6e8a80-2c02-11ea-8960-d109e1b03253.png)

**Comment by AndreiMisiukevich** [comment]
as for triggers. Can you provide a small xaml sample?

**Comment by PauchardThomas** [comment]
> as for triggers. Can you provide a small xaml sample?

https://github.com/PauchardThomas/HotReloadIssue

**Comment by PauchardThomas** [comment]
I do not change the root view type, just updating the content

**Comment by AndreiMisiukevich** [comment]
add ```<?hotReload preserve.triggers?>``` to your content view xaml

```xaml
<?xml version="1.0" encoding="UTF-8" ?>
<?hotReload preserve.triggers?>
<ContentView x:Class="HotReloadIssue.MyContentView"
             xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d">
    <ContentView.Content>
        <Frame BorderColor="Green">
            <StackLayout> 
                <Label FontSize="Large" Text="This is my content viewssdfgh" />
            </StackLayout>
        </Frame>
    </ContentView.Content>
</ContentView>
```

**Comment by AndreiMisiukevich** [comment]
ViewCells are gone since CollectionView is released. I don't see any sense continue to support them
