### ISSUE TITLE
getStream instead of httppost?

### ISSUE THREAD

**Issue by EmilAlipiev** [AndreiMisiukevich/HotReload#13]
I was just examining your code and there is this one also very similar to yours. i was wondering why did you prefer httppost request instead of getstream like here is doing? https://github.com/patsadow2/XamarinLiveReload/blob/master/XamarinLiveReloadPS/XamarinLiveReloadPS/Program.cs

I am not sure but maybe it is better way, as you can see he is doing localhost connection. Xamarin Livereload was doing similar connection also. maybe thats why we have problem to connect on android emulators with your implementation.

**Comment by AndreiMisiukevich** [comment]
@EmilAlipiev i know, how we can solve this issue. Make requests every 1 sec by timer FROM device/emulator TO laptop/pc. In this case laptop/PC must know, which files it should send to device.

**Comment by EmilAlipiev** [comment]
I think that you dont even need to schedule for 1 sec. you can continue doing it as you do now. only problem here is connection between work station and emulator. Android emulator seems to be working differently than Ios simulator. like in the answer [here ](https://stackoverflow.com/questions/3378501/how-to-browse-localhost-on-android-device)is given localhost can be used with 10.0.2.2 Android recognizes this. yesterday i played around a little bit but i couldnt make it work. maybe it is best way to use getstream with this ip address. i will play around more later when i have time.

**Comment by AndreiMisiukevich** [comment]
@EmilAlipiev I will be grateful any details :)
Probably i will continue investigation.

So, if you will have any ideas, contact me

Btw, let's close this ticket and go ahead with existing one https://github.com/AndreiMisiukevich/HotReload/issues/1
