### ISSUE TITLE
Implement C# reloading not only for pages

### ISSUE THREAD

**Issue by AndreiMisiukevich** [AndreiMisiukevich/HotReload#132]
ContentViews etc.

**Comment by AndreiMisiukevich** [comment]
Check why Commands are not allowed on Android

**Comment by MagicAndre1981** [comment]
I get this message about pages with version 2 under Android (VS2017):

`04-14 09:56:35.977 I/mono-stderr(25963): 	CS1503: Argument "1": Konvertierung von "Foo.App.Views.MainPage" in "Page" nicht möglich.`

and a lot of missings:

> 	CS0103: Der Name "Application" ist im aktuellen Kontext nicht vorhanden.
> 	CS0103: Der Name "Application" ist im aktuellen Kontext nicht vorhanden.
> 	CS0103: Der Name "JsonConvert" ist im aktuellen Kontext nicht vorhanden.04-14 09:56:35.834 I/mono-stderr(25963): 	CS0246: Der Typ- oder Namespacename "XamlCompilationAttribute" wurde nicht gefunden (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).
> 
> 04-14 09:56:35.977 I/mono-stderr(25963): 	CS0246: Der Typ- oder Namespacename "Thickness" wurde nicht gefunden (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).

**Comment by AndreiMisiukevich** [comment]
Hi @MagicAndre1981 )
1st: CodeReloadingEnabled = true - default value.
2nd: Could you please provide a stack trace in English?

**Comment by AndreiMisiukevich** [comment]
Can you build a small sample?

**Comment by MagicAndre1981** [comment]
> 2nd: Could you please provide a stack trace in English?

there is no callstack only the message that the the type was not found. 

```
04-17 09:30:11.121 I/mono-stderr(27060): 	CS0103: Der Name "Application" ist im aktuellen Kontext nicht vorhanden.
04-17 09:30:11.121 I/mono-stderr(27060): 	CS0103: Der Name "JsonConvert" ist im aktuellen Kontext nicht vorhanden.
```

I reacted to your change from OnLoaded to OnHotReloaded, but I still see it.

**Comment by AndreiMisiukevich** [comment]
> > 2nd: Could you please provide a stack trace in English?
> 
> there is no callstack only the message that the the type was not found.
> 
> ```
> 04-17 09:30:11.121 I/mono-stderr(27060): 	CS0103: Der Name "Application" ist im aktuellen Kontext nicht vorhanden.
> 04-17 09:30:11.121 I/mono-stderr(27060): 	CS0103: Der Name "JsonConvert" ist im aktuellen Kontext nicht vorhanden.
> ```
> 
> I reacted to your change from OnLoaded to OnHotReloaded, but I still see it.

Weird, please fill a new issue and attach a very small sample

**Comment by MagicAndre1981** [comment]
> Weird, please fill a new issue and attach a very small sample

I'm struggling to create a demo. I get VS2017 I see [this new issue](https://github.com/xamarin/xamarin-android/issues/2674) with **System.Threading.Tasks.Extensions** for the Android app if I use Package Reference, but the demo project also shows errors with packages.config. 

And in VS2019 the packages.config way seams to be broken, the entries are added several times, that also causes compile errors. Also the android app is here uncompilable because properties are not resolved (appname, sdk, namespace is all empty and I have to reload the solution several times to may have a chance to get it compiled.)

I hate this crappy Visual Studio shit 😢 🤢 🤮

**Comment by MagicAndre1981** [comment]
with VS2019 I now get OutOfMemoryException of devenv.exe when using your extension (and it showed both buttons the same time in toolbox for what ever reason and I have to manually delete the extension folder to get VS2019 starting again) and compiling the android app fails in 2019 with MSB3030, with strange message that Andoid app DLL was not found, while this is the app not a dll.

So I'm unable to provide you a demo. My main projects that I maintain compile fine in 2017 and with the last version 2 I get the posted messages in debug window. This is all help I can give.

**Comment by MagicAndre1981** [comment]
I noticed that only Microsoft.CodeAnalysis [2.9.x](https://github.com/dotnet/roslyn-analyzers/releases/tag/v2.9.9) work with VS2017 

> Release build of Roslyn-analyzers based on Microsoft.CodeAnalysis 2.9.0 NuGet packages. Works with **VS 2017.9** or later.

and the[ 3.x require 2019](https://github.com/dotnet/roslyn-analyzers/releases/tag/v3.0.0), 

> Release build of Roslyn-analyzers based on Microsoft.CodeAnalysis 3.0.0 NuGet packages. Works with **VS 2019 or later**.

so this may also cause my issues that code reload fails.
