### ISSUE TITLE
### HOTRELOAD ERROR: CANNOT RELOAD C# CODE ###

### ISSUE THREAD

**Issue by Sergiojoel9877** [AndreiMisiukevich/HotReload#133]
Hi Andrei.

I'm experiencing this issue on VS for Mac.

Under: 
Xamarin.Forms 4.6.0-pre4
AndroidX.

### HOTRELOAD ERROR: CANNOT RELOAD C# CODE ###
[monodroid-assembly] typemap: unable to find mapping to a managed type from Java type 'com/android/internal/policy/PhoneLayoutInflater'
[monodroid-assembly] typemap: unable to find mapping to a managed type from Java type 'android/content/res/XmlBlock$Parser'
[monodroid-assembly] typemap: module matching MVID [629BCB14-6D67-4F9E-83B5-5F4A64E6918C] not found.
[monodroid-assembly] typemap: module matching MVID [629BCB14-6D67-4F9E-83B5-5F4A64E6918C] not found.
[monodroid-assembly] typemap: module matching MVID [629BCB14-6D67-4F9E-83B5-5F4A64E6918C] not found.
[monodroid-assembly] typemap: type with token 33556167 (0x20006c7) in module {BBFB9F10-9100-4C04-8EF904-15 22:49:02.477 W/monodroid-assembly(27621): typemap: module matching MVID [629BCB14-6D67-4F9E-83B5-5F4A64E6918C] not found.
[monodroid-assembly] typemap: module matching MVID [629BCB14-6D67-4F9E-83B5-5F4A64E6918C] not found.
[monodroid-assembly] typemap: module matching MVID [629BCB14-6D67-4F9E-83B5-5F4A64E6918C] not found.
[monodroid-assembly] typemap: module matching MVID [629BCB14-6D67-4F9E-83B5-5F4A64E6918C] not found.
[monodroid-assembly] typemap: module matching MVID [629BCB14-6D67-4F9E-83B5-5F4A64E6918C] not found.
[monodroid-assembly] typemap: module matching MVID [629BCB14-6D67-4F9E-83B5-5F4A64E6918C] not found.
[monodroid-assembly] typemap: module matching MVID [629BCB14-6D67-4F9E-83B5-5F4A64E6918C] not found.
[monodroi04-15 22:49:02.479 W] typemap: module matching MVID [629BCB14-6D67-4F9E-83B5-5F4A64E6918C] not found.
[monodroid-assembly] typemap: module matching MVID [629BCB14-6D67-4F9E-83B5-5F4A64E6918C] not found.
[monodroid-assembly] typemap: module matching MVID [629BCB14-6D67-4F9E-83B5-5F4A64E6918C] not found.
[monodroid-assembly] typemap: module matching MVID [629BCB14-6D67-4F9E-83B5-5F4A64E6918C] not found.
[monodroid-assembly] typemap: module matching MVID [629BCB14-6D67-4F9E-83B5-5F4A64E6918C] not found.
[monodroid-assembly] typemap: type with token 33556167 (0x20006c7) in module {BBFB9F10-9100-4C04-8EF9-A9C1F37AF2D0} (Mono.Android) not found.
[monodroid-assembly] typemap: unable to find mapping to a managed type from Java type 'android/content/res/XmlBlock$Parser'
[monodroid-assembly] typemap: module matching MVID [629BCB14-6D67-4F9E-83B5-5F4A64E6918C] not found.
[monodroid-assembly] typemap: module matching MVID [629BCB14-6D67-4F9E-83B5-5F4A64E6918C] not found.
[monodroid-assembly] typemap: module matching MVID [629BCB14-6D67-4F9E-83B5-5F4A64E6918C] not found.
[monodroid-assembly] typemap: module matching MVID [629BCB14-6D67-4F9E-83B5-5F4A64E6918C] not found.
[monodroid-assembly] typemap: module matching MVID [629BCB14-6D67-4F9E-83B5-5F4A64E6918C] not found.
[monodroid-assembly] typemap: module matching MVID [629BCB14-6D67-4F9E-83B5-5F4A64E6918C] not found.
[monodroid-assembly] typemap: module matching MVID [629BCB14-6D67-4F9E-83B5-5F4A64E6918C] not found.
[monodroid-assembly] typemap: module matching MVID [629BCB14-6D67-4F9E-83B5-5F4A64E6918C] not found.
[monodroid-assembly] typemap: module matching MVID [629BCB14-6D67-4F9E-83B5-5F4A64E6918C] not found.
[monodroid-assembly] typemap: module matching MVID [629BCB14-6D67-4F9E-83B5-5F4A64E6918C] not found.
[monodroid-assembly] typemap: module matching MVID [629BCB14-6D67-4F9E-83B5-5F4A64E6918C] not found.
[monodroid-assembly] typemap: type with token 33556167 (0x20006c7) in module {BBFB9F10-9100-4C04-8EF9-A9C1F37AF2D0} (Mono.Android) not found.
[monodroid-assembly] typemap: module matching MVID [629BC 22:49:02.538 D/SocketClient(  480): SocketClient sendData done: 614 Address updated ::cd93:1e54:392f:76a9/64 wlan0 1 0 1
[monodroid-assembly] typemap: module matching MVID [629BCB14-6D67-4F9E-83B5-5F4A64E6918C] not found.
[monodroid-assembly] typemap: module matching MVID [629BCB14-6D67-4F9E-83B5-5F4A64E6918C] not found.
[monodroid-assembly] typemap: module matching MVID [629BCB14-6D67-4F9E-83B5-5F4A64E6918C] not found.
[monodroid-assembly] typemap: module matching MVID [629BCB14-6D67-4F9E-83B5-5F4A64E6918C] not found.
[monodroid-assembly] typemap: module matching MVID [629BCB14-6D67-4F9E-83B5-5F4A64E6918C] not found.
[monodroid-assembly] typemap: module matching MVID [629BCB14-6D67-4F9E-83B5-5F4A64E6918C] not found.
[monodroid-assembly] typemap: module matching MVID [629BCB14-6D67-4F9E-83B5-5F4A64E6918C] not found.
[monodroid-assembly] typemap: unable to find mapping to a managed type from Java type 'android/view/DisplayListCanvas'
[monodroid-assembly] typemap: unable to find mapping to a managed type from Java type 'android/view/DisplayListCanvas'
[monodroid-assembly] typemap: unable to find mapping to a managed type from Java type 'android/view/DisplayListCanvas'

**Comment by Sergiojoel9877** [comment]
I'm using the latest version of HotReload [2.0.7]

**Comment by AndreiMisiukevich** [comment]
@Sergiojoel9877 can you build a sample?

**Comment by Sergiojoel9877** [comment]
[Sample_HotReload.zip](https://github.com/AndreiMisiukevich/HotReload/files/4496067/Sample_HotReload.zip)

@AndreiMisiukevich here's the sample.

**Comment by Sergiojoel9877** [comment]
Tested on an emulator running Android 10 a couple of minutes ago, and also presenting the same error.

**Comment by Sergiojoel9877** [comment]
Any updates?

**Comment by AndreiMisiukevich** [comment]
> Any updates?

does it work fine on iOS?
