### ISSUE TITLE
attempting hot reload UWP with remote debugging but on localhost

### ISSUE THREAD

**Issue by MagicPoulp** [AndreiMisiukevich/HotReload#134]
In another old issue, on said one cannot use locally this feature for UWP in Xamarin, only via hotreload on a tablet.
https://github.com/AndreiMisiukevich/HotReload/issues/113

But I wish to understand. If one uses remote debugging on localhost, then why would it not work?

I installed the VIsual studio remote debugger. THen I activated in the project remote debugging and it detected the remote debugger on the computer. WHen I start Visual studio, the remote debugger application says it made a connection.

THen I used the hot reload extension's button with a lightning image. It says connected on port 15000, auto detected IP.

But when modifying XAML, no hot reload happens. There are no logs or errors. What is the technical reason why it does not work?

I have added the option in the initialization of the NuGet Package to specify an IP. I tried 127.0.0,1 and the IPv4 given by ipconfig. Curiously no port is accepted it says it auto-detects it. I tried to add a port anyways and nothing changed.

SO how does this package work? THe extension starts a server port 15000 with autodetected IP it says. WHat does it mean? DOes it connect directly to the remote debugger, or visual studio, or the remote device?

If youy make this work, you can make a fortune selling this to Microsoft.

**Comment by AndreiMisiukevich** [comment]
Hi @MagicPoulp 
Microsoft has its own HotReload :)

**Comment by AndreiMisiukevich** [comment]
@stanbav is aware about this limitation.

**Comment by MagicPoulp** [comment]
Miscrosoft's hot reload does not support UWP before long in the future, not even planned.

I was just curious why it does not work remote debugging locally. It just does nothing and I wish (and maybe others) to understand the internals. I have no idea what happens when click the lightning button.

**Comment by AndreiMisiukevich** [comment]
> Miscrosoft's hot reload does not support UWP before long in the future, not even planned.
> 
> I was just curious why it does not work remote debugging locally. It just does nothing and I wish (and maybe others) to understand the internals. I have no idea what happens when click the lightning button.
> 
> One guy made UWPÅ work via remote debugging on a separate tablet device. So what is the fundamental difference with remote debugging to local machine?

I don't know, sorry. But it doesn't work for some reason. Perhaps @stanbav @MagicAndre1981 know

**Comment by MagicAndre1981** [comment]
UWP apps can't connect to localhost (limitation from Windows 8 apps, that was never removed). I develop in a VM without touch, so I use remote debugging to a tablet, here it works hotreload works.

Have you tried the Hotreload from VS2019? I still use 2017 so I need this extension from @AndreiMisiukevich  .

**Comment by MagicPoulp** [comment]
Thansk for the good info. IT is called "Network isolation". It is said it can be disabled in Visual Studio.
https://stackoverflow.com/questions/34589522/cant-see-localhost-from-uwp-app

I will try to make it work. Then I will petition Microsoft so they "sponsor" your tool :)

DO you realize? Microsoft working with open source community?

**Comment by AndreiMisiukevich** [comment]
> Thansk for the good info. IT is called "Network isolation". It is said it can be disabled in Visual Studio.
> https://stackoverflow.com/questions/34589522/cant-see-localhost-from-uwp-app
> 
> I will try to make it work. Then I will petition Microsoft so they "sponsor" your tool :)
> 
> DO you realize? Microsoft working with open source community?
> 
> I use VS2019. The version does not matter. Xamarin has no hot reload for UWP before, it seems, at least 2 years in the future.

:)

**Comment by MagicPoulp** [comment]
Here is the xamarin commmunity thread:
https://developercommunity.visualstudio.com/idea/661682/xaml-hot-reload-for-xamarinforms-on-uwp.html?childToView=1073283#comment-1073283

**Comment by MagicAndre1981** [comment]
since VS2019 [16.8 Preview2, the official XAML Hotreload supports UWP](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#xaml-tools-wpf-uwp--xamarinforms).

> in this release we begin to rollout support for a highly requested feature that enables the new changes only XAML Hot Reload support in Xamarin.Forms Projects when targeting UWP.

**Comment by AndreiMisiukevich** [comment]
> since VS2019 [16.8 Preview2, the official XAML Hotreload supports UWP](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#xaml-tools-wpf-uwp--xamarinforms).
> 
> > in this release we begin to rollout support for a highly requested feature that enables the new changes only XAML Hot Reload support in Xamarin.Forms Projects when targeting UWP.

Yeah, that's awesome )

**Comment by MagicPoulp** [comment]
ok then we close this
