### ISSUE TITLE
Picker with MVVM

### ISSUE THREAD

**Issue by MarMarIV** [AndreiMisiukevich/HotReload#137]
Hi, i found issue with Picker. After reloading page, picker selected value is removed

Steps to reproduce:
 - Select value from Picker
 - Make any change in XAML and save
 - HotReload refresh page sucessfully, but SelectedItem is set to NULL

Example:
[HotReloadPickerTest.zip](https://github.com/AndreiMisiukevich/HotReload/files/5217847/HotReloadPickerTest.zip)

**Comment by jerry2007** [comment]
+1

**Comment by AndreiMisiukevich** [comment]
Does official hot reload work properly?

**Comment by MarMarIV** [comment]
Yes, HotReload is working fine. But with usage of Picker, after page reload, Picker lost information about SelectedItem (someting invoke/reset SelectedItem = NULL)

**Comment by AndreiMisiukevich** [comment]
> Yes, HotReload is working fine. But with usage of Picker, after page reload, Picker lost information about SelectedItem (someting invoke/reset SelectedItem = NULL)

I mean **official** hot reload with the same case?

This one is not **official** embedded in Visual Studio.
This is a 3-rd party *non-official* nuget package.

**Comment by AndreiMisiukevich** [comment]
Well, I see you are using official MS HotReload (This is different one with my nuget package). So you should open issues in the different place.

**Comment by MarMarIV** [comment]
Yeah, I get it. Bad project. I am sorry
