### ISSUE TITLE
InitComponent is necessary?

### ISSUE THREAD

**Issue by EmilAlipiev** [AndreiMisiukevich/HotReload#14]
You mentioned on xamarin forums that InitComponent is not required but when i try sample project and comment out InitComponent lines in xaml.cs files, it doesnt work. how to use it without InitComponent? samples are not probably up to date

**Comment by AndreiMisiukevich** [comment]
@EmilAlipiev i said, that ```InitComponent(InitializeComponent);``` isn't necessary, but you will have to write ```InitComponent();```

So, answer: Yes, it's necessary.

Maybe, it would be better to generate code, but i don't know how to achieve it (Like Fody did)
