### ISSUE TITLE
C# reloading not working in iOS Simulator

### ISSUE THREAD

**Issue by ericbrunner** [AndreiMisiukevich/HotReload#141]
Hi,

I get that the HOTRELOAD started at Port 8000, but when I enalbed Hotreload in the Visual Studio Toolbar it states that it is listening on Port 15000. I added the --enable-repl in Debug|iPhoneSimulator mtouch settings. 

I just tried to set a background color on a grid -> saved the file -> nothing changed. The Hotreload (your's) is enabled in toolbar.

PS: that attribute doesn't exist 	`[HotReloader.CSharpVisual] `

**Comment by AndreiMisiukevich** [comment]
I propose to use official Microsoft solution
