### ISSUE TITLE
Is it still working for Rider?

### ISSUE THREAD

**Issue by ziomek64** [AndreiMisiukevich/HotReload#142]
Hello,
Is this HotReload still supposed to be working for Rider? I've tested on newest Rider version. I installed plugin, nugetpackage, did code change.

The Rider's implementation of hot reload is annoying, it brings the page back to the top every hot reload so I wanted to test something else. Is it the case here too? As I can't get it to work

**Comment by AndreiMisiukevich** [comment]
Hi @ziomek64 
Unfortunately, I think this project is not actively maintained anymore

@iBavtovich did rider plugin though if he is still interested in fixing anything (I doubt)

**Comment by iBavtovich** [comment]
Hi @ziomek64 I will take a look and come back to you with the answer soon.
Thanks, for reporting the issue.

**Comment by ziomek64** [comment]
@iBavtovich  Was this plugin changes-only hot reload? That's what I'm looking for mainly.  Rider has full page reload only, vs2019 has changes only  hot reload but I'd like to use Rider

**Comment by AndreiMisiukevichEmobilitydv** [comment]
@ziomek64 it's not changes-only

CC @iBavtovich

**Comment by AndreiMisiukevich** [comment]
@ziomek64 it's not changes-only

CC @iBavtovich

**Comment by ziomek64** [comment]
> @ziomek64 it's not changes-only
> 
> CC @iBavtovich

@AndreiMisiukevich then its probably gonna be same as in Rider, meaning it resets page back to the top on every hot reload?

**Comment by AndreiMisiukevich** [comment]
@ziomek64 it will clear page's content and recreate all views inside it from scratch using new xaml.

**Comment by iBavtovich** [comment]
Hi @ziomek64.
I have fixed the issues with the Rider 2021.2+, as there were bunch of changes in the Rider/Intelij platform, so plugin wasn't  working.
The version 1.4.6 will be available for download in Rider within 2 days (required JetBrains confirmation).

If you still interested in checking the project, you are welcome :)

**Comment by ziomek64** [comment]
I will try it out ! @iBavtovich
