### ISSUE TITLE
What is the different of hotreload between xamarin.form's xaml and xamarin.native's C#?

### ISSUE THREAD

**Issue by xtuzy** [AndreiMisiukevich/HotReload#143]
Hello, i see Android Studio have Apply Change function to hot reload java , and ios also have InjectionIII to hot reload, i want bring they to xamarin.native , but i haven't got a clue, do you have some advice?

**Comment by ziomek64** [comment]
I think there's gonna be .NET hot reload or something like that in c#?

**Comment by AndreiMisiukevich** [comment]
Yeah, I think.NET MAUI will introduce some C# hot reload)
