### ISSUE TITLE
Not updating on changes - android device - win64

### ISSUE THREAD

**Issue by LeoJHarris** [AndreiMisiukevich/HotReload#16]
Hi @AndreiMisiukevich ,

I am having issues with your plugin in that I cannot get anything to reload when saving,

I am using a real android device for hot reload and have followed your setup steps:

1. have added the nuget to NETSTANDARD and android and iOS projects

2. added to App file the code `#if DEBUG
            HotReloader.Current.Start();     
#endif`

3. ALL XAML partial classes have added the `this.InitComponent();` for debugging.

4. Downloaded observer.exe and run that from in the NETSTANDARD project as is (no change to URL just run as is)

5. I then start debugging my application.

6. I make changes in XAML and save but nothing happens.

Any ideas? I checked the address the app is running from in the output at application start but it changes every time app is started/restarted. 

If you need anything let me know. Thanks

Great plugin and cant wait to get this working 👍

**Comment by AndreiMisiukevich** [comment]
@EmilAlipiev hi. Could you please help us?

@LeoJHarris 
1) Are you able to check that system works on my sample ?
2) Can you see any updates in cmd after saving the file ? (It should write something like "FILE CHANGED" in command line of observer)


Ahhh.. step (4). You said that you run observer.exe as is.
So, like ```observer.exe``` in cmd, correct?
You must use url of your device!
```observer.exe u=http://192.168.0.3``` (your device id you can find in application output of VISUAL STUDIO)
Also, make sure, that you PC/Laptop and you device use the same local network (the same Wi-fi)

**Comment by AndreiMisiukevich** [comment]
@LeoJHarris did you solve the problem?

**Comment by LeoJHarris** [comment]
@AndreiMisiukevich I Found the device URL in the VS output window and set that as the URL for the observer and the path to the root .NETSTANDARD project in cmd (where the observer file is). I just restarted the debugger a couple of times without success while observer still running. I checked the cmd output and no details saying "FILE CHANGED" when saving the XAML while debugging - Ill check your sample today and confirm if the same issue. As only still tested on my project however I am following the steps outlined to the best of my understanding. Ill get back to you on this soon

**Comment by AndreiMisiukevich** [comment]
@LeoJHarris hm, looks like observer doesn't detect any changes.. hmm
Yes, please, try with my sample
If no luck, try to build observer from solution (just select console app and rebuild action, then find exe file in bin folder)

**Comment by AbdelrahmanGIT** [comment]
I think this maybe the same as #17

**Comment by AndreiMisiukevich** [comment]
@LeoJHarris check it again on the next week
Should be working :)
