### ISSUE TITLE
Observer.exe doesn't register a file change when using visual studio as the ide on windows

### ISSUE THREAD

**Issue by AbdelrahmanGIT** [AndreiMisiukevich/HotReload#17]
When changing a xaml file through visual studio, vs doesn't change the file instead  it writes the content to temporary file then removes the original file and then renames the temp file to the original file name.

Which in `FileSystemWatcher` eyes its a delete then rename the problem is that the current Filter isn't setup to detect this kind of behavior and as a result it doesn't detect any changes.

A way to solve this is by adding this filter to the list `NotifyFilters.FileName` this will allow `FileSystemWatcher` to detect `Rename` events but it will also introduce some weird behavior which also will make `FileSystemWatcher` detect the temp file which looks somthing like this `filename.xaml~RF14c34af7.TMP` a way around it is to check wither the file `EndsWith(".xaml") or not

my OS is `win10` and i use `visual studio 2017/2019` which both has the same issue

i will be happy to contribute this as well if it's confirmed as an issue

**Comment by AndreiMisiukevich** [comment]
Wait PR's
