### ISSUE TITLE
Allow to use HotReload without modifying all code-behind files

### ISSUE THREAD

**Issue by AndreiMisiukevich** [AndreiMisiukevich/HotReload#20]
It would be awesome to avoid writing of next lines in every **xaml.cs** file
```csharp
this.InitComponent(InitializeComponent);
```

**Comment by AbdelrahmanGIT** [comment]
I think maybe listening to `PageAppearing/PageDisappearing`  in the `Application` class but in that case we need to retrieve `InitializeComponent` using reflection also we may need some kind of flag to avoid init multiple times if it will create a problem

**Comment by AndreiMisiukevich** [comment]
@AbdelrahmanGIT 

We need to attach our code to Xaml.cs constructors.

PageAppearing/PageDisappearing ... hm.. need to think about it.. We also need to update ALL elements on the page (including Cells, Views)

**Comment by AndreiMisiukevich** [comment]
Done!
Check newest version. It will be available in very short time
