### ISSUE TITLE
Unhandled Exception: System.IO.IOException: The process cannot access the file '...Views\MenuPage.xaml' because it is being used by another process.

### ISSUE THREAD

**Issue by huyjack178** [AndreiMisiukevich/HotReload#21]
It throws when run observer.exe

**Comment by AndreiMisiukevich** [comment]
Seems you opened this file for edit in some redactor except VS ?

Win / Mac ?

**Comment by huyjack178** [comment]
> Seems you opened this file for edit in some redactor except VS ?
> 
> Win / Mac ?

I develop in windows and use iOS emulator in paired MAC

**Comment by AndreiMisiukevich** [comment]
> > Seems you opened this file for edit in some redactor except VS ?
> > Win / Mac ?
> 
> I have check but only open in VS. I develop in windows and use iOS emulator in paired MAC

Good point.

Will you get the same exception if unpair mac and just try to update xaml ?

**Comment by huyjack178** [comment]
> > > Seems you opened this file for edit in some redactor except VS ?
> > > Win / Mac ?
> > 
> > 
> > I have check but only open in VS. I develop in windows and use iOS emulator in paired MAC
> 
> Good point.
> 
> Will you get the same exception if unpair mac and just try to update xaml ?

Yes, get the same

**Comment by AndreiMisiukevich** [comment]
@huyjack178 and one more check please.

Close VS totally and open xaml file in text editor. Try to edit now

Still got the error? It's very strange
-
Maybe restarting PC will help....

**Comment by AndreiMisiukevich** [comment]
@huyjack178 unfortunately i don't have Win PC... Mac only :(

Need help in debugging this case

**Comment by huyjack178** [comment]
> @huyjack178 and one more check please.
> 
> Close VS totally and open xaml file in text editor. Try to edit now
> 
> ## Still got the error? It's very strange
> Maybe restarting PC will help....

I have restarted PC. Open XAML file in notepad. 1st save show NO CONNECTION. 2nd save show Exception as well

**Comment by AndreiMisiukevich** [comment]
@huyjack178 NO Connection means that file was read but observer could not send it to your simulator (as it isn't started)

But why after that you get such exception.. no idea

You could try to put any xaml file in bin/debug directory of observer project and debug what's wrong..

hmmmm very strange

**Comment by huyjack178** [comment]
I run emulator and try again, not show NO Connection but not reload UI and the 2nd save still throw exception. I use windows 10

**Comment by AndreiMisiukevich** [comment]
Ok, got it
I will try to solve

**Comment by huyjack178** [comment]
> Ok, got it
> I will try to solve

any news sir?

**Comment by AndreiMisiukevich** [comment]
@huyjack178 hi, one my colleague works on VS Extension :) He promised to create in on next weekend. So, hope it will solve this issue (you won't need to use observer.exe)

**Comment by stanbav** [comment]
@huyjack178 please try out [this extension](https://marketplace.visualstudio.com/items?itemName=StanislavBavtovich.hotreloadxamarinforms). That's the one @AndreiMisiukevich was talking about :)

**Comment by AndreiMisiukevich** [comment]
@huyjack178 try with extension please :)

**Comment by huyjack178** [comment]
thank you so much

**Comment by huyjack178** [comment]
> @huyjack178 try with extension please :)

how to config extension, I don't see it in Tools menu

**Comment by AndreiMisiukevich** [comment]
@huyjack178 we will add info about configuration a little bit later :)
@stanbav could you please make PR with doc?

**Comment by stanbav** [comment]
@huyjack178 To show on Visual Studios toolbar next steps required: Tools -> Customize -> Tick "Xamarin.Forms Hot Reload" checkbox. An "lighting" icon will appear - just press it.

@AndreiMisiukevich will update Readme this weekend.
