### ISSUE TITLE
Support with PrismApplication

### ISSUE THREAD

**Issue by IoTFier** [AndreiMisiukevich/HotReload#22]
How to configure this extension in the set up which uses Prism Library for Xamarin Forms 3.5+ , Prism Library v7.1+ with dryloc as IoC ?

**Comment by AndreiMisiukevich** [comment]
Hi @IoTFier 
What exactly is your issue ? :)

Did you read Readme file?

Call it once
``` csharp
HotReloader.Current.Start();
```
And all xaml.cs files (which you want to reload with HotReload
``` csharp
this.InitComponent(InitializeComponent); // instead of InitializeComponent();
```

Is it your issue? https://github.com/AndreiMisiukevich/HotReload/pull/5

**Comment by IoTFier** [comment]
In Prismbased Xamarin Forms application the App is derived from PrismApplication base class which doesn't take the default constructor. Adding that default constructor per your readme throws following error. 

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0111	Type 'App' already defines a member called '.ctor' with the same parameter types	

I truly appreciate your help in helping us. But, I will use this extension again when it has been developed and validated against Prism library and when we don't to call custom initialization routine in all partical xaml.cs files.

Thank you again.

**Comment by AndreiMisiukevich** [comment]
You can call this method in any place ```HotReloader.Current.Start();```
In AppDelegate.cs or MainActivity.cs or OnStart method of application etc.

**Comment by AndreiMisiukevich** [comment]
You need to call it before opening any reloadable view. So, put in AppDelegate and MainActivity before creating application.

Hope it will help

**Comment by jbravobr** [comment]
@AndreiMisiukevich I try everything and still not working, I got this ### HOTRELOAD ERROR: 'x:Class' NOT FOUND ###. Any ideas ?

**Comment by AndreiMisiukevich** [comment]
@jbravobr hi
could you please provide small sample with this issue?

**Comment by jbravobr** [comment]
@AndreiMisiukevich here: https://github.com/jbravobr/ArcTouch_CHALLENGE. At the exactly moment it's without the HotReload, but you could add it bac again and test

**Comment by AndreiMisiukevich** [comment]
@jbravobr 

   ```x:Class                ="arcthouchapply.Views.MovieSelectionPage">```

try to remove spaces
just
```   x:Class="arcthouchapply.Views.MovieSelectionPage">```

**Comment by jbravobr** [comment]
The spaces it's just the formating style of the code, but I'll try it

**Comment by jbravobr** [comment]
@AndreiMisiukevich sorry for the delay, but it's works! Thanks
