### ISSUE TITLE
[Enhancement] Extension for VS for Mac

### ISSUE THREAD

**Issue by AndreiMisiukevich** [AndreiMisiukevich/HotReload#23]
It would be awesome to have this tool for Mac too

**Comment by stanbav** [comment]
@AndreiMisiukevich assign on me - guess will be able to release it this or next weekend.

**Comment by AndreiMisiukevich** [comment]
@stanbav good job!

**Comment by akamud** [comment]
Where can we find the source code for the extension?

**Comment by stanbav** [comment]
@akamud I wouldn't like to open source code of the extension now. Since it very messy and needs to be reengireed. Unfortunately I don't have much time to do that. 
For now you can report extension-related  critical and major issues here and I will try to fix it asap.
