### ISSUE TITLE
[Discussion/Idea] Use Fody to simplify setup

### ISSUE THREAD

**Issue by akamud** [AndreiMisiukevich/HotReload#25]
I was wondering if we could use [Fody](https://github.com/Fody/Fody) to remove this page setup:

```csharp
#if DEBUG
            this.InitComponent();
#else
            InitializeComponent();
#endif
```

Right now this feels cumbersome as it is needed in every page. With Fody we could automatically change this call to the propery way, adding a check for a compilation symbol. For example, we could avoid doing that if we find a `DISABLE_HOT_RELOAD` compilation symbol.

What do you think?

**Comment by AndreiMisiukevich** [comment]
hi @akamud https://github.com/AndreiMisiukevich/HotReload/issues/20

I work on this :)

**Comment by AndreiMisiukevich** [comment]
duplicated
