### ISSUE TITLE
VS2019 Preview4: Performance Warning

### ISSUE THREAD

**Issue by MagicAndre1981** [AndreiMisiukevich/HotReload#26]
When I start Visual Studio 2019 (preview4 in my case) I get a Performance warning:

![image](https://user-images.githubusercontent.com/8274816/53554043-2f0efa80-3b3f-11e9-894b-47a636abfa50.png)

clicking on "Manage Performance" shows that Hotreload uses a Deprecated API:

![image](https://user-images.githubusercontent.com/8274816/53553931-fe2ec580-3b3e-11e9-96b9-5d768ce380e1.png)

Clicking on _More information about this issue_ points to this page:

https://docs.microsoft.com/en-us/visualstudio/extensibility/synchronously-autoloaded-extensions?view=vs-2017

**Comment by stanbav** [comment]
Fixed in 1.1.0 release.

**Comment by MagicAndre1981** [comment]
ok, now I get a new warning: 

![image](https://user-images.githubusercontent.com/8274816/54490235-622de980-48b4-11e9-85fd-a3cfbf41777e.png)

![image](https://user-images.githubusercontent.com/8274816/54490286-d49ec980-48b4-11e9-811b-5804ca9df48b.png)
