### ISSUE TITLE
Lost  page content when reload 

### ISSUE THREAD

**Issue by huyjack178** [AndreiMisiukevich/HotReload#27]
Please take a look in this photo, when reload it lost all content in windows VS

![image](https://user-images.githubusercontent.com/11793001/53616507-72d43380-3c15-11e9-8e8b-3ae415f236a4.png)

**Comment by tnolan2** [comment]
I have the same issue. Was working great all day, until this.

**Comment by AndreiMisiukevich** [comment]
@tnolan2 @huyjack178 could you please provide small sample?

**Comment by AndreiMisiukevich** [comment]
Probably you had mistakes in xaml during designing?

**Comment by huyjack178** [comment]
I use prism and that page is in the modules of prism

**Comment by AndreiMisiukevich** [comment]
@huyjack178 could you please create small sample project with this issue?
i will debug it :) 👍

**Comment by tnolan2** [comment]
@AndreiMisiukevich I did a little bit of debugging on this. In my case I only see this issue when I have a page with a converter inside my page resources.

<ContentPage.Resources>
        <converters:NegateBooleanConverter x:Key="Inverter" />
</ContentPage.Resources>

I have also noticed when I have a toolbaritem in my page it will duplicate when saving. I am using prism on xamarin 4 preview. I can submit a sample later. I can probably swap most converters out for data triggers to alleviate the issue on my end.

**Comment by tnolan2** [comment]
I fixed the issue by wrapping the converters in a resourcedictionary. After looking at the xamarin docs it looks like they should be wrapped in a resource dictionary regardless.
Xamarin doc reference: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/converters

ContentPage.Resources
ResourceDictionary
converters:NegateBooleanConverter x:Key="Inverter"
ResourceDictionary
ContentPage.Resources

**Comment by AndreiMisiukevich** [comment]
v 1.2.1
