### ISSUE TITLE
[Enhancement] Create project logo

### ISSUE THREAD

**Issue by AndreiMisiukevich** [AndreiMisiukevich/HotReload#28]
@baranpirincal Hi :)
Would you like to contribute logo for this project as well?)

You did amazing work for CardsView https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView/CardsView.cs

Regards

**Comment by baranpirincal** [comment]
Hey @AndreiMisiukevich :)

I think you wanted something like that:

![hotreload](https://user-images.githubusercontent.com/37786733/55577140-847c8f80-571b-11e9-8e33-9f66fa2a0502.jpg)

If you agree with that, I can work more on that and make more characteristic. I am waiting your opinion! :)

**Comment by AndreiMisiukevich** [comment]
@baranpirincal yeah! it look amazing!
It would be great to have this icon with text and without!)

**Comment by AndreiMisiukevich** [comment]
@stanbav do you like it too ?)

@baranpirincal

**Comment by stanbav** [comment]
@AndreiMisiukevich looks good :)

**Comment by AndreiMisiukevich** [comment]
Look forward to see final result :)

**Comment by AndreiMisiukevich** [comment]
@baranpirincal hey :)

**Comment by baranpirincal** [comment]
![hotreload1](https://user-images.githubusercontent.com/37786733/56910087-5c7e1300-6ab2-11e9-8d5b-a233d4471599.jpg)

**Comment by baranpirincal** [comment]
Hey again, sorry I was too busy last weeks.

I prefer to use last variation of logo design, what do you think about it?

**Comment by AndreiMisiukevich** [comment]
@baranpirincal wow !) Looks amazing

**Comment by baranpirincal** [comment]
@AndreiMisiukevich 

Thanks! I am happy that you liked it.

I can upload the logo design in several format on repository and send a pull-request if you completely okay for that one.

![asas](https://user-images.githubusercontent.com/37786733/56948821-f9d05a00-6b39-11e9-9bea-ad3cbffef545.jpg)

**Comment by AndreiMisiukevich** [comment]
@baranpirincal yeah, it would be awesome! 

Could you please send several formats (including colored and white-black as well)

Super star ! :) You rock!

**Comment by baranpirincal** [comment]
@AndreiMisiukevich
 
Thank you for your nice words!
I uploaded the logo design as svg/pdf/png/jpg  

Good luck!

**Comment by AndreiMisiukevich** [comment]
@baranpirincal great job!
