### ISSUE TITLE
Allow multiple connections

### ISSUE THREAD

**Issue by ChasakisD** [AndreiMisiukevich/HotReload#29]
First of all, i would like to say thanks for this amazing extension. It's the first that actually works, even with custom views and custom renderers.

A lot of times you have to test on a lot of platforms and devices. It would be better to allow the visual studio to connect with multiple devices and when sending the xaml, it should send it to all the devices.

I could work on that. I could add this feature into the observer, but it seems that the vsix is not on this repository.

**Comment by AndreiMisiukevich** [comment]
Hey @ChasakisD Thanks for feedback :) I'm glad to read it :)

**Comment by MagicAndre1981** [comment]
what about using PC names (when using UWP apps of XF project) instead of IPs? IPs can change on DHCP very often

**Comment by MagicAndre1981** [comment]
any update on this? I would also like to run UWP/Android app same time and see how xaml updates (for example OnPlatform entries) look on each platform

**Comment by AndreiMisiukevich** [comment]
@MagicAndre1981 work is in progress. I hope it will be available at this week (probably at weekend @stanbav will push new version of extensions)

**Comment by MagicAndre1981** [comment]
thanks for the update

**Comment by stanbav** [comment]
Included in 1.1.0 release.
@MagicAndre1981, @ChasakisD
