### ISSUE TITLE
Not working for TabbedPage

### ISSUE THREAD

**Issue by PWaliaDev** [AndreiMisiukevich/HotReload#3]
I have changed inside children control of TabbedPage. View has not been refreshed.

**Comment by AndreiMisiukevich** [comment]
Hi, what exactly did you change?

**Comment by PWaliaDev** [comment]
I created SampleApp with TabbedPage. 
TabbedPage has children MainPage. I changed Label text inside MainPage but nothing changed on simulator.

**Comment by AndreiMisiukevich** [comment]
@PWaliaDev great, thanks. I will check this case

**Comment by AndreiMisiukevich** [comment]
Check my sample
I tried next code

```csharp
MainPage = new TabbedPage
            {
                Children = {
                    new MainPage(),
                    new SecondPage()
                }
            };
```

And everything works as expected. So, i wait the sample with reproduction of this issue

**Comment by PWaliaDev** [comment]
This code is not working. 
Let say have a Label "nameLbl" in Xaml of page.


public MainPage()
        {
#if DEBUG
            this.InitializeElement();
#else
            InitializeComponent();
#endif


nameLbl.TextColor = Color.White;
        }

**Comment by AndreiMisiukevich** [comment]
@PWaliaDev could you please provide full sample project in zip 
...
As for named views, I am afraid this isn't supported by my plugin

**Comment by AndreiMisiukevich** [comment]
@PWaliaDev hey) could you please provide me a reproduction sample?)

**Comment by AndreiMisiukevich** [comment]
@PWaliaDev hey)

**Comment by PWaliaDev** [comment]
@AndreiMisiukevich  was trying for TabbedPages but its working 
May be i was missing something.

But yes is not working for  named views. getting null exception.

**Comment by AndreiMisiukevich** [comment]
@PWaliaDev as for named view.. it isn't supported and i'm not sure, if it will be possible to support at all.

Closing this issue for now, if you have sample of original issue, let me know.
