### ISSUE TITLE
ToolBarItems incrementing

### ISSUE THREAD

**Issue by stntz** [AndreiMisiukevich/HotReload#32]
When you save a page that has a toolbaritem defined in xaml, it adds a duplicate and keeps adding everytime when you save.

**Comment by AndreiMisiukevich** [comment]
Thanks 😊

**Comment by ChasakisD** [comment]
The same is happening also for the TabbedPage items. All of the tabs are added to the current TabbedPage after reload.

**Comment by AndreiMisiukevich** [comment]
@ChasakisD do you mean tabbed page children ?

**Comment by ChasakisD** [comment]
Yes. Tested on both Android and iOS while children pages are set in xaml.

**Comment by AndreiMisiukevich** [comment]
v 1.2.1
