### ISSUE TITLE
Add a warning to extension if Hotreload is not connected like "Live reload"

### ISSUE THREAD

**Issue by MagicAndre1981** [AndreiMisiukevich/HotReload#33]
The retired Microsoft [Live reload extension](https://marketplace.visualstudio.com/items?itemName=Xamarin.XamarinLiveReload) adds this little yellow bar over the opened XAML if it is not connected:

![image](https://user-images.githubusercontent.com/8274816/53870646-f073b700-3ffa-11e9-8d87-1a87da4439c5.png)

It would be nice if this was be also added here. I was confused why the page did not update until I noticed I  had not clicked on "connect" in toolbar.

![image](https://user-images.githubusercontent.com/8274816/53870918-709a1c80-3ffb-11e9-9d66-b3d419da13d0.png)

**Comment by stanbav** [comment]
Included in 1.1.0 release.
@MagicAndre1981

**Comment by MagicAndre1981** [comment]
ok, I see it, but only shortly. Next I saw the [message that VS was unresponsive](https://github.com/AndreiMisiukevich/HotReload/issues/26#issuecomment-473658881) and not the bar is gone

**Comment by stanbav** [comment]
@MagicAndre1981 going to revert this functionality in 1.1.2 and test again - please update to 1.1.2.

**Comment by stanbav** [comment]
@MagicAndre1981 could you check this Beta build of extension ?
https://github.com/stanbav/HotReloadExtension-Beta/blob/master/Windows/Xamarin.Forms.HotReload.Extension.WinVS.vsix

**Comment by MagicAndre1981** [comment]
@stanbav with the new beta version VS2019 Preview no longer shows the perf warning for me

**Comment by stanbav** [comment]
@MagicAndre1981 Nice. 1.1.3 will include this fix.

**Comment by MagicAndre1981** [comment]
@stanbav  great. do you have any idea why I can't connect Hotreload to local device/simulator UWP app? Remote device works fine.

**Comment by stanbav** [comment]
@MagicAndre1981  Hmm, need to investigate that issue, could you create a ticket for this issue? so we don't forget about that.

**Comment by MagicAndre1981** [comment]
> @MagicAndre1981 Hmm, need to investigate that issue, could you create a ticket for this issue? so we don't forget about that.

done:

https://github.com/AndreiMisiukevich/HotReload/issues/41

**Comment by stanbav** [comment]
Thanks !

**Comment by MagicAndre1981** [comment]
@stanbav 

there is a bug:

![image](https://user-images.githubusercontent.com/8274816/54587059-3ed37d80-4a1f-11e9-9537-a1cde9baa2f7.png)

I enabled Hotreload via old school Toolbar icon click but the new yellow bar is not going away. Also it would be nice to only show it over an opend XAML file like LiveReload does.

**Comment by stanbav** [comment]
@MagicAndre1981 good idea, will fix it in future releases.

**Comment by MagicAndre1981** [comment]
@stanbav and ETA for a fix? I still have this yellow bar in 1.2.0 even if I'm connected and I would still prefer a smaller bar over an opend XAML file.
