### ISSUE TITLE
Error when tryin to connect to Android emulator

### ISSUE THREAD

**Issue by AlonRom** [AndreiMisiukevich/HotReload#35]
Hi,

I keep getting the following error when trying to connect to my emulator:

![Capture](https://user-images.githubusercontent.com/27087135/54142949-721b7880-4431-11e9-80bb-ab406e5fa2ef.PNG)

Do you know how can I fix this issue?

thanks.

**Comment by AndreiMisiukevich** [comment]
Hi
Have you checked yet?
https://github.com/AndreiMisiukevich/HotReload#android-emulator

**Comment by AlonRom** [comment]
where di I need to execute this command:
adb forward tcp:8000 tcp:8000 ?

**Comment by AndreiMisiukevich** [comment]
> @AndreiMisiukevich where do I need to execute this command:
> adb forward tcp:8000 tcp:8000 ?

In your terminal.
Firstly you need to install adb (if it doesn't exist)
https://stackoverflow.com/questions/31374085/installing-adb-on-macos

**Comment by AlonRom** [comment]
@AndreiMisiukevich  thanks for the reply, I'm on windows, when I run this command I'm getting the following:

![image](https://user-images.githubusercontent.com/27087135/54160063-3c898600-4457-11e9-80cb-87c09bfcc3cc.png)

**Comment by AlonRom** [comment]
Success! thanks @AndreiMisiukevich
