### ISSUE TITLE
Add Profiles/History feature to VS extension

### ISSUE THREAD

**Issue by AndreiMisiukevich** [AndreiMisiukevich/HotReload#38]
![image](https://user-images.githubusercontent.com/10124814/54358934-9619cc80-4672-11e9-89e8-1df0937e6097.png)

Add possibility to create multiple profiles for different devices (like history)

**Comment by MagicAndre1981** [comment]
it would be nice to make comments for the IP (device name, Phone XYZ) so that I can remember what IP is used by which device

**Comment by MagicAndre1981** [comment]
Implementing https://github.com/AndreiMisiukevich/HotReload/issues/43 would make this obsolete. I would prefer the automatic discovery option from the other issue.

**Comment by stanbav** [comment]
@AndreiMisiukevich I think we can close it and concentrate on https://github.com/AndreiMisiukevich/HotReload/issues/43.

**Comment by MagicAndre1981** [comment]
@stanbav I agree with this.
