### ISSUE TITLE
[Bug] VS Extension did not load correctly on v1.1.0

### ISSUE THREAD

**Issue by ChasakisD** [AndreiMisiukevich/HotReload#40]
After updating to version 1.1.0 the extensions does not load. Tried uninstall and reinstall but same.

#### The warning:
![image](https://user-images.githubusercontent.com/23040695/54480809-dffee000-4835-11e9-8c2f-20502194e095.png)

#### From ActivityLog.xml
![image](https://user-images.githubusercontent.com/23040695/54480825-163c5f80-4836-11e9-83f8-14317fa8a92a.png)

**Comment by stanbav** [comment]
Thanks for bug report @ChasakisD 
Please try to update to 1.1.1 version

**Comment by ChasakisD** [comment]
It does not throw the exception anymore, but the icon is not appearing.

![image](https://user-images.githubusercontent.com/23040695/54491373-c48fe580-48c6-11e9-855f-13f6209cadb2.png)

**Comment by stanbav** [comment]
@ChasakisD could you post/send a hierarchy of your solution ? Or you can mail me this solution if it's just a test project. 
Reverted some functionality that could cause this issue - please updated to 1.1.2

**Comment by ChasakisD** [comment]
It is very weird. When i open existing solutions the icon is not showing. When i created a new X.F. solution it is appearing.

**Comment by stanbav** [comment]
@ChasakisD could you try to install this beta build and check whether it shows Hot reload button on all projects ? 
[https://github.com/stanbav/HotReloadExtension-Beta/blob/master/Windows/Xamarin.Forms.HotReload.Extension.WinVS.vsix](url)

**Comment by ChasakisD** [comment]
@stanbav Beta version works fine on all of my current projects. :)

**Comment by stanbav** [comment]
Nice 😀

**Comment by AndreiMisiukevich** [comment]
Good job guys :)
