### ISSUE TITLE
Hotreload can't connect to local device/simulator [UWP]

### ISSUE THREAD

**Issue by MagicAndre1981** [AndreiMisiukevich/HotReload#41]
when I start the app in Windows 10 1709 and click on the connect icon in toolbar I get a message that connection failed. I tried the local IP of the development VM and 127.0.0.1, but both fail to connect to the running app.

If I debug the app on Remote Device I can connect fine.

**Comment by MagicAndre1981** [comment]
@stanbav 

the [Simulator](https://docs.microsoft.com/en-us/visualstudio/debugger/run-windows-store-apps-in-the-simulator?view=vs-2017) is doing a "remote connection" so logging in a 2nd user and displays this desktop in a Tablet looking UI Window where I can rotate the screen , test different resolutions to see if the app looks good. It would be really nice to get Hotreload working for this.

**Comment by stanbav** [comment]
@MagicAndre1981 will test it to see whether it's possible

**Comment by MagicAndre1981** [comment]
can you repro this issue?

**Comment by AndreiMisiukevich** [comment]
@MagicAndre1981 maybe you would like to debug this case ?
i think it's smt on reloader side, no?

I don't have Win PC :(

**Comment by MagicAndre1981** [comment]
download and run the provided VM in parallels/Vmware:

https://developer.microsoft.com/en-US/windows/downloads/virtual-machines

**Comment by MagicAndre1981** [comment]
how I can help to debug it? The extension and reloader need to add log details to debug/output window

**Comment by AndreiMisiukevich** [comment]
@MagicAndre1981 wait please. I hope @stanbav will contribute full code of extensions soon :)

**Comment by MagicAndre1981** [comment]
if you merge my PR I could step into the client code to see more.

**Comment by AndreiMisiukevich** [comment]
@MagicAndre1981 but what stops you to create local nuget ?

**Comment by MagicAndre1981** [comment]
I don't want to maintain my fork and merge your changes all the time

**Comment by stanbav** [comment]
@MagicAndre1981, @AndreiMisiukevich going to check in source code of the extension these week.

**Comment by MagicAndre1981** [comment]
@stanbav 

add some Eventsource debug code, this is easier.

    ```
using System.Diagnostics.Tracing;

public sealed class ProgramEventSource : EventSource
    {
        public static class Tasks
        {
            public const EventTask ApplicationInfo = (EventTask)1;
            public const EventTask ApplicationError = (EventTask)2;
        }

        public ProgramEventSource() : base(EventSourceSettings.EtwManifestEventFormat | EventSourceSettings.ThrowOnEventWriteErrors) { }

        public static ProgramEventSource Log = new ProgramEventSource();

        [Event(1, Opcode = EventOpcode.Info, Task = Tasks.ApplicationInfo, Message = "{0}")]
        public void ApplicationInfo(string message)
        {
            if (IsEnabled())
            {
                WriteEvent(1, message);
            }
        }

        [Event(2,  Opcode = EventOpcode.Info, Task = Tasks.ApplicationError, Message = "Application Falure: {0}")]
        public void ApplicationError(string exceptionMessage, string exceptionType)
        {
            if (IsEnabled())
            {
                WriteEvent(2, exceptionMessage, exceptionType);
            }
        }
    }
```

 Post it this way

```
catch (Exception e)
{
      ProgramEventSource.Log.ApplicationError(e.Message, e.GetType().FullName);
}

ProgramEventSource.Log.ApplicationInfo("my debug message at: " + new StackTrace(true).ToString() );
```

I can easily capture those messages with Perfview/WPR.exe and look what happens.

**Comment by AndreiMisiukevich** [comment]
@stanbav hope extensions will be available soon :)

**Comment by stanbav** [comment]
@MagicAndre1981 going to check in source code of the extension today or tomorrow,  so you can debug it yourself and contribute ;)

**Comment by AndreiMisiukevich** [comment]
@stanbav happy days :)

**Comment by MagicAndre1981** [comment]
ok, hopefully you use nuget packages for all VS SDK related files, so that I can build it without hassle.

**Comment by stanbav** [comment]
@MagicAndre1981 extension source code is here.:)

**Comment by MagicAndre1981** [comment]
@stanbav ok, I can compile it. But how can I now debug it?

**Comment by MagicAndre1981** [comment]
please add my small code and call it, this is easier than trying to understand your code.

Also look for the pending nuget updates and warnings that VS generates.

**Comment by stanbav** [comment]
@MagicAndre1981 okay, will try to debug it on UWP mysef at first. Let's see.

**Comment by MagicAndre1981** [comment]
When I debug the extension in the experimental instance, the UWP app never starts. I gave it up. Please add the better EventSource way to write Debug messages.

**Comment by stanbav** [comment]
@MagicAndre1981 
It's not possible to communicate with the Http listener in UWP app within the same machine. 
https://docs.microsoft.com/en-us/previous-versions/windows/apps/hh780593(v=win.10)#enable-loopback-for-network-access "Further, a Windows Runtime app can use an IP loopback only as the target address for a client network request."

But if you try to connect from another windows machine in your local network - it will work. For that you will also need to enable "Private Network (Client & Server)" capability in UWP package manifest. 

@AndreiMisiukevich  I think we can close this issue. what do you think ?

**Comment by MagicAndre1981** [comment]
I have that already set and allowed my app to use localhost loopback. this works fine and I my UWP app can communicate to the SignalR server on the same VM

**Comment by MagicAndre1981** [comment]
why is this closed? As I said it is activated!

**Comment by AndreiMisiukevich** [comment]
@MagicAndre1981
Well, our main point is: we are not keen to add some extra package references (such as SignalR or something else)

Have you got ideas how can we work around this limitation?

**Comment by MagicAndre1981** [comment]
I don't want to add extra packages, I only said that connecting from UWP to a HTTP service on same machine works if you tell this to the app (in my case I run a selfhosted (command line tool) SignalR server and connect fine to it)

![image](https://user-images.githubusercontent.com/8274816/55702926-64c5bf80-59d8-11e9-8ea0-ebf33579e225.png)

if you have Fiddler installed, run `%localappdata%\Programs\Fiddler\EnableLoopback.exe` and here also verify that looback is enabled.

**Comment by MagicAndre1981** [comment]
@stanbav

It is also documented in [recent docs](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/deploying-and-debugging-uwp-apps#debugging-options):

> **Allow local network loopback**
> 
> For security reasons, a UWP app that is installed in the standard manner is not allowed to make network calls to the device it is installed on. By default, **Visual Studio deployment creates an exemption from this rule for the deployed app. This exemption allows you to test communication procedures on a single machine.**

**Comment by stanbav** [comment]
@MagicAndre1981 if I understand you correctly - you are connecting from UWP to PC. In our case we need the other  way around - from PC to UWP.
Anyway we would like to have a sample from you when server is running in UWP application and connecting to it from PC :)
