### ISSUE TITLE
[BUG] ContentView in ContentPage

### ISSUE THREAD

**Issue by thiagoparabas** [AndreiMisiukevich/HotReload#42]
When you have a contentview (xmal in another file) inside a contentpage and save the contentview, the screen goes white, not updating.

On android and iOS.

**Comment by ChasakisD** [comment]
I can confirm that this issue is happening some times, specially when you manually layout the views from the xaml.cs

**Comment by AndreiMisiukevich** [comment]
Hey guys, could you please provide small sample with exact steps for reproducing it?

**Comment by AndreiMisiukevich** [comment]
Are you sure, that you don't make any mistake in xaml file? (Check application output)

**Comment by AndreiMisiukevich** [comment]
Need sample
cannot reproduce.
