### ISSUE TITLE
[Enhancement] Automatic Network Discovery

### ISSUE THREAD

**Issue by ChasakisD** [AndreiMisiukevich/HotReload#43]
It would be nice the client(mobile app) could send UDP Broadcast messages in a specified port(e.g. 8000) and the server(Visual Studio) could listen into this port. By doing that, you do not have to worry when the ip address is changed, and you do not need to check your mobile ip address. 

The mobile app could send a udp broadcast every 5-10 seconds. Visual studio will catch those and inside the HotReload Menu those addresses will be inside a list. Then, you can add an ip from that list to your device connections list.

**Comment by ChasakisD** [comment]
For the reloader part, i could work on sending udb broadcats until a connection is established.

**Comment by MagicAndre1981** [comment]
The idea is great, but **don't do polling**! 

The VS extension should send a UDP broadcast when you click on the Icon in the toolbar or the yellow bar, wait for a response of the apps in the local network that implement Hotreload. In the response the app should send the IP of the device via some device info (OS, name/model maybe Xamarin.Essentials can give all data) that the extension can display in the connect dialog. This must be done automatically by the hotreload component so that we don't have to include anything.

**Comment by ChasakisD** [comment]
@MagicAndre1981 I actually think that this is better option. UDP Broadcast must be sent from the Visual Studio. Open source the extension so we can contribute! :)

**Comment by stanbav** [comment]
@ChasakisD planning to open source it soon, just need to refactor a bit at first :)

**Comment by MagicAndre1981** [comment]
The remote debug dialog is a good way to do it:

![image](https://user-images.githubusercontent.com/8274816/54737650-57739d00-4bb1-11e9-8794-6eb4c06b4f9b.png)

it shows my Toshiba Tablet (with Windows Buildnumberand cpu archtiecture),  my Lumia 950 XL phone ( which I can't use with Xamarin.Forms any longer do to stuck at Build 15254 with no .net standard 2.0 support) and adds an option to add your own config entries.

**Comment by stanbav** [comment]
@ChasakisD extension code is here :)

**Comment by AndreiMisiukevich** [comment]
@stanbav check code in console app :) i think we can add autodiscovery feature

**Comment by AndreiMisiukevich** [comment]
delivered

**Comment by MagicAndre1981** [comment]
for me the detection works, but users are [confused about missing window](https://github.com/AndreiMisiukevich/HotReload/issues/72). Try to add a status message to extension after connect click that it tries to find devices where the app runs.

**Comment by MagicAndre1981** [comment]
or bring a window back like the remote debug dialog of VS where you see the automatically detected devices and manually add your own devices.
