### ISSUE TITLE
Extension: only show Toolbar when XF project is open

### ISSUE THREAD

**Issue by MagicAndre1981** [AndreiMisiukevich/HotReload#48]
When I start my VS2017 I'm often confused why there is an empty toolbar icon

![image](https://user-images.githubusercontent.com/8274816/55214317-9ed3dc00-51f6-11e9-93e2-562b4d1f25b0.png)

until I notice this is Hotreload Connect Icon. Display it only when a project is loaded that targets Xamarin.Forms

**Comment by AndreiMisiukevich** [comment]
Yes, I think it makes sense

**Comment by AndreiMisiukevich** [comment]
@stanbav what do you think?

**Comment by stanbav** [comment]
Yes, that's something that should be fixed.)

**Comment by stanbav** [comment]
Fixed in https://github.com/AndreiMisiukevich/HotReload/commit/d24ea31dc0c3751a2c13ff3dcdba82794893cd60. Will be included in next release (1.2.0).
