### ISSUE TITLE
Better Installation&Activation documentation needed

### ISSUE THREAD

**Issue by KCemK** [AndreiMisiukevich/HotReload#49]
Hi,
It may be a great tool., really promising.
However, after 2 hours of work, I could not run it.

Many points are not clear:

-Main logic ? What is for this IP setting ?
-Do I need install Nuget Package besides installing VS extension ? (It seems so).
-Should I add IReloadable interface to every page ?
-if so, what should I implement in OnLoaded()
-What happens in production version ? should I remove all those interfaces ? Or does your tool code goes with my code to the user ?
thanks.

**Comment by MagicAndre1981** [comment]
1. install the VS extension
2. install the nuget packages to shared code and all projects (Android, iOS, UWP)
3. add this to App constructor of shared project

```
#if DEBUG
            HotReloader.Current.Start(this);     
#endif
```
4. look for IP of your target device (phone, tablet)
5. compile and run the app
6. in VS connect dialog enter the IP of the device and click connect
7. navigate to the page you want to edit in your app, now open that page in VS and edit it. after changing it the app page gets updated.

**Comment by AndreiMisiukevich** [comment]
@MagicAndre1981 thanks)

**Comment by vincentcastagna** [comment]
You can add this to the documentation imo. I think a PR would be overkill for that . 

Get target device's IP easily : 

- Open adb command prompt
- Run command `adb shell `
- Run command `ip -f inet addr show wlan0`

**Comment by AndreiMisiukevich** [comment]
@vincentcastagna feel free to create PR)

**Comment by fileman** [comment]
@MagicAndre1981 have you tried with VS 2019 RC.4 ?

**Comment by KCemK** [comment]
Until now, I have tried Xamarin's own Live Player & Gorilla & XAML Live. and left the all tree during installation.
Mentioned steps are OK, but it is still not working.
Simply nothing is happening.
In fact, I can't understand its working logic. Will it work while the app running and allow to modify XAML ? 
If I can run it, promise, I will contribute the project with a good Quick Start documentation :)

**Comment by MagicAndre1981** [comment]
yes, you run the app on the target device and navigate to the page, click on connect button in VS and now modify the XAML in VS

**Comment by vincentcastagna** [comment]
@KCemK have you checked [this ](https://github.com/AndreiMisiukevich/HotReload#android-emulator)?

**Comment by AndreiMisiukevich** [comment]
@KCemK 

![image](https://user-images.githubusercontent.com/10124814/55682070-c46b8e80-5936-11e9-8dfa-bbae23b8b4e6.png)

![image](https://user-images.githubusercontent.com/10124814/55682073-d2b9aa80-5936-11e9-97ca-d327d6e4b304.png)

Your should start on the same port (default is 8000)

So, change it in code to 5555

![image](https://user-images.githubusercontent.com/10124814/55682100-29bf7f80-5937-11e9-875d-8990ce7cc372.png)


BTW, as i noticed HotReloader doesn't work with **Genymotion**
