### ISSUE TITLE
VS4Mac 2019 support

### ISSUE THREAD

**Issue by Clancey** [AndreiMisiukevich/HotReload#50]
VS4 mac 2019 uses Monodevelop.Core 8.0. This package depends on 7.8.3.

**Comment by AndreiMisiukevich** [comment]
http://addins.monodevelop.com/Project/Index/376

Use version 1.1.0

**Comment by AndreiMisiukevich** [comment]
@Clancey try to download it directly and install as local file.

@stanbav have you got any ideas, why it can be invisible?

**Comment by stanbav** [comment]
No ideas. :( I do see it in VS for Mac 2019

**Comment by AndreiMisiukevich** [comment]
@stanbav 

![image](https://user-images.githubusercontent.com/10124814/55624202-dec63080-57ad-11e9-94f8-1eed23a73976.png)


But i am on 7.8.x version. So, maybe it's ok

**Comment by AndreiMisiukevich** [comment]
@Clancey so, download please version 1.1.0 as file through the link above.
