### ISSUE TITLE
Exception when there is a resource defined in a listview template view (android)

### ISSUE THREAD

**Issue by InquisitorJax** [AndreiMisiukevich/HotReload#51]
### STR
- define list view with a data template that is in a separate ContentView file
- in the template view, define a resource in the ContentView.Resources
- change something in the template view xaml
- Exception is thrown when hot reload activates - something along the lines of "resource [resourcekey] has already been added"

### Work-around
- adding the resource to the container of the content view (like Grid.Resources) works fine.

**Comment by AndreiMisiukevich** [comment]
@InquisitorJax thanks a lot for you report :)

it would be nice to have small sample

**Comment by InquisitorJax** [comment]
I'll see if I can get to it this evening when I'm not on the clock :)

**Comment by InquisitorJax** [comment]
I think I may have found the issue - although I couldn't repro exactly.
I had a copy of the content view xaml commented our below the actual xaml (older version of the content view)
The commented code also had a resource with a key defined in the content view - I'm guessing hotreload doesn't detect that this is commented code, and attempts to add duplicate resource keys.
This is such an edge case, I'm not sure it warrants effort in fixing. Happy to close.
