### ISSUE TITLE
Support Design Time Data

### ISSUE THREAD

**Issue by ChaseFlorell** [AndreiMisiukevich/HotReload#53]
It would be great if this could support Design Time Data akin to what the previewer can do.

More info can be foud here.
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-previewer/design-time-data

**Comment by AndreiMisiukevich** [comment]
@ChaseFlorell hmm.. don't think, we can achieve it (since HotReload is not kind of previewer. It's real live reload. And you should test with real data (and it makes much more sense :])
