### ISSUE TITLE
Jetbrains Rider Plugin

### ISSUE THREAD

**Issue by ChaseFlorell** [AndreiMisiukevich/HotReload#54]
Consideration for implementing a Rider plugin for easier addition.

https://blog.jetbrains.com/dotnet/2017/02/07/rider-front-end-plugin-development/

**Comment by AndreiMisiukevich** [comment]
Hi, does not Mac plugin work for Rider ?

**Comment by AndreiMisiukevich** [comment]
Try to download it as file and install

Just interesting

**Comment by AndreiMisiukevich** [comment]
good point :)

**Comment by AndreiMisiukevich** [comment]
good point :)

**Comment by iBavtovich** [comment]
Hi, guys! I can help you with developing HotReload plugin for Rider :)

**Comment by AndreiMisiukevich** [comment]
@iBavtovich hi
Would be amazing )

**Comment by AndreiMisiukevich** [comment]
So, currently Rider lovers can use console app instead of extension (info is in Readme fill)

**Comment by AndreiMisiukevich** [comment]
will be released on the next week and announced on my twitter https://twitter.com/Andrik_Just4Fun
