### ISSUE TITLE
HotReload not reload if use ReSharper

### ISSUE THREAD

**Issue by scriptBoris** [AndreiMisiukevich/HotReload#55]
Hello! I found error when I try to reload the XAML page then Android app got white display.

I use ReSharper from JetBrains, my XAML code started:
```
...
xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" mc:Ignorable="d"
d:DataContext="{d:DesignInstance vm:MasterViewModel}"
...
```
This above code can link View with ViewModel for IntelliSense. And that thing is "must have"!
How use ReSharper (d, m, DataContext) and HotReload?
Regards, your user.

**Comment by AndreiMisiukevich** [comment]
@scriptBoris could you please create small sample?
it would be awesome.

Thanks

**Comment by scriptBoris** [comment]
I can create youtube video. 5 min...

**Comment by AndreiMisiukevich** [comment]
@scriptBoris sample would be better :)
Just small project which demonstrates this issue

**Comment by scriptBoris** [comment]
video: https://drive.google.com/open?id=1qZaBxdrb8VxVmj8cRQKWWHykmAccYdth
Youtube is slowpoke.

**Comment by AndreiMisiukevich** [comment]
@scriptBoris that is why i highly need sample :)

I saw 2 bugs

1) Mater pages isn't reloaded
2) Issue which was described by you (btw, you can check application output, i wonder if HotReloader wrote smth there)


So, will you be able to create small sample project?

**Comment by ChasakisD** [comment]
The problem is with the d:DataContext. I am having the same issue. Resharper cannot recognize the viewmodel using the x:DataType so you have to use the d: DataContext. If you remove this live it will reload perfectly

**Comment by scriptBoris** [comment]
> The problem is with the d:DataContext. I am having the same issue. Resharper cannot recognize the viewmodel using the x:DataType so you have to use the d: DataContext. If you remove this live it will reload perfectly

I dont use x:DataType.

**Comment by scriptBoris** [comment]
> So, will you be able to create small sample project?
Eah, just wait some time. I will create simple project Xamarin Forms with ReSharper(he allow use d, mc, DataContext for IntelliSense) and HotReload.

**Comment by AndreiMisiukevich** [comment]
@scriptBoris btw, could you please fill separate bug with master detail page?

**Comment by AndreiMisiukevich** [comment]
@scriptBoris hey :) could you pls provide sample ?:)

**Comment by AndreiMisiukevich** [comment]
ping

**Comment by AndreiMisiukevich** [comment]
seems
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             mc:Ignorable="d"

don't cause error

**Comment by AndreiMisiukevich** [comment]
will be available in the next release (1-2 weeks)
