### ISSUE TITLE
HotReload not realod ListView items

### ISSUE THREAD

**Issue by danielccunha** [AndreiMisiukevich/HotReload#56]
Hello, I found an error using HotReload that I'm assume is very annoying and many will experience it.

The problem is basically that **ListView** doesn't reload its items when a change is made in the page. When I first load the page, the items are load, but when I change a single property, the page reload and I lost the items.

Hope you can solve it. Excellent plugin by the way, I'm loving it.

**Comment by AndreiMisiukevich** [comment]
@danielccunha Hi :) thanks for feedback
could you please prepare small sample for reproducing this issue ?
because i have such sample and it works fine.

Thx

**Comment by danielccunha** [comment]
Here's a gif of the issue, but I think I've already discovered the problem. When I was creating this layout I was working with the code-behind, without ViewModels, and for initializing the ListView I was doing it in the constructor. But when I changed it to the ViewModel the bug didn't happen again.

![bug](https://user-images.githubusercontent.com/32555455/56748987-3a555f80-6757-11e9-85fa-35ae37bb0752.gif)

**Comment by AndreiMisiukevich** [comment]
Yeah, in those cases when you don't work with bindings and want to have live-reloading, you should go ahead with IReloadable interface. More info  https://github.com/AndreiMisiukevich/HotReload#run-your-app-and-start-developing-with-hotreload
