### ISSUE TITLE
XF 4 support ?

### ISSUE THREAD

**Issue by scharada** [AndreiMisiukevich/HotReload#60]
i see it supports XF 3.6  only, any plan for XF 4 ?
nuget package does not even install in the netstandard project (it installs but disappears ) using VS 2019.

when added manually to the project, it stays but does not work.

**Comment by AndreiMisiukevich** [comment]
Hi
Hmmm, interesting

Small sample please

**Comment by AndreiMisiukevich** [comment]
Tested with XF 4 project
Seems to be working (except Shell)
So could you please provide me small sample
