### ISSUE TITLE
not able to style dynamic created content

### ISSUE THREAD

**Issue by SagarPanwala** [AndreiMisiukevich/HotReload#61]
I know there is a IReloadable interface, I used it or may be wrongly, but I have 1 code which creates view dynamically inside ViewAppear. After changing style of otherview inside same page, my dynamic view disappearing.

**Comment by AndreiMisiukevich** [comment]
Yes, of course.
You need to call that code in OnLoaded method of IReloadable interface.

HotReload doesn't update code. Xaml and css only

**Comment by SagarPanwala** [comment]
Suppose,

I created some controls on button click, then try to change other controls
with hot reload, my dynamic control will be gone, in this case.

**Comment by AndreiMisiukevich** [comment]
@SagarPanwala well, you can restore needed controls OnLoaded.

Create needed controls by yourself )

You should keep in mind, that HotReload redraws whole xaml element
