### ISSUE TITLE
Not working with grid

### ISSUE THREAD

**Issue by dely17** [AndreiMisiukevich/HotReload#63]
hey the hotreloaded ain't corresponding with my grid layout ,when i press save everything turns white except does that are outside the grid

**Comment by AndreiMisiukevich** [comment]
Show me your xaml
I think you make mistake in xaml

**Comment by dely17** [comment]
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
              NavigationPage.HasNavigationBar="False"
             x:Class="Emarald.Menu">
    <AbsoluteLayout  >
        <Image x:Name="BackGround" ScaleX="2"  AbsoluteLayout.LayoutBounds="0,0,1,1" AbsoluteLayout.LayoutFlags="All"/>

        <Image x:Name="TopBanner"  AbsoluteLayout.LayoutBounds="0.5,0.01,1,0.085" AbsoluteLayout.LayoutFlags="All"/>


        <Image x:Name="FilmTape" ScaleY="0.8"  AbsoluteLayout.LayoutBounds="0.5,0.095,1,0.07" AbsoluteLayout.LayoutFlags="All"/>
        <Label Text="May" AbsoluteLayout.LayoutBounds="0.5,0.158 " HorizontalOptions="Center" AbsoluteLayout.LayoutFlags="PositionProportional" TextColor="White" FontFamily="Montserrat-ExtraBold.otf#Montserrat"  FontSize="25"/>

        <Grid  HorizontalOptions="Fill" AbsoluteLayout.LayoutBounds="0.5,0.373,1,0.35" AbsoluteLayout.LayoutFlags="All" ColumnSpacing="0">
            <Image x:Name="Movie1" Grid.Column="0" />

            <Image x:Name="Movie2"  Grid.Column="1" />
            <Image x:Name="Movie3"  Grid.Column="2"/>

        </Grid >
        <Grid Grid.ColumnSpan="3"   ColumnSpacing="0" RowSpacing="0" AbsoluteLayout.LayoutBounds="0.5,0.59,1,0.09" AbsoluteLayout.LayoutFlags="All"  >
            <Image x:Name="Corner1"  Grid.Column="2" Grid.RowSpan="3" ScaleY="1.5"  />
            <Image x:Name="Corner2" Grid.RowSpan="3" Grid.Column="1" ScaleY="1.5"/>
            <Image x:Name="Corner3"  Grid.Column="0" Grid.RowSpan="3" ScaleY="1.5" />


            <Image x:Name="Cornerthree" Grid.Row="2" Grid.Column="2" ScaleX="0.8" ScaleY="0.8" AnchorY="0.5" HorizontalOptions="Center" HeightRequest="-1" InputTransparent="False" IsOpaque="False" Grid.RowSpan="1" />
            <Image  x:Name="Cornertwo" Grid.Row="2" Grid.Column="1" ScaleX="0.8" ScaleY="0.8" AnchorY="0.5"  />
            <Image   x:Name="Corner" Grid.Row="2" Grid.Column="0" ScaleX="0.8" ScaleY="0.8" HorizontalOptions="Center" AnchorY="0.5" />
            <Button Opacity="0" x:Name="buyticket" Clicked="Button_Clicked"  BackgroundColor="Green" Grid.Row="2"  />

            <Button Opacity="0" x:Name="buyticket2" Clicked="Buyticket2_Clicked" BackgroundColor="Green" Grid.Row="2" Grid.Column="1"   />


            <Button Opacity="0" x:Name="buyticket3" Clicked="Buyticket3_Clicked" BackgroundColor="Green"  Grid.Row="2" Grid.Column="2" HorizontalOptions="Center"   />
            
            <BoxView Grid.ColumnSpan="3" BackgroundColor="#188041" ScaleY="1.2" ScaleX="3" Margin="0, 0, 0, 0" Grid.Row="0" ></BoxView>
            <Label Text="Thursday" HorizontalOptions="Center" FontSize="12" FontFamily="Montserrat-SemiBold.otf#Montserrat" TextColor="White" Grid.Row="0" Grid.Column="0"/>
            <Label Text="Friday"   HorizontalOptions="Center" FontSize="12" FontFamily="Montserrat-SemiBold.otf#Montserrat" TextColor="White" Grid.Row="0" Grid.Column="1"/>
            <Label Text="Saturday" HorizontalOptions="Center" FontSize="12" FontFamily="Montserrat-SemiBold.otf#Montserrat" TextColor="White" Grid.Row="0" Grid.Column="2"/>
            <Label Text="(Action/Sci-fi)"  HorizontalOptions="Center" FontSize="9" FontFamily="Montserrat-SemiBold.otf#Montserrat" TextColor="White" Grid.Row="1" Grid.Column="0"/>
            <Label Text="(Thriller/Mystery)"  HorizontalOptions="Center" FontSize="9" FontFamily="Montserrat-SemiBold.otf#Montserrat"  TextColor="White" Grid.Row="1" Grid.Column="1"/>
            <Label Text="(Fantasy/Mystery)"  HorizontalOptions="Center" FontSize="9" FontFamily="Montserrat-SemiBold.otf#Montserrat"  TextColor="White" Grid.Row="1" Grid.Column="2"/>


        </Grid>
        

        <Grid  AbsoluteLayout.LayoutBounds="0.5,0.225,1,0.05" AbsoluteLayout.LayoutFlags="All"   >
            
            <BoxView  Grid.ColumnSpan="3"  ScaleX="3" BackgroundColor="#0b9f46"></BoxView>
            <Image x:Name="HD" Grid.Column="0" ScaleX="0.6" ScaleY="0.6" HorizontalOptions="End"  />
            <Label Text="WEEK 1" HorizontalTextAlignment="Center" VerticalOptions="Center" TextColor="White" FontSize="17.9" FontFamily="Montserrat-Bold.otf#Montserrat"  Grid.Column="1" AnchorY="0.9" />
            <Image x:Name="HD2" Grid.Column="2" ScaleX="0.6" ScaleY="0.6" HorizontalOptions="Start"  />
        </Grid>
        <Grid RowSpacing="0" ColumnSpacing="0" AbsoluteLayout.LayoutBounds="0,0.92,1,0.177" HorizontalOptions="Center"  AbsoluteLayout.LayoutFlags="All" >

            
            <BoxView  Grid.Row="0"  Grid.ColumnSpan="5"  ScaleX="3" BackgroundColor="#148a43" Opacity="80"></BoxView>
            <Image  x:Name="Popcorn" Grid.Row="0" ScaleX="0.75" ScaleY="0.75" Grid.Column="1"/>
            <Label Grid.Column="2" Text="WEEK 2"  HorizontalOptions="Center" VerticalOptions="Center" TextColor="White" FontFamily="Montserrat-Bold.otf#Montserrat" FontSize="17.9"/>
            <Image  x:Name="Popcorn2" Grid.Row="0" ScaleX="0.75" ScaleY="0.75" Grid.Column="3"/>

            
            <BoxView  Grid.Row="1"  Grid.ColumnSpan="5"  ScaleX="3" BackgroundColor="#188041" Opacity="70"></BoxView>
            <Image  x:Name="Ticket" Grid.Column="1" Grid.Row="1" ScaleX="0.75" ScaleY="0.75"/>
            <Label Grid.Column="2" Grid.Row="1" Text="WEEK 3" HorizontalOptions="Center" VerticalOptions="Center" TextColor="White" FontFamily="Montserrat-Bold.otf#Montserrat" FontSize="17.9"/>
            <Image  x:Name="Ticket2" Grid.Column="3" Grid.Row="1" ScaleX="0.75" ScaleY="0.75"/>

            
            <BoxView  Grid.Row="2"  Grid.ColumnSpan="5"  ScaleX="3" ScaleY="1.02" BackgroundColor="#206b3e"></BoxView>
            <Image  x:Name="Film" Grid.Column="1" ScaleX="0.75" ScaleY="0.75" Grid.Row="2"/>
            <Label Grid.Column="2" Grid.Row="2" Text="WEEK 4" HorizontalOptions="Center" VerticalOptions="Center" TextColor="White" FontFamily="Montserrat-Bold.otf#Montserrat" FontSize="17.9"/>
            <Image x:Name="Film2"  Grid.Column="3" ScaleX="0.75" ScaleY="0.75" Grid.Row="2"/>

        </Grid>

        <Label BackgroundColor="#333333" HorizontalOptions="FillAndExpand" HorizontalTextAlignment="Center"   Text="JUNE"  TextColor="Gray" FontSize="25"  FontFamily="Montserrat-ExtraBold.otf#Montserrat" AbsoluteLayout.LayoutBounds="0,1.036,1,0.1"  AbsoluteLayout.LayoutFlags="All"/>
        <ImageButton x:Name="options" AbsoluteLayout.LayoutBounds="0.03,0.01,0.1,0.09" AbsoluteLayout.LayoutFlags="All" ScaleX="0.99" WidthRequest="50" BackgroundColor="Transparent"/>
        <Label HorizontalOptions="Center"  Text="" x:Name="TicketBought" TextColor="Gray" FontSize="25" AbsoluteLayout.LayoutBounds="0,0.75,1,0.1"  AbsoluteLayout.LayoutFlags="All"/>

    </AbsoluteLayout>

</ContentPage>

**Comment by dely17** [comment]
[Eme.txt](https://github.com/AndreiMisiukevich/HotReload/files/3189942/Eme.txt)

**Comment by AndreiMisiukevich** [comment]
@dely17 are you able to create small sample page with this issue ?

**Comment by AndreiMisiukevich** [comment]
Cannot reproduce

![May-17-2019 13-44-02-min](https://user-images.githubusercontent.com/10124814/57923181-3aee9b00-78aa-11e9-8220-933b59fc48dc.gif)

Make sure, that you write your xaml without errors (Check application output after reloading. HotReload says, if something is wrong)

**Comment by AndreiMisiukevich** [comment]
So, make sure you don't make mistakes. Or provide sample and steps for replicating
