### ISSUE TITLE
CSS Stylesheet doesn't automatically reload when included in App.xaml

### ISSUE THREAD

**Issue by DanielAHill** [AndreiMisiukevich/HotReload#64]
Using the sample app, if we move the StyleSheet reference from the page*.xaml files into the App.xaml file, changes to the CSS do are not reloaded.

To replicate, on a Windows Android Simulator, I loaded the sample app, navigated to Thanos, then changed the .TeamLabel color and saved. Notice the color does not change.

If I hit the back button. Then tap on Thanos again, the color change is now visible.

----------------
Remove line from Pages xaml files:
```xaml
<StyleSheet Source="../Assets/styles.css" />
```
------
App.xaml file:
```xaml
<?xml version="1.0" encoding="utf-8"?>
<Application xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" x:Class="Xamarin.Forms.HotReload.Sample.App">
    <Application.Resources>
        <StyleSheet Source="Assets/styles.css" />
        <ResourceDictionary>
            <Color x:Key="CellTitleColor">White</Color>
        </ResourceDictionary>
    </Application.Resources>
</Application>
```

**Comment by ionixjunior** [comment]
This problem occurs with any resources located in App.xaml.

I added a new color and tried referencing it in the page and the problem occurs.

![hotreload_issue](https://user-images.githubusercontent.com/519642/58443199-db249b00-80c6-11e9-994b-93d21ae3298e.gif)

**Comment by AndreiMisiukevich** [comment]
@ionixjunior thank you for GIF

I will check

**Comment by AndreiMisiukevich** [comment]
Hey guys, I found the reason, I think

It will be fixed and delivered soon (I hope on this weekend)

**Comment by AndreiMisiukevich** [comment]
v.1.3.0

**Comment by ionixjunior** [comment]
Works perfectly! Thank you!
