### ISSUE TITLE
Small usability improvement: When entering an ip address, automatically select the entire contents of the current text box

### ISSUE THREAD

**Issue by JohnHMP** [AndreiMisiukevich/HotReload#65]

**Comment by AndreiMisiukevich** [comment]
Hi, in very short time you won't need to enter ip at all :)

https://github.com/AndreiMisiukevich/HotReload/issues/43

**Comment by JohnHMP** [comment]
> Hi, in very short time you won't need to enter ip at all :)
> 
> #43

I realised that after reading the other issues! :)
How long do you think?

**Comment by AndreiMisiukevich** [comment]
@JohnHMP we are planning release on this week. Maybe next
