### ISSUE TITLE
Multiple VS instances

### ISSUE THREAD

**Issue by MarMarIV** [AndreiMisiukevich/HotReload#70]
Hi, after update with automatic IP detection, i have a problem at solution loading and multiple Visual Studio running instances:

SetSite failed for package [HotReloadPackage]Source: 'System'; Description: Only one usage of each socket address (protocol/network address/port) is normally permitted.

And when i run only one instance, it doesn't working too. Version 1.2.8 is working

VS: 2019 (16.1.2)
NuGet: 1.3.0

**Comment by AndreiMisiukevich** [comment]
@stanbav need to find solution for this.

**Comment by AndreiMisiukevich** [comment]
Works fine with one VS instance on mac

**Comment by AndreiMisiukevich** [comment]
@MarMarIV can you confirm that it doesn't work on windows with one instance of VS ?

Make sure you:
Run IDE, opened project, ENABLED extension and ONLY after that run simulator

**Comment by AndreiMisiukevich** [comment]
@MarMarIV next release it won't be necessary to start extension BEFORE simulator/device.

**Comment by stanbav** [comment]
@MarMarIV please check 1.3.2 version of extension. Issue related to busy port should be gone. And you can now work with multiple instances of VS
