### ISSUE TITLE
The "connection window" does not open on clicking the lightening icon in visual studio

### ISSUE THREAD

**Issue by uksreejith** [AndreiMisiukevich/HotReload#71]

**Comment by AndreiMisiukevich** [comment]
@uksreejith that's our new feature.

Does reloader work?

**Comment by AndreiMisiukevich** [comment]
1) Open solution
2) Start extension by clicking lightening icon (it should become green)
3) Run your app with HotReload

Does it work?

**Comment by uksreejith** [comment]
Oh.. Is it so? The extension got updated automatically without my knowledge. And the extension stopped doing its thing
How exactly is it supposed to work now? The VS extension will automatically detect the current running instance?
Updates to the XAML file are not visible on my emulator.

**Comment by AndreiMisiukevich** [comment]
@uksreejith emulator ? Did you forward ports like readme file tells ?

**Comment by uksreejith** [comment]
Yes. I am using Memu Play. I have forwarded the ports as per the read me. Everything was working fine till the extension got updated to version 1.3. This is how I setup my emulator:

1) adb kill-server
2) adb start-server
3) adb connect 127.0.0.1:21503
4) adb forward tcp:8000 tcp:8000

**Comment by AndreiMisiukevich** [comment]
Does reloader work with real device ?

**Comment by AndreiMisiukevich** [comment]
1) make lightening icon green
2) start app on real device

**Comment by AndreiMisiukevich** [comment]
Why do you connect to 127.0.0.1:21503
But forward 8000 ports ??

**Comment by jbravobr** [comment]
Here the windows didn't open and Hot Reload don't work but it's shows ok in the Application Output
### AVAILABLE DEVICE's IP: Http://192.168.200.2:8000 ###
### AVAILABLE DEVICE's IP: Http://192.168.232.2:8000 ###
### HOTRELOAD STARTED ###

And I found this 
#### HOTRELOAD COULD NOT FIND CellRenderer.RealCellProperty

Using Last version of VS4Mac and Xamarin Forms 4.1-pre

**Comment by AndreiMisiukevich** [comment]
window shouldn't be opened anymore

**Comment by AndreiMisiukevich** [comment]
@jbravobr @uksreejith 
try latest version of nuget (1.3.1) and extension (1.3.2)

**Comment by AndreiMisiukevich** [comment]
check readme again pls

**Comment by uksreejith** [comment]
> 
> 
>     1. make lightening icon green
> 
>     2. start app on real device

Yes. It is working fine on the device. But when not on the emulator.

**Comment by AndreiMisiukevich** [comment]
@uksreejith thanks, we will try to solve this issue

**Comment by AndreiMisiukevich** [comment]
@uksreejith it's opened as separate one

**Comment by uksreejith** [comment]
> 
> 
> Why do you connect to 127.0.0.1:21503
> But forward 8000 ports ??
"Why do you connect to 127.0.0.1:21503"?
That seems to be the way for ADB to connect to Memu Play. Please check https://stackoverflow.com/questions/38477795/how-to-use-adb-with-emulator-like-memu-bluestacks-nox-app-player

I have the following settings in the emulator's .meme file:

`<NAT>
            <Forwarding name="ADB" proto="1" hostip="127.0.0.1" hostport="21503" guestip="10.0.2.15" guestport="5555"/>
            <Forwarding name="MVD" proto="1" hostip="127.0.0.1" hostport="21501" guestip="10.0.2.15" guestport="21501"/>
          </NAT>`

"But forward 8000 ports ??"
That was as per your documentation for the previous versions. Which port exactly do I forward now then?

**Comment by uksreejith** [comment]
> 
> 
> @uksreejith it's opened as separate one

Cool.

**Comment by AndreiMisiukevich** [comment]
@uksreejith https://github.com/AndreiMisiukevich/HotReload/issues/73

**Comment by jbravobr** [comment]
@AndreiMisiukevich I've updated the extension and try to use with a phone and it didn't work. Look into Application output I founded this : ### HOTRELOAD AUTODISCOVERY ERROR ###
