### ISSUE TITLE
ver 1.3.1 doesn't show window with IP of connected iOS simulator, devices

### ISSUE THREAD

**Issue by IoTFier** [AndreiMisiukevich/HotReload#72]
Hi @AndreiMisiukevich , thank you for keeping this hot reload package updated.
It really means a lot. 

My env . VS 16.1.3 | Win 10 64 | iOS simulator Mac - Mac OS 10.14.5 | Xamarin Forms 4.1 pre1
 
I just updated to the new version 1.3.1 , but now I see the window showing my VS port # , but doesn't show IP addresses of my connected iOS simulator and device.

How do I get to that?

As a result, my XAML updates are not reflected.

Thank you

**Comment by MagicAndre1981** [comment]
Update [VS Extension](https://github.com/AndreiMisiukevich/HotReload/issues/71#issuecomment-501070347)

**Comment by scriptBoris** [comment]
Some problem occurred
![image](https://user-images.githubusercontent.com/29772096/59326778-33d87280-8d1a-11e9-9c7c-eaf761a726d1.png)

**Comment by scriptBoris** [comment]
HotReload Nuget - 1.3.1
HotReload Extension - 1.3.2
Not work

**Comment by MagicAndre1981** [comment]
the new version [tries to automatically find the target](https://github.com/AndreiMisiukevich/HotReload/issues/43) and **no longer shows an UI**. For me it works and it detects my UWP part of XF app running on Tablet with remote debug.

**Comment by AndreiMisiukevich** [comment]
> Some problem occurred
> ![image](https://user-images.githubusercontent.com/29772096/59326778-33d87280-8d1a-11e9-9c7c-eaf761a726d1.png)

it isn't problem
HotReload tells you that it is running on port 15000
so, just call

```HotReloader.Current.Start(this);```

**Comment by AndreiMisiukevich** [comment]
so, there is an issue with android emulator. It's opened as separate one.

As for IP entering. We refused this step

**Comment by IoTFier** [comment]
@AndreiMisiukevich, I don't see version 1.3.2 available in the VS marketplace or in the nuget package manager when I tried to update. Please don't close this issue until we get to agree on a working soln.

I am still not able to use it, even after calling the constructor version that takes the port number of my VS. Besides, it was a good feature to know IPs of our iOS simulator, Android and emulator. I would suggest to keep it - at least for read only purposes to validate that the extension is really communicating with our devices / simulator / emulator... at this point I have no clue.

Thanks

**Comment by epomeranz** [comment]
> so, there is an issue with android emulator. It's opened as separate one.
> 
> As for IP entering. We refused this step

Hi Andrei,

Thanks for the awesome extension!

For me it does not work on a PHYSICAL DEVICE since upgrading to the version
My Setup: Pixel 3, VS 2019, windows, nuget 1.3.1, extension 1.3.2

**Comment by AndreiMisiukevich** [comment]
@epomeranz your devices and your PC with extension should use the same local network (WI-FI for example)

**Comment by AndreiMisiukevich** [comment]
> For me it works and it detects my UWP part of XF app running on Tablet with remote debug.

Does HotReload work on UWP ??

**Comment by MagicAndre1981** [comment]
for me it worked fine for UWP. Hotreload detected the tablet (remote debug), connected fine and I was able to modify a XAML file and I saw the updated page on the tablet
