### ISSUE TITLE
Extension 1.3.2 - not worked on Android Emulator

### ISSUE THREAD

**Issue by scriptBoris** [AndreiMisiukevich/HotReload#73]
HotReload nuget - 1.3.1
HotReload extension - 1.3.2
Android emulator - OS 9.0

Im use standard code init:
HotReloader.Current.Start(this);

1) launch emulator;

2) use adb comand:
adb forward tcp:8000 tcp:8000

3) run xamarin debug (F5)

4) In VS2019 change current view XAML

5) Press Alt + S

6) ...

7) Not PROFIT. Hot reload not reload

**Comment by MagicAndre1981** [comment]
don't post same issue several times. You already [comment here](https://github.com/AndreiMisiukevich/HotReload/issues/72) that it doesn't work

**Comment by AndreiMisiukevich** [comment]
@stanbav could you please validate this case?

**Comment by AndreiMisiukevich** [comment]
I think it's bug

**Comment by scriptBoris** [comment]
I can give you more information, but I don't know what

**Comment by AndreiMisiukevich** [comment]
@scriptBoris you tested on android emulator, didn't you?

**Comment by scriptBoris** [comment]
@AndreiMisiukevich, yeah, android emulator

**Comment by AndreiMisiukevich** [comment]
@scriptBoris this is a bug. Need to find the reason.

**Comment by uksreejith** [comment]
@AndreiMisiukevich In the mean time is it possible to download the older version of the vsix file from somewhere?

**Comment by uksreejith** [comment]
> 
> 
> @AndreiMisiukevich In the mean time is it possible to download the older version of the vsix file from somewhere? Unlike Nuget I guess you can't download an older version from visual studio market place.

**Comment by AndreiMisiukevich** [comment]
@uksreejith unfortunately not. But probably we will create archives and put them on github.
Sorry

**Comment by scriptBoris** [comment]
@AndreiMisiukevich I think downgrade self extension & nuget package. Need link for download backup

**Comment by AndreiMisiukevich** [comment]
@scriptBoris there is no such possibility on these stupid stores ))
nuget - yes
extension - no

**Comment by scriptBoris** [comment]
@AndreiMisiukevich from my HDD.
HotReload Extension 1.2:
https://drive.google.com/file/d/1fBacG2enN8e0lOU_aA-O392_RWGz7ps7/view?usp=sharing

IMPORTANT
**Disable** autoupdate vs extension!

**Comment by AndreiMisiukevich** [comment]
@scriptBoris why is it strange ? )

**Comment by AndreiMisiukevich** [comment]
nuget package is backward compatible with all version of extensions

**Comment by AndreiMisiukevich** [comment]
btw, i recommend to stay on nuget version 1.3.1

**Comment by scriptBoris** [comment]
@AndreiMisiukevich yeah, im use newest nuget package - no problem.

**Comment by move3a** [comment]
> @AndreiMisiukevich from my HDD.
> HotReload Extension 1.2:
> https://drive.google.com/file/d/1fBacG2enN8e0lOU_aA-O392_RWGz7ps7/view?usp=sharing
> 
> IMPORTANT
> **Disable** autoupdate vs extension!
> 
> P.S. Im install extension v1.2 and HotReload is reload XAML code. Strange things, but worked...

Hi, some old extension for VS for mac? Thanks

**Comment by scriptBoris** [comment]
@move3a oh sorry, i dont have hardware with MacOS

**Comment by AndreiMisiukevich** [comment]
Hey guys, i'm going to resolve this issue today

**Comment by Altevir** [comment]
Hi!

The same happens when the Device is used, if the port is 15001 the changes are not reflected, but with port 15000, everything works.

I'm using
HotReload Nuget - 1.3.1
HotReload Extension - 1.3.2
Device Motorola G6 - Android 9.0

**Comment by AndreiMisiukevich** [comment]
fix will be delivered a little bit later and will require *NUGET* package update

**Comment by winnertech** [comment]
@AndreiMisiukevich 
HotReloader.Current.Start() is Deprected?

**Comment by AndreiMisiukevich** [comment]
> @AndreiMisiukevich
> HotReloader.Current.Start() is Deprected?

yes, thank you for good question. Yes since now you should use ```Run```

**Comment by AndreiMisiukevich** [comment]
1.4.6 is already delivered and should fix this issue.

Don't forget abou adb forward :)

**Comment by uksreejith** [comment]
@AndreiMisiukevich The latest version of nuget(1.4.6) is working fine on emulator also. Thanks for the quick fixes and this awesome project. Keep up the good work!

**Comment by AndreiMisiukevich** [comment]
@uksreejith thank you :) the best way to give thanks - repost message about **HotReload** to broadcast info to as many people as we can :) https://twitter.com/Andrik_Just4Fun

**Comment by Altevir** [comment]
@AndreiMisiukevich 
now with this new version (1.4.6) everything works perfectly! Thanks for the quick fix and for this amazing tool!

**Comment by move3a** [comment]
@AndreiMisiukevich Excelent, works fine vs for mac.
¡¡Good Job!!

**Comment by AndreiMisiukevich** [comment]
Great guys )
