### ISSUE TITLE
Provide an option to auto forward tcp port for Android emulators

### ISSUE THREAD

**Issue by akamud** [AndreiMisiukevich/HotReload#75]
I usually use HotReload simultaneously on Android emulator and iOS simulator, the new auto discover feature is great and allows for a scenario where I can just set a random port to avoid collision when opening multiple emulators/apps.

Unfortunately, for Android emulators, I need to know the port so I can forward it through `adb`, as mentioned in the README.

My proposal: pass a `-auto-forward` flag so the Observer can automatically call `adb` to forward the port. I did this for my project and it is working, so if you think it makes sense, I can just open a new PR. The code looks something like this:

Inside the `UdpReceived`:

```csharp
if (!_addresses.Contains(address))
{
    _addresses.Add(address);

    var port = address.Split(':')?[2];
    Process.Start("adb", $"forward tcp:{port} tcp:{port}");
}
```

**Comment by AndreiMisiukevich** [comment]
Hey)
Will it work both for windows and mac?

Btw, we should add the same behavior to extensions as well. Because reloader is just console app

**Comment by akamud** [comment]
I just tested this on my Mac, I'll find a Windows to test it, but I believe it will as long as the `adb` is in the `PATH`.

**Comment by AndreiMisiukevich** [comment]
i think this update makes sense :)

**Comment by akamud** [comment]
I'll open a PR with this improvement.

**Comment by MagicAndre1981** [comment]
on my system, adb is not added to PATH by default. So add this note to readme, that users need to add adb to PATH.

**Comment by AndreiMisiukevich** [comment]
> on my system, adb (located in C:\Program Files (x86)\Android\android-sdk\platform-tools) is not added to PATH by default. So add this note to readme, that users need to add adb to PATH.

make PR please with this useful info)

**Comment by AndreiMisiukevich** [comment]
@MagicAndre1981 i will do it myself. no worries
