### ISSUE TITLE
VSMac 2019 extension port changed automatically to 15002 ,Hot reload won't work

### ISSUE THREAD

**Issue by prasadsunny1** [AndreiMisiukevich/HotReload#77]
VsMac 2019 with extension.
Project has latest version of NuGet package installed.

I don't know when but IDE extension's port changed from 15000 to 15002 and after that it is not hot reloading in iPhone simulator or android device.

It used to work normally before.

Tried to:
Add a parameter extension = 15002 in the initialization line.But no luck.
`HotReloader.Current.Start(this,extensionPort:15002);`
Removed NuGet and extension and reinstalled them, No luck

Is anyone else facing this isssue.

**Comment by AndreiMisiukevich** [comment]
First of all please use Run method instead of Start

**Comment by AndreiMisiukevich** [comment]
Hm, weird
What extension version do you use ? Are you sure it's latest one ?

**Comment by prasadsunny1** [comment]
Yes latest plugin for project and IDE

**Comment by AndreiMisiukevich** [comment]
@prasadsunny1 tell me versions please?
Can you try restart laptop

**Comment by AndreiMisiukevich** [comment]
##### Try to disable Firewall
![image](https://user-images.githubusercontent.com/10124814/59552526-dbf77100-8f90-11e9-9026-6bade3b406ea.png)


##### Try to change device port to other value e.g. "DeviceUrlPort = 4568"
And if **EXTENSION SHOWS 15002 port**, setup HotReload on your simulator with:

```csharp
HotReloader.Current.Run(this, new HotReloader.Configuration
{
    DeviceUrlPort = 4568,
    ExtensionAutoDiscoveryPort = 15002
});
```

**Comment by renatojunior2009** [comment]
I am facing the same problem only in VS 2017 for Windows, after updating the package and the extension HotReload no longer works

**Comment by renatojunior2009** [comment]
I am facing the same problem only in VS 2017 for Windows, after updating the package and the extension HotReload no longer works

**Comment by renatojunior2009** [comment]
I am facing the same problem only in VS 2017 for Windows, after updating the package and the extension HotReload no longer works. Is there any way to check which port is being used by HotReload.

**Comment by AndreiMisiukevich** [comment]
> I am facing the same problem only in VS 2017 for Windows, after updating the package and the extension HotReload no longer works. Is there any way to check which port is being used by HotReload.

yes, of course. When you "enable" extension, it shows you alert with port number

**Comment by renatojunior2009** [comment]
Okay, and how do I configure this port, because the window to inform the IP has disappeared, this is done automatically now?

**Comment by AndreiMisiukevich** [comment]
@renatojunior2009 yes, it is.
Please read Readme file! https://github.com/AndreiMisiukevich/HotReload/issues/77#issuecomment-502370371

**Comment by JigarM** [comment]
@AndreiMisiukevich yes let me try it on Monday and will let the thread know

**Comment by AndreiMisiukevich** [comment]
Can anybody create video of full reproduction this issue?

With showing code of setup, reloader and extensions versions

**Comment by renatojunior2009** [comment]
Hi, follow the image link capped by the VS Log with the error in the extension

[https://drive.google.com/file/d/1sBEw7pkIEcRaUX7_s45hqhq3Zjjprv_2/view?usp=sharing](url)

**Comment by AndreiMisiukevich** [comment]
@renatojunior2009 I don't understand this language. Could you please provide more info in English?

**Comment by renatojunior2009** [comment]
[error](https://drive.google.com/file/d/1sBEw7pkIEcRaUX7_s45hqhq3Zjjprv_2/view?usp=sharing) happened as soon as you installed the extension and restarted visual studio. Access link to view error details

**Comment by renatojunior2009** [comment]
[error](https://drive.google.com/file/d/1sBEw7pkIEcRaUX7_s45hqhq3Zjjprv_2/view?usp=sharing)
error happened as soon as you installed the extension and restarted visual studio. Access link to view error details

**Comment by AndreiMisiukevich** [comment]
Hm, try to remove extension, restart VS, install extension again, restart VS again

**Comment by renatojunior2009** [comment]
I tried three times and I did not succeed, I even reinstalled Visual Sudio.

**Comment by renatojunior2009** [comment]
[Attached](https://drive.google.com/file/d/1u2kjY_smGjRNf3qHWl8VnF32hNVJ-SPZ/view?usp=sharing) is the video I recorded showing the whole process.

**Comment by AndreiMisiukevich** [comment]
@renatojunior2009 thanks.
I will check.

Btw, tell me please your VS version too :)

**Comment by renatojunior2009** [comment]
I am using Enterprise version 2017 15.9.13.

**Comment by marcosmusk** [comment]
Same issue here in VS 2019 and VS 2019 for mac, not working in iOS and Android.
HotReload 1.4.9

**Comment by AndreiMisiukevich** [comment]
> [Attached](https://drive.google.com/file/d/1u2kjY_smGjRNf3qHWl8VnF32hNVJ-SPZ/view?usp=sharing) is the video I recorded showing the whole process.

it's **exe** file!

provide me video

**Comment by AndreiMisiukevich** [comment]
Has anybody solve this issue yet? (after reading Readme file)

**Comment by AndreiMisiukevich** [comment]
reproduced.

Seems 15002 port is reserved or something else..

**Comment by prasadsunny1** [comment]
Netstat shows nothing like that

**Comment by AndreiMisiukevich** [comment]
[HotReload.MacVS.HotReload.MacVS_1.3.4.mpack.zip](https://github.com/AndreiMisiukevich/HotReload/files/3294864/HotReload.MacVS.HotReload.MacVS_1.3.4.mpack.zip)


Hey, mac users, can anyone check this version of extension (unzip archive and install extension from file)

**Comment by prasadsunny1** [comment]
Let me check, In 3 hours

**Comment by marcosmusk** [comment]
> [HotReload.MacVS.HotReload.MacVS_1.3.4.mpack.zip](https://github.com/AndreiMisiukevich/HotReload/files/3294864/HotReload.MacVS.HotReload.MacVS_1.3.4.mpack.zip)
> 
> Hey, mac users, can anyone check this version of extension (unzip archive and install extension from file)
> 
> Does it solve the problem on mac?
> 
> if yes, i will publish it to store and ask @stanbav to update Windows as well

This build works on Mac with Xamarin Forms 4.0.0.497661, only in iOS for while. 
Android I tried but didn't worked, I guess it is because the port configuration...

**Comment by AndreiMisiukevich** [comment]
@marcosmusk did you try on android real device or emulator ?

**Comment by AndreiMisiukevich** [comment]
Tonight will be release for Windows and Mac and new nuget version

**Comment by AndreiMisiukevich** [comment]
> [Attached](https://drive.google.com/file/d/1u2kjY_smGjRNf3qHWl8VnF32hNVJ-SPZ/view?usp=sharing) is the video I recorded showing the whole process.

@renatojunior2009 

What is it?) Do you think i am silly?)

![image](https://user-images.githubusercontent.com/10124814/59597369-53004700-9102-11e9-983f-f02e9989e95a.png)

**Comment by AndreiMisiukevich** [comment]
@stanbav will push new extension releases in short time (today, maybe tomorrow)

**Comment by shyam-s00** [comment]
@AndreiMisiukevich 

I too had a similar issue in Windows with VS2019. 
In log I can see below. 

06-17 08:34:31.565 I/mono-stdout(27785): [OBSOLETE] ### AVAILABLE DEVICE's IP: http://192.168.43.163:8000 ###
06-17 08:34:31.567 I/mono-stdout(27785): ### HOTRELOAD STARTED ###

But device is not getting updated. 

Will your next release address this issue?

**Comment by AndreiMisiukevich** [comment]
@shyam-s00 what does extension show you 15002 port too?

**Comment by shyam-s00** [comment]
Nope. it still shows 15000. 
Actually it was working until couple of week back. From today, after upgrade its stopped working. 

Tried this and still no luck... 

 HotReloader.Current.Run(this, new HotReloader.Configuration {
                    DeviceUrlPort = 8000,
                    ExtensionAutoDiscoveryPort = 15000
                });

**Comment by AndreiMisiukevich** [comment]
@shyam-s00 do you on android emulator?
Did you forward ports regarding to Readme ?

**Comment by AndreiMisiukevich** [comment]
@shyam-s00 your device and PC/laptop should be in the same network (if you test on real device)

**Comment by ThallisonRhanniel** [comment]
Here it stopped working on friday

I'm using: **HotReloader.Current.Run (this);**

Windows 10
Real Device in the same network : Android 7.0
Visual Studio 2019: 16.1.1
Visual Studio Extension Port : 15000
Xamarin Forms: 3.6.0.344457
HotReload: 1.4.10

**Comment by marcosmusk** [comment]
> @marcosmusk did you try on android real device or emulator ?
> 
> Because in case of emulator you should forward port (check Readme file)

In real device (android 7.0) it's working, I will try to configure port forwarding in emulator.

**Comment by AndreiMisiukevich** [comment]
@marcosmusk btw, we want to add "port autoforward" feature as well ) so you won't need to forward them anymore

**Comment by marcosmusk** [comment]
Nice, would be a nice feature.
Btw, you're doing a great job, thanks!

**Comment by AndreiMisiukevich** [comment]
@marcosmusk not me only :)
@stanbav and @iBavtovich these guys contributed a lot ) 


Anyway thanks)

**Comment by shyam-s00** [comment]
@AndreiMisiukevich 
Yeah. Both device and laptop are in same network. Tried Port Forward as well and still its not working for me. 

there is only one difference that I could see. Previously when I enable the hot reload I was getting device connection list window.

Win 10,
VS2019 Enterprise 
Physical Device . Android 7.1.1
Xamarin Forms 3.2

**Comment by ThallisonRhanniel** [comment]
I returned the previous version, now it is working. 👍 
Nuget HotReload : 1.3.0
Extension Visual Studio:  1.1.3.

**Comment by renatojunior2009** [comment]
Hi, I've come to disagree with the virus detected, in no time was my intention, this is a tool that I use to record videos on my computer, it really saves in .exe, once again I apologize, I saw that it posted in github but I had no way of answering for him. To verify that this is not really a virus. I dowloaded it from the following site. Software Screen2EXE

https://screen2exe.soft112.com/

**Comment by renatojunior2009** [comment]
After upgrading visual studio to version 2019 and installing extension 1.3.2 and HotReload 1.49 package came back up, but I noticed a delay of 10 seconds for the change to be rendered on the screen.

**Comment by AndreiMisiukevich** [comment]
use nuget 1.4.10 and extension 1.3.5
