### ISSUE TITLE
Não funciona apos atualizaçao de pacote e Extensao

### ISSUE THREAD

**Issue by renatojunior2009** [AndreiMisiukevich/HotReload#78]
Apos atualizar a extensão e o nuget para a ultima versão não consigo mais usar o HotReload, já desinstalei e instalei novamente por diversas vezes e nada,

**Comment by AndreiMisiukevich** [comment]
first of all, use English please.


https://github.com/AndreiMisiukevich/HotReload follow Readme. We added IP autodiscovery feature
