### ISSUE TITLE
Doesn't work on real iOS device

### ISSUE THREAD

**Issue by pm64** [AndreiMisiukevich/HotReload#79]
Testing with a blank shell template project in VS2019. Device is a 2nd-generation iPad Pro. Verified ports, restarted VS, rebooted machine & device. Everything is on the same LAN. Any suggestions?

**Comment by AndreiMisiukevich** [comment]
Do you work on Mac?

**Comment by pm64** [comment]
No, Windows 10 x64

**Comment by AndreiMisiukevich** [comment]
@pm64 please provide screenshot of extensions alert and setup code.

**Comment by pm64** [comment]
![image](https://user-images.githubusercontent.com/10715458/59669132-82e53400-916e-11e9-855f-bbbb237feb66.png)

**Comment by AndreiMisiukevich** [comment]
@pm64 
Thanks, and tell me please your LAPTOP/PC IP address and your DEVICE IP address

**Comment by pm64** [comment]
The PC and laptop are both on the same /24 subnet.

**Comment by AndreiMisiukevich** [comment]
@pm64 yeah, but tell me IPs please (local IPs)

**Comment by pm64** [comment]
@AndreiMisiukevich - I just emailed you that information

**Comment by uksreejith** [comment]
@AndreiMisiukevich Similar issue for me too. Not working on an iPhone. I am using Visual studio 2017. Connected to a mac mini via mac agent and the iPhone is connected to the Mac mini via USB.

IP address for visual studio machine : 192.168.1.9
IP address of iPhone : 192.168.1.4

**Comment by pm64** [comment]
@AndreiMisiukevich I tried your suggestion of downgrading to 1.3.1 and initializing as follows:
`HotReloader.Current.Start(this, 8000, ReloaderScheme.Https)`
Unfortunately, this did not have any effect.

**Comment by AndreiMisiukevich** [comment]
@pm64 thanks for investigation

**Comment by phil-harmoniq** [comment]
Any updates on this? I can't get HotReload to work on a physical iPhone regardless of if I am building/deploying from Windows or my Mac

**Comment by AndreiMisiukevich** [comment]
@phil-harmoniq not yet, sorry
i think official Microsoft HotReload should work

**Comment by AndreiMisiukevich** [comment]
@phil-harmoniq I think for iOS/Android development you should go ahead with official MS HotReload
