### ISSUE TITLE
[Windows] HotReload auto discovery sometimes doesn't work

### ISSUE THREAD

**Issue by AlonRom** [AndreiMisiukevich/HotReload#80]
Hi Andrei,

For some reason after a long period that everything was working great, the Hot Reload stopped working last week.

I was working with an old version 1.2.4 but I think since the extension was updated by itself things stopped working.

I tried about everything including:

1. updating to the newest version 1.4.10
2. reinstall the extension tool
3. Adding the adb path to the environment path
4. forwarding: adb forward tcp:8000 tcp:8000 after I made sure the output log said it was 8000
5. Changes start to run:   HotReloader.Current.Run(this);

I'm running on a device, on windows and it worked on that device for quite some time until last week.

Is there a way to go back to 1.2.4 with prior extension?

Thanks!

**Comment by InquisitorJax** [comment]
I think this is a fairly recent breaking change.
Everything was working fine yesterday.
This morning default ports changed from the 15X range to 17502 - not sure what's going on, but super disappointed that lately this plugin is costing more time than it is saving.
Also windows VS 2017 + android emulator

**Comment by AlonRom** [comment]
Just want to go back to how it was 1.2.4, works great and saved a lot of time.
Now I wasted two days to try to make in work again.

**Comment by InquisitorJax** [comment]
@AlonRom  if you want to roll back - have a look here at #73 - there's a link to an old version of the extension there (and you need to turn off auto-update for the extensions as well)

**Comment by AlonRom** [comment]
Thanks @InquisitorJax ! I will try

**Comment by AndreiMisiukevich** [comment]
@AlonRom did you install 1.3.5 version of extension?

![image](https://user-images.githubusercontent.com/10124814/59748675-486dbb00-9284-11e9-9f0e-a2195fcbb370.png)

**Comment by AlonRom** [comment]
@AndreiMisiukevich yes!

**Comment by AndreiMisiukevich** [comment]
@AlonRom ```Changes start to run: HotReloader.Current.Run(this);```

but what does extension show you? what port value ?

**Comment by AlonRom** [comment]
15000

**Comment by AndreiMisiukevich** [comment]
@AlonRom try to disable firewall

**Comment by AlonRom** [comment]
@AndreiMisiukevich  Where? how?
I don't think it's the best solution and can't apply it in the work routine

**Comment by AndreiMisiukevich** [comment]
@AlonRom i can explain how does it work:

1) Extensions opens UDP receiver on that port, which it shows in alert
2) Reloader build url "http://{deviceIp}:{DeviceUrlPort}" and broadcast it via UDP client to that port (ExtensionAutoDiscoveryPort).
3) Then extension sends updates to your device/emulator by that url

Well, try to find your PC/LAPTOP ip (NOT DEVICE IP!)

and

ExtensionIpAddress = IPAddress.Parse("YOUR LAPTOP IP HERE") (e.g. 192.168.1.8)

It's property of configuration

It will force to send device's url directly to your PC instead of broadcasting.

**Comment by AndreiMisiukevich** [comment]
@AlonRom do you work on Windows?

**Comment by AlonRom** [comment]
@AndreiMisiukevich yes

**Comment by AndreiMisiukevich** [comment]
@AlonRom just had a call with @InquisitorJax 
Sooo, it's strange thing, but could you please try:

1) Enable extension (it will show you a port value)
2) put this port value to config (if it isn't 15000 for sure, if it is, you may skip this step)
3) run your application
4) after running the application make this (find that message and make adb forward yourself)
![image](https://user-images.githubusercontent.com/10124814/59751902-05aee180-928a-11e9-9e71-84d59c120f68.png)

**Comment by AndreiMisiukevich** [comment]
@AlonRom just in case you may try to
```adb forward tcp:8000 tcp:8000```
```adb forward tcp:8001 tcp:8001```
```adb forward tcp:8002 tcp:8002```
```adb forward tcp:8003 tcp:8003```

**Comment by AndreiMisiukevich** [comment]
@AlonRom does it help?


Okay, anyway @stanbav  and me decided to release old extensions as separate extension. So, everybody will be able to decide which one to use.

Does it sound good?

**Comment by AlonRom** [comment]
@AndreiMisiukevich everything you mentioned above I already did with no success.
But why use ports 8001,2,3?

When will you provide the option to go back to older extensions?

**Comment by AndreiMisiukevich** [comment]
@AlonRom today i think

**Comment by AndreiMisiukevich** [comment]
but i suggest you to try on REAL android device:

```xaml
            HotReloader.Current.Run(this, new HotReloader.Configuration
            {
                DeviceUrlPort = 4981, //or other values
                ExtensionAutoDiscoveryPort = {value from alert},
                ExtensionIpAddress = IPAddress.Parse({your PC ip here}
            });
```

**Comment by AlonRom** [comment]
@AndreiMisiukevich 
I'm using a real device all the time, the same one I used when it worked:

1. DevicePort - I put 8000 as the output suggested:
### HOTRELOAD STARTED ON DEVICE's PORT: 8000 ###

2. ExtensionAutoDiscoveryPort  - I put 15000 as the alert window suggested.

3. ExtensionIpAddress = IPAddress.Parse("172.18.8.67")
I took it from cmd after ipconfig command:    IPv4 Address. . . . . . . . . . . : 172.18.8.67

Still nothing..

**Comment by AndreiMisiukevich** [comment]
@AlonRom tell me please your android device IP

**Comment by AlonRom** [comment]
12.0.0.20

**Comment by AndreiMisiukevich** [comment]
@AlonRom ... https://www.speedguide.net/ip/12.0.0.20

it's not LOCAL ip address. Your device and your PC/laptop must be at the same local network

**Comment by AlonRom** [comment]
Now changed to:10.166.172.6
Just tell me where to look and what to do and I will provide the details.

**Comment by AndreiMisiukevich** [comment]
> Now changed to:10.166.172.6
> Just tell me where to look and what to do and I will provide the details.

- 172.18.8.67
- 10.166.172.6

is it possible to put device and your pc to the same addresses range

for example to 172.18.8.{value} ?

**Comment by AlonRom** [comment]
This was it!!! working:)

**Comment by InquisitorJax** [comment]
@AndreiMisiukevich is this something users need to be aware of and fix themselves - or can this be remedied with a hotreload update?

**Comment by AndreiMisiukevich** [comment]
@InquisitorJax not sure that there is possibility to change device's IP
So, i think it makes sense to put more info in Readme. Do you want to send PR with info :) . ?

**Comment by IoTFier** [comment]
It has stopped working on VS 16.1.3 as well.  HotReload extension 1.3.5 and Nuget package 1.4.10
My VS port is 15000, app.cs has following after initialize()
#if DEBUG
            HotReloader.Current.Run(this);
            //optionaly you may specify EXTENSION's port for auto discovery and device's port
#endif
This extension has been very unstable, ever since the auto detect IP feature (BTW which is great) was launched.

**Comment by AndreiMisiukevich** [comment]
@IoTFier look through the discussion. We have already resolved this question.

also you may use old extensions with newest nuget package https://github.com/AndreiMisiukevich/HotReload/tree/master/old_extension_packages

**Comment by InquisitorJax** [comment]
@AndreiMisiukevich after our discussion yesterday, it stopped working again, and resetting the adb port forwarding didn't help.
I'll try again later (and also the old extensions) to see if anything changes.

**Comment by IoTFier** [comment]
@AndreiMisiukevich , thank you for your response.  I use iOS simulator and Android device.

I did read the discussion and will definitely read it again, if I missed any step. My VS extn is configured to update automatically.

The point I was making earlier is - new updates have taken toll on productive time when using this extension. New improvements are intended for great purpose, but they have destabilized the core functionality. I will feel, we should at least know the IPs it is connecting to. 

Regarding port # besides 15000; do we have to change the code every-time to provide the port number if it is not 15000 ?

Thank you

**Comment by InquisitorJax** [comment]
@IoTFier I had the same feedback ... before setting up IP numbers was a once-off. With the new changes - that port 15X could change every time you connect - which means changing code - which doesn't really help in a team setting.
I prefer the old extension - but that's disappointing, because that means it's not going to be getting new features.

**Comment by AndreiMisiukevich** [comment]
@IoTFier are you sure that Windows extension ever works with iOS simulators at all?
As for Android device

Can you confirm that your device IP and your PC ip are in the same IP range ?

**Comment by IoTFier** [comment]
@InquisitorJax - I am not sure if it make sense to go backward by losing features and functionality for getting stability.  I truly thank @AndreiMisiukevich & co to provide us with this great help. My request is to not compromise on basic usability of this tools when launching / adding new features / bug-fixes.

**Comment by AndreiMisiukevich** [comment]
@IoTFier old extension is stable. It just doesn't have autodiscovery feature.

**Comment by InquisitorJax** [comment]
@AndreiMisiukevich perhaps consider keeping the old IP dialog - but add a checkbox that enables auto-IP discovery? That way if there's a problem with auto-discover, it's a lot easier to uncheck that feature, rather than installing older extensions?

**Comment by IoTFier** [comment]
> @IoTFier are you sure that Windows extension ever works with iOS simulators at all?
> As for Android device
> 
> Can you confirm that your device IP and your PC ip are in the same IP range ?
Yes, it was working before this port # feature was brought in. Ever since that I have lost the functionality... Let me put it this way .. it is hit and miss

My android device IP and PC ip are in the same range. 
I use HotReload more on the iOS simulator than Android.

**Comment by IoTFier** [comment]
> @IoTFier old extension is stable. It just doesn't have autodiscovery feature.
@AndreiMisiukevich - It is certainty a great planned feature; 
   My request is to display those connected IPs, and OS version , and device / simulator name (old extn++? )

**Comment by AndreiMisiukevich** [comment]
> @AndreiMisiukevich perhaps consider keeping the old IP dialog - but add a checkbox that enables auto-IP discovery? That way if there's a problem with auto-discover, it's a lot easier to uncheck that feature, rather than installing older extensions?

need to discuss with @stanbav

**Comment by AndreiMisiukevich** [comment]
@IoTFier have you tried this as well? (put your PC ip there)

![image](https://user-images.githubusercontent.com/10124814/59838431-8e478380-9357-11e9-807b-ddc8448559f2.png)

**Comment by AndreiMisiukevich** [comment]
@InquisitorJax as for entering Extension port. We can easily solve this problem. Reloader may send its ip to range of possible IP, so you won't need to copy-paste anything

**Comment by AndreiMisiukevich** [comment]
1.4.12 nuget package

new extensions will be available soon. Read readme again please
@InquisitorJax no need to fill extension's port anymore. Just ignore alert message :)

**Comment by IoTFier** [comment]
Hi @AndreiMisiukevich I have latest extension and nuget package, tried above suggested step by you.

No luck. It is still not working.. Can you please keep this issue open?

Thanks

**Comment by AndreiMisiukevich** [comment]
@IoTFier reach me in skype please csi.andreymisyukevich

**Comment by AndreiMisiukevich** [comment]
@IoTFier case is WINDOWS + iOS simulator :)

**Comment by IoTFier** [comment]
thank you @AndreiMisiukevich 
I am seeing issue on both iOS simulator and Android emulator as well. 
My Android emulator has IP address in a different subnet, even though android emulator is running off my PC.  

Also, searching of "$"### HOTRELOAD STARTED ON DEVICE's PORT:" in VS output resulting in nothing. Am I missing any step in the android config for the HOTRELOADER to not to get fired off when app.xaml.cs is loaded ?

With old extn I could enter IP address of my iOS simulator and Android device; and it worked fine. I had never tried Android simulator. That's my next move until the latest ext 1.3.6 is ready to use.

Thank you for your help.

**Comment by IoTFier** [comment]
@AndreiMisiukevich it seems that old extn 1.2.1 is not compatible with VS 2019 when I tried to install it... 
Is that right ? How do I configure / install it for VS 2019?

**Comment by AndreiMisiukevich** [comment]
No idea, should work. Try to restart VS, after removing

**Comment by IoTFier** [comment]
I have no instance of VS 2017/2019 running.
FYI..
![image](https://user-images.githubusercontent.com/26844611/60272486-e2071f00-98b9-11e9-8f5c-7478ff520dae.png)

![image](https://user-images.githubusercontent.com/26844611/60272567-0d8a0980-98ba-11e9-9fff-09bc775ce32f.png)

**Comment by IoTFier** [comment]
Figured out... just disabling the extn for installing old one doesn't work. We need to uninstall the new extension before the old one recognizes a need to install it on that VS. Not sure if it make sense fully... VS should provide an option for choosing the version # it is already installed ...
![image](https://user-images.githubusercontent.com/26844611/60273288-6efea800-98bb-11e9-93df-2c519e5be7d6.png)

**Comment by IoTFier** [comment]
@AndreiMisiukevich ,
the old extension works like a charm !

**Comment by AndreiMisiukevich** [comment]
@IoTFier i think, nice to hear it. Do you use 127.0.0.1 for iOS simulator reloading?

**Comment by glaubermarcelino** [comment]
I managed to run the hotreload with the latest version in emulators, so it was necessary to map the folder of adb.exe, close the visual studio and reopen, enabling "Enable it" the hotreload.
The settings I left were these in App.Xaml.cs.

`HotReloader.Current.Run(this);`

**Comment by AndreiMisiukevich** [comment]
> I managed to run the hotreload with the latest version in emulators, so it was necessary to map the folder of adb.exe, close the visual studio and reopen, enabling "Enable it" the hotreload.
> The settings I left were these in App.Xaml.cs.
> 
> `HotReloader.Current.Run(this);`

Yeah :) as described in documentation :)

**Comment by glaubermarcelino** [comment]
> > I managed to run the hotreload with the latest version in emulators, so it was necessary to map the folder of adb.exe, close the visual studio and reopen, enabling "Enable it" the hotreload.
> > The settings I left were these in App.Xaml.cs.
> > `HotReloader.Current.Run(this);`
> 
> Yeah :) as described in documentation :)

However for it to work according to the instructions it is necessary to close and reopen Visual Studio otherwise it does not work

**Comment by AndreiMisiukevich** [comment]
@IoTFier what IP do you use for iOS simulator on Windows?

**Comment by IoTFier** [comment]
@IoTFier , sorry for my delay.. trying to get you the info... but the meantime the extn got upgraded ., I did uncheck the box of auto upgrade.. reinstalling it will let you know

**Comment by IoTFier** [comment]
@AndreiMisiukevich - my apologies for the delay again. The IP Address of my iOS Simulator is same as the IP address of my Mac machine.

The issue I was facing about text was .. .just unchecking the upgrade of the extn wasn't enough. Along with that it is also necessary to disable that (uncheck) under tools -> options -> environment -> extensions .. see the pic below.. 
Otherwise, if you were to open another VS instance, it keeps upgrading the extension from 1.2.1 to the latest one 

![image](https://user-images.githubusercontent.com/26844611/60477803-f9416600-9c45-11e9-8680-2eb2b1dcb2a3.png)

**Comment by AndreiMisiukevich** [comment]
@IoTFier so, let's imagine that your PC ip is 192.168.0.12
You enters http://192.168.0.12:8000 to extension box and it works well, right?

**Comment by IoTFier** [comment]
@AndreiMisiukevich - yes, that's what seems to be correct.

**Comment by MagicAndre1981** [comment]
the port get changed for me when Hotrelaod is connected, but I close the solution and open a new one (now 15001). On closing a solution Hotreload should disconnect automatically. 

Maybe this helps others with connection issues.

**Comment by Tyri0n** [comment]
This is working great for me in Android emulator - thanks!

In iOS simulator (running in Mojave VM) it takes about 45 seconds for any changes to appear. Any ideas?

**Comment by AndreiMisiukevich** [comment]
@Tyri0n wow. Weird. Do you work on virtual machine?
anyway try to disable your firewall

**Comment by Tyri0n** [comment]
I code in VS 2019 under Windows 10. Mojave runs in VM on same Windows host. Mojave firewall is off.

For some reason it seems a bit better now. Sometimes saving a xaml change is causing the app to jump to a different page and the change is visible when navigating back.

I suspect it's a simulator issue - I usually have to double tap buttons to change page whereas it works fine on device.

Anyways, thanks for the quick response.

**Comment by AndreiMisiukevich** [comment]
can be closed i think
