### ISSUE TITLE
Cant get working with prism app

### ISSUE THREAD

**Issue by SShaw1985** [AndreiMisiukevich/HotReload#81]
Hi

I have set up the extension as descvribed but cant get an emulator to update using the ios emulator on vs for mac.

is there an extra step needed to get Prism working also?

Many thanks

**Comment by AndreiMisiukevich** [comment]
try to run HotReload from AppDelegate

var app = new PrismApp();
HotReloader.Current.Run(app);

**Comment by AndreiMisiukevich** [comment]
![image](https://user-images.githubusercontent.com/10124814/59909479-708e2300-9418-11e9-990d-c16627435640.png)

![image](https://user-images.githubusercontent.com/10124814/59909503-7ab02180-9418-11e9-9cfa-0cca8a903fa9.png)

![image](https://user-images.githubusercontent.com/10124814/59909517-869be380-9418-11e9-9039-36014041c153.png)

OR

![image](https://user-images.githubusercontent.com/10124814/59909605-b21ece00-9418-11e9-9865-fba3fb3d78de.png)
