### ISSUE TITLE
Differences of Setup for Xaml and pure CS Pages

### ISSUE THREAD

**Issue by cassionandi** [AndreiMisiukevich/HotReload#83]
Hi folks.

Is there any differences that we must be aware when working with pure C# Pages?

Something like:

`public class MainPageCS : ContentPage
    {
        public MainPageCS()
        {
            Content = GetContent();
        }

        private View GetContent()
        {
            var mainLayout = new StackLayout
            {
                Children = {
                    new Label { Text = "Text Label", FontSize = 40 }

                }
            };
            return mainLayout;
        }
    }`

I have a sample project that works fine with XAML, but not the the code-behind nor an only-C# page like the above code.

**Comment by AndreiMisiukevich** [comment]
Hi)
Csharp code reloading isn’t supported by this plugin. Xaml and CSS only

**Comment by cassionandi** [comment]
It's curious because I saw a live stream with @davidortinau and @rdavisau working on Xappy (https://www.twitch.tv/videos/441875218), and the code was hot reloading, and the repo seems indicates HotReload using whttps://github.com/rdavisau/Xappy/blob/master/Xappy/Xappy/App.xaml.cs

**Comment by AndreiMisiukevich** [comment]
Oh ?

**Comment by cassionandi** [comment]
> Oh ?

I discovered that they were using Continuous on the live stream, but it was not commited on the repo. Sorry for the inconvenience.
