### ISSUE TITLE
HotReloader as realtime previewer

### ISSUE THREAD

**Issue by IoTFier** [AndreiMisiukevich/HotReload#86]
Hi @AndreiMisiukevich ,

Is a real-time previewer functionality possible using HotReloader i.e. switch to a realtime preview and HotReloader, if -
1. I add a new ContentPage or ContentView in my app which is not functionally used directly in my app 
2. In VS editor panel, switch from ContentPage / ContentView to another one already present in the solution ?

It also will be nice if we could use xmlns:d="http://xamarin.com/schemas/2014/forms/design" while using that feature. 

Thanks

**Comment by AndreiMisiukevich** [comment]
sorry
HotReload is real-time xaml/css reloader
it's not designed to be a previewer.

**Comment by IoTFier** [comment]
Hi @AndreiMisiukevich - 

As much I understand and respect the intent behind HotReloader functionality.

For the faster productivity - both HotReloader and previewer go both hand-in-hand. The either/or approach is never a complete tooling to make use of XAML for delivering value.

I hope you will reconsider my request. 
The potential of impact is huge and upwards. Please think about it.

**Comment by AndreiMisiukevich** [comment]
@IoTFier well, you win
i will think about it

**Comment by IoTFier** [comment]
@AndreiMisiukevich - thank you for your consideration.
Bringing this capability will definitely be a great Game Changer for many of us out there.

Thank you.

**Comment by AndreiMisiukevich** [comment]
@IoTFier https://github.com/AndreiMisiukevich/HotReload#additional-setup--troubleshooting 

point number 6
