### ISSUE TITLE
connecting to a uwp local machine

### ISSUE THREAD

**Issue by al3xmeister** [AndreiMisiukevich/HotReload#87]
Having issues with running the previewer on a local machine, esentially the lightning bolt keeps disappearing, and when I do manage to enable it, the extension doesnt work fine - as it does, flawlessly, on android tablets. Could you please assist me whenever you have the time? Many thanks in advance

**Comment by AndreiMisiukevich** [comment]
https://github.com/AndreiMisiukevich/HotReload/issues/41


@MagicAndre1981 could you please explain how have you run HotReload on UWP ?

**Comment by MagicAndre1981** [comment]
local machine/Simulator is not working. I always have setup Remote Debugging from my Win10 dev VM to my Windows 10 tablet to test it. My original issue 41 was already linked. [UWP has server capabilities](https://docs.microsoft.com/en-US/windows/uwp/networking/sockets#build-a-basic-tcp-socket-client-and-server) and allows local access with `Fiddler\EnableLoopback.exe` , but it may [require extra work](https://github.com/twisteroidambassador/retroflect/) which I also never got working.

**Comment by AndreiMisiukevich** [comment]
@MagicAndre1981 thanks)

@al3xmeister so, this is limitation of HotReload.

**Comment by al3xmeister** [comment]
@Andrei Misiukevich <andrei.misiukevich@gmail.com>

Thanks for the info,

I'm away to configure a VM and test further, may ask please, what software
are you using for running a windows 10 tablet VM on you desktop?

Kindest regards,


Alex Danicel, MSc.
m: 07534848580

**Comment by AndreiMisiukevich** [comment]
@MagicAndre1981 i would be grateful if you was able to reply :) cuz i'm totally mac user

**Comment by MagicAndre1981** [comment]
> Thanks for the info, I'm away to configure a VM and test further, may ask please, what software are you using for running a windows 10 tablet VM on you desktop? 

Follow the [steps here](https://docs.microsoft.com/en-US/visualstudio/debugger/run-windows-store-apps-on-a-remote-machine?view=vs-2019) and install the Remote Debug tools on Tablet and specify the tablet device name in debug properties.

When you press F5 to debug the app, it gets deployed to tablet and now you can use Hotreload to see the changes of the XAML file in realtime on the tablet.

**Comment by al3xmeister** [comment]
Thank you so much for the prompt response guys,

Will keep on using and recommending your extension to colleagues and
friends.

Kindest regards,


Alex Danicel, MSc.
m: 07534848580
