### ISSUE TITLE
Lost in Space?

### ISSUE THREAD

**Issue by DwainSnickles** [AndreiMisiukevich/HotReload#88]
![VSCapture](https://user-images.githubusercontent.com/26853477/60761402-db3c8280-a004-11e9-9dd8-280a9b0a45ec.PNG)
I think I am missing the big picture here? I have HotReload its loaded and running in visual studio 2017. How do I view the xaml I am working on.?

**Comment by AndreiMisiukevich** [comment]
@DwainSnickles first of all, why do you have two HotReload icons??
Please remove HotReload extension, restart Visual Studio, install HotReload again and restart Visual Studio again. You should have only one lightning icon.

Then follow Readme guid

**Comment by AndreiMisiukevich** [comment]
guideline *

**Comment by DwainSnickles** [comment]
Ok revived as requested on start up of Visual studio there is only 1 white icon however I get a yellow notification saying it is not enabled click here to enable hotreload after clicking to enable I get both icons.

**Comment by DwainSnickles** [comment]
![Capture3](https://user-images.githubusercontent.com/26853477/60772088-337b8f00-a0ae-11e9-8eea-835a2c060686.PNG)
Going further into the readme I added the following but getting a error hotreload not found in current context and the hotreload is connected and using Xamarin.Forms; is included in the using statement.

**Comment by AndreiMisiukevich** [comment]
@DwainSnickles read Readme till end please... add nuget package...

**Comment by DwainSnickles** [comment]
I thought I had the nugget package  ok installed that restarted vs added the Hotloader current run no issue I still don't see a visual designer.

**Comment by AndreiMisiukevich** [comment]
@DwainSnickles it's not designer.. you should run your app and change xaml in real time

**Comment by DwainSnickles** [comment]
That's the part I was missing thanks for being patient

**Comment by DwainSnickles** [comment]
Hi Andrei sorry to be a pain but was never able to get this working First I needed to get the Android emulator working I did that. I added the nugget package it show in properties in the android app. According to the instructions I should add the  following
       public App()
        {
            InitializeComponent();
#if DEBUG
            HotReloader.Current.Run(this);
#endif

            MainPage = new MainPage();
        }
It still shows doesn't exist I am using xarmin cross platform and this error is in the c# part of it. What am I missing here if I put it in the android it cant find the (this) but the Hotloader is found. I thought maybe I needed the nugget cli for dotnet but that doesn't load  in the package manager. 
dotnet add package Xamarin.HotReload --version 1.4.12

**Comment by AndreiMisiukevich** [comment]
you can put it in android part as well (in MainActivity)
```
var app = new App();
HotReloader.Current.Run(app);
LoadApplication(app);
```

**Comment by DwainSnickles** [comment]
I did try that after I verified the emulator was working but it appears to freeze up visual studio. I am giving up just wanted to let you know that. Thanks again for your support. I am ordering a Android tablet and maybe then I will try again.
![Capture4](https://user-images.githubusercontent.com/26853477/60987761-8304c980-a2ff-11e9-9717-7dceea9183c0.PNG)

**Comment by AndreiMisiukevich** [comment]
@DwainSnickles oh.... you made mistake, let me show you code...

**Comment by AndreiMisiukevich** [comment]
@DwainSnickles 

```csharp
    public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity
    {
        protected override void OnCreate(Bundle savedInstanceState)
        {
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;
            base.OnCreate(savedInstanceState);
            global::Xamarin.Forms.Forms.Init(this, savedInstanceState);
            var app = new App();
#if DEBUG
           HotReloader.Current.Run(app);
#endif
            LoadApplication(app);
        }
    }
```

**Comment by DwainSnickles** [comment]
Thanks Andre
One last question the emulator loads I make changes but the emulator doesn't refresh not sure if I am supposed to be seeing this in the emulator or just in the code view display window. Sorry but I relatively new to xarmin forms in Visual Studio. I assume the emulator should preview the changes?

**Comment by AndreiMisiukevich** [comment]
@DwainSnickles first of all use should add adb as environment variable

**Comment by AndreiMisiukevich** [comment]
yes, you should open page on emulator and work with it's xaml in VS.

**Comment by DwainSnickles** [comment]
Not exactly sure what you mean when you say add adb as environment variable did a quick google search but couldn't fidure it out.

**Comment by AndreiMisiukevich** [comment]
@DwainSnickles really? ) 

http://letmegooglethat.com/?q=add+adb+as+environment+variable

**Comment by AndreiMisiukevich** [comment]
i suggest you to re-read Readme of the project

**Comment by DwainSnickles** [comment]
Andrei I finally did get it to work didn't need the environment variable. After reading the readme several times which was a little confusing maybe I will create one specifically for windows. Hers what I ended up doing and I put this here for other noobes. On each xmal.cs  in project including app.xaml.cs:
#if !Debug
    [XamlCompilation(XamlCompilationOptions.Compile)]
#endif

**Comment by DwainSnickles** [comment]
**_FYI never assume_**. The only dumb question is the one not asked. I was searching google for adding the environment variable path for visual studio not for the windows pc and yes I did get a totally different result. "Yes Really". Anyway it is a cool program once you get it figured out. I never claimed to be intelligent my claim to fame is persistence. Thanks again Dwain

**Comment by AndreiMisiukevich** [comment]
@DwainSnickles great)

**Comment by DwainSnickles** [comment]
Adrei not sure if you want to share the link but I made a youtube video for installing Hotreload  for windows using Visual Studio. I wish I had this when I started several days ago. I think it would be very useful for others. Short simple and concise. Let me know if you think I missed anything. Thanks dwain.
