### ISSUE TITLE
Updating values in the resource files don't reflect changes via HotReload

### ISSUE THREAD

**Issue by IoTFier** [AndreiMisiukevich/HotReload#89]
Hi @AndreiMisiukevich ,

It seems changing of the data in the (AppResources) .resx files doesn't reflect on XAML changes via HotReload.

Is that a known behavior / limitation ? 
If so, can that support be added ?

Thank you

**Comment by AndreiMisiukevich** [comment]
It's limitation for now (only xaml and css supported), but maybe we enhance this in future

**Comment by Dids** [comment]
Same with separate/global XAML ResourceDictionary stuff, which I've started to use a lot now.

**Comment by AndreiMisiukevich** [comment]
@Dids hmm, it should work

can you provide small simple sample ? Because global resource dictionaries are supported (you may check my samples)

**Comment by AndreiMisiukevich** [comment]
Check latest nuget (will be available in 20-30 mins). CI is running now

**Comment by IoTFier** [comment]
Hi @AndreiMisiukevich , should you wait from closing this ticket until we get to validate the new nuget ?
Thanks

**Comment by AndreiMisiukevich** [comment]
@IoTFier just reopen it in case of issue still exists

**Comment by Dids** [comment]
@AndreiMisiukevich Something as simple as the example below didn't work, last I tried.

App.xaml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Application xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" x:Class="FooBar.App">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary Source="Styles/LoginPageStyle.xaml" />
        </ResourceDictionary>
    </Application.Resources>
</Application>
```

Styles/LoginPageStyle.xaml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ResourceDictionary xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml">
    <Style TargetType="Label" Class="LoginPageLoginLabel">
        <Setter Property="Text" Value="LOGIN" />
    </Style>
</ResourceDictionary>
```

LoginPage.xaml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" x:Class="FooBar.LoginPage">
    <ContentPage.Content>
        <StackLayout>
            <Label AutomationId="LoginPageLoginLabel" StyleClass="LoginPageLoginLabel" />
        </StackLayout>
    </ContentPage.Content>
</ContentPage>
```

Changes in `LoginPage.xaml` update fine, but changes in `Styles/LoginPageStyle.xaml` do not.

**Comment by AndreiMisiukevich** [comment]
@Dids please create small sample project) thanks
