### ISSUE TITLE
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation

### ISSUE THREAD

**Issue by acaliaro** [AndreiMisiukevich/HotReload#91]
Hi @AndreiMisiukevich 

I have tried to install HotReload following your instructions.

I have enabled the Xamarin.Forms HotReload in VS2019 then I press "run" to execute the project on a real device.

This is the exception:

![image](https://user-images.githubusercontent.com/5759350/60928252-fdf0c480-a2ac-11e9-819d-573198be5e91.png)

 Maybe I am wrong....

**Comment by acaliaro** [comment]
Solved, was a problem in Styles...

**Comment by AndreiMisiukevich** [comment]
@acaliaro nice to hear that you are with us :)

**Comment by acaliaro** [comment]
Yes @AndreiMisiukevich , but remember I am waiting HotReloading for C#.....
