### ISSUE TITLE
Any thoughts for supporting ViewModel or Code behind changes

### ISSUE THREAD

**Issue by Im-PJ** [AndreiMisiukevich/HotReload#92]
Any thoughts on supporting this? For e.g. I update Button click handler/command method and then see the button execute new method without deploying solution again. Just like Xaml reload but for C# reload. Is it possible.

**Comment by AndreiMisiukevich** [comment]
it is not possible for now. not sure that we add it

**Comment by AndreiMisiukevich** [comment]
https://twitter.com/Andrik_Just4Fun/status/1155963687980507136

**Comment by MagicAndre1981** [comment]
ok, hopefully we VS users can use it, too. Will this also work for UWP?

**Comment by Im-PJ** [comment]
Its working like a charm. Thanks for implementing it so soon. Waiting for VS windows as its my main IDE.

**Comment by AndreiMisiukevich** [comment]
> ok, hopefully we VS users can use it, too. Will this also work for UWP?

extension for VS for Windows is pushed as well.
Good question, i didn't check. So, you can do it :)

**Comment by AndreiMisiukevich** [comment]
> Its working like a charm. Thanks for implementing it so soon. Waiting for VS windows as its my main IDE.

1.4.0 is here https://marketplace.visualstudio.com/items?itemName=StanislavBavtovich.hotreloadxamarinforms

**Comment by MagicAndre1981** [comment]
> Good question, i didn't check. So, you can do it :)

doesn't work for me. I've made the extension update, added the attribute, but when the app is running, the Visual Studio text editor is locked and I can't type any code changes.

**Comment by AndreiMisiukevich** [comment]
@MagicAndre1981 https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-enable-and-disable-edit-and-continue?view=vs-2019

**Comment by MagicAndre1981** [comment]
the setting is already enabled. I now started the app without debugger, connected Hotreload, but code changes make no difference.

**Comment by AndreiMisiukevich** [comment]
> the setting is already enabled. I now started the app without debugger, connected Hotreload, but code changes make no difference.

have you added HotReloader.CSharpVisual attribute to your ContentPage ?
Keep in mind that you cannot mix xaml and code yet

**Comment by MagicAndre1981** [comment]
yes, I added the attribute.

I found this bug report:

https://github.com/xamarin/Xamarin.Forms/issues/1574

**Comment by MagicAndre1981** [comment]
ok, I also see the error message `Failed to emit module 'FooApp'` like in this [Stackoverflow question](https://stackoverflow.com/questions/54284619/edit-and-continue-does-not-work-on-xamarin), but I can't set PDB type to full, because here UWP also has a bug, that prevents debugging at all for Full symbols if shared code is .net standard 2.0:

https://github.com/dotnet/standard/issues/621
https://github.com/xamarin/Xamarin.Forms/issues/2712

**Comment by Im-PJ** [comment]
Does it only works on Android & ios Simulators as you have mentioned in the doc? I was trying on a real device and was not successful at first attempt.

**Comment by AndreiMisiukevich** [comment]
> Does it only works on Android & ios Simulators as you have mentioned in the doc? I was trying on a real device and was not successful at first attempt.

not sure
But i think it should work

**Comment by MagicAndre1981** [comment]
> But i think it should work

for me it also doesn't work with Lineageos OS 14.1 device connected via adb over Wifi

**Comment by MagicAndre1981** [comment]
tested now with VS2019 16.3 Preview1 also shows this for Android app on real device:

![image](https://user-images.githubusercontent.com/8274816/62192764-8297a580-b376-11e9-8c9f-34c4cbaaa06e.png)

and in error list I get `Failed to emit module 'FooApp'`

In debug output I can see that Hotreload shows its debug messages so it is running

**Comment by MagicAndre1981** [comment]
@AndreiMisiukevich can you share a demo app that works for you so that I can compare it with my csproj and detect differences?  Also have you tried it on real phone? As I already run inside a VM, running the emulator is difficult (nested VM).

**Comment by AndreiMisiukevich** [comment]
Unfortunately I am on vacation now.
You can try to play with sample app in free time. But frankly speaking I am not sure that code reloading is working on Win

**Comment by MagicAndre1981** [comment]
ok. I tried everything, but can't get it working.

To disable the error, I need to uncheck "Edit an continue" in options as suggested for a different tool that also offers C# code reloading:

![image](https://user-images.githubusercontent.com/8274816/62450394-86f40200-b76c-11e9-9016-4caccd6722f9.png)

But when I set breakpoint and edit code, I see the original values are assigned.

**Comment by MagicAndre1981** [comment]
ok, I see a warning about [Mono.Sharp](https://github.com/AndreiMisiukevich/HotReload/blob/aef8f31c89098784ac7a0c1ecc097db13ce3b23c/HotReload.nuspec#L23) conflict:

```
There was a conflict between "Mono.CSharp, Version=2.0.5.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756" and "Mono.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756".
1>    "Mono.CSharp, Version=2.0.5.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756" was chosen because it was primary and "Mono.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756" was not.
1>    References which depend on "Mono.CSharp, Version=2.0.5.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756" [C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0\Mono.CSharp.dll].
1>        C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0\Mono.CSharp.dll
1>          Project file item includes which caused reference "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0\Mono.CSharp.dll".
1>            Mono.CSharp
1>    References which depend on "Mono.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756" [].
1>        D:\Foo.App\packages\Xamarin.HotReload.1.4.19\lib
1>etstandard2.0\Xamarin.Forms.HotReload.Reloader.dll
1>          Project file item includes which caused reference "D:\Foo.App\packages\Xamarin.HotReload.1.4.19\lib
1>etstandard2.0\Xamarin.Forms.HotReload.Reloader.dll".
1>            Xamarin.Forms.HotReload.Reloader, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL
1>            D:\Foo.App\Foo.App\Foo.App\bin\Debug\Foo.App.dll
1>Found conflicts between different versions of "Mono.CSharp" that could not be resolved. 
```

can this be the cause of the failure? As you see (**packages**\Xamarin.HotReload.1.4.19\lib
1>etstandard2.0\Xamarin.Forms.HotReload.Reloader.dll)  I have to use packages.config, do you use the new PackageReference Include instead?

**Comment by Im-PJ** [comment]
@MagicAndre1981 Im also getting error about Mono.CSharp conflict due to which my project build is failing. Did you find any workaround?

**Comment by AndreiMisiukevich** [comment]
@Im-PJ fill new issue pls
It's bug and should be fixed (stay on 15 minor version, without code)

**Comment by Im-PJ** [comment]
Im sorry which version you mean exactly.

**Comment by AndreiMisiukevich** [comment]
@Im-PJ https://www.nuget.org/packages/Xamarin.HotReload/1.4.15

**Comment by MagicAndre1981** [comment]
@AndreiMisiukevich I created a [new ticket](https://github.com/AndreiMisiukevich/HotReload/issues/112)

**Comment by MagicAndre1981** [comment]
@AndreiMisiukevich 

when capturing Exception data with WPR.exe I see this NotSuportedException with callstack from Hotreload:


Line # | etw:ActivityId | Provider Name | Task Name | Time (s) | Opcode Name | Field 1 | Stack | Message | Event Name | Id | Process | Cpu | ThreadId | Field 1 | Field 2 | Field 3 | Field 4 | Field 5 | Field 6 | Field 7 | Field 8 | Field 9 | Field 10 | Field 11 | Field 12 | Field 13 | Field 14 | Field 15 | Field 16 | Count | Time (s)
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
56 |   |   |   | 130,868269600 |   |   | coreclr.dll!MethodDescCallSite::CallTargetWorker |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
57 |   |   |   | 130,868269600 |   |   | System.Private.CoreLib.dll!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
58 |   |   |   | 130,868269600 |   |   | System.Private.CoreLib.dll!System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
59 |   |   |   | 130,868269600 |   |   | System.Private.CoreLib.dll!System.Threading.Tasks.Task.ExecuteEntryUnsafe() |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
60 |   |   |   | 130,868269600 |   |   | System.Private.CoreLib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef) |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
61 |   |   |   | 130,868269600 |   |   | System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
62 |   |   |   | 130,868269600 |   |   | System.Private.CoreLib.dll!System.Threading.Tasks.Task+<>c.<.cctor>b__278_1(System.Object) |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
63 |   |   |   | 130,868269600 |   |   | System.Private.CoreLib.dll!System.Threading.Tasks.Task.InnerInvoke() |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
64 |   |   |   | 130,868269600 |   |   | Xamarin.Forms.HotReload.Reloader.dll!Xamarin.Forms.HotReloader+<>c::<Run>b__24_8 0x0 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
65 |   |   |   | 130,868269600 |   |   | System.Private.CoreLib.dll!System.Reflection.Assembly.Load(Byte[]) |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
66 |   |   |   | 130,868269600 |   |   | System.Private.CoreLib.dll!System.Reflection.Assembly.Load(Byte[], Byte[]) |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
67 |   |   |   | 130,868269600 |   |   | System.Private.CoreLib.dll![COLD] System.AppDomain.CheckLoadByteArraySupported() |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
68 |   |   |   | 130,868269600 |   |   | coreclr.dll!IL_Throw |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  

and the exception message is: 

`ExceptionMessage=Assembly.Load(byte[], ...) is not supported in AppX.;`

So it looks like System.Private.CoreLib.dll!System.Reflection.Assembly.Load(Byte[]) doesn't work in UWP. Now I need to find a way to capture .net Exceptions in Android.

**Comment by AndreiMisiukevich** [comment]
@MagicAndre1981 well, I will disable code reloading, because it doesn't work

**Comment by MagicAndre1981** [comment]
have you ever tested it with Android or only iOS?

**Comment by AndreiMisiukevich** [comment]
tested with android on MAC

**Comment by MagicAndre1981** [comment]
> tested with android on MAC

real device or emulator? Because run Win10 in a VM I always test real devices, because Android Emulator doesn't support nested VMs. Here I use Adb over Wifi/LAN to connect to a tablet/phone and run the apps

**Comment by AndreiMisiukevich** [comment]
@MagicAndre1981 both

**Comment by MagicAndre1981** [comment]
this is really wired. Can you add more debug code so that I can logging in debug window?
