### ISSUE TITLE
Future Discussion

### ISSUE THREAD

**Issue by MagicAndre1981** [AndreiMisiukevich/HotReload#93]
Microsoft announced their own XAML Hot Reload for using with Xamarin.Forms:

[Announcing XAML Hot Reload for Xamarin.Forms](https://devblogs.microsoft.com/xamarin/xaml-hot-reload/)

> Today at Xamarin Developer Summit, we announced XAML Hot Reload for Xamarin.Forms, which enables you to make changes to your XAML UI and see them reflected live, without requiring another build and deploy.
> 
> XAML Hot Reload for Xamarin.Forms speeds up your development and makes it easier to build, experiment, and iterate on your user interface. And this means that you no longer have to rebuild your app each time you tweak your UI – it instantly shows you your changes in your running app!

What does this mean for this project here? Will development stopped? Microsoft ones only seams to work in VS2019, so this extension here is better.

**Comment by AndreiMisiukevich** [comment]
Let’s observe current situation

**Comment by AndreiMisiukevich** [comment]
@MagicAndre1981 anyway i bumped new release yesterday)

**Comment by MagicAndre1981** [comment]
I saw it and just made the nuget update.

**Comment by AndreiMisiukevich** [comment]
going to close this ticket
i decided to continue supporting

**Comment by MagicAndre1981** [comment]
> i decided to continue supporting

![image](https://user-images.githubusercontent.com/8274816/61685606-88114200-ad1d-11e9-9d4c-5fe90cfe18ba.png)

**Comment by MagicAndre1981** [comment]
I saw[ your tweet ](https://twitter.com/Andrik_Just4Fun/status/1153648324211302400) and this C# reloading is what I need for improving Layout code in [OnSizeAllocated](https://docs.microsoft.com/en-US/dotnet/api/xamarin.forms.page.onsizeallocated?view=xamarin-forms) when rotation changes. I can't wait for the release 😍

**Comment by AndreiMisiukevich** [comment]
> I saw[ your tweet ](https://twitter.com/Andrik_Just4Fun/status/1153648324211302400) and this C# reloading is what I need for improving Layout code in [OnSizeAllocated](https://docs.microsoft.com/en-US/dotnet/api/xamarin.forms.page.onsizeallocated?view=xamarin-forms) when rotation changes. I can't wait for the release 😍

I am keen to release it

https://twitter.com/Andrik_Just4Fun/status/1153804045733122049

**Comment by MagicAndre1981** [comment]
the reloader of Microsoft is now part of VS2019 Update 3 Preview 2:

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/hot-reload

So it requires 16.3 at least and so your lib is still better for me.

**Comment by AndreiMisiukevich** [comment]
@MagicAndre1981 thanks man ))

**Comment by AndreiMisiukevich** [comment]
@MagicAndre1981 once Microsoft release better solution, i will archive this project.

**Comment by MagicAndre1981** [comment]
> @MagicAndre1981 once Microsoft release better solution, i will archive this project.

I doubt that. We still talk about Microsoft, their solutions are always poor, limited and unreliable. The requirement of VS2019 blocks me from using theirs, so I need your project.

**Comment by MagicAndre1981** [comment]
Xamarin.Forms 4.3 will [require Visual Studio 2019 16.3](https://github.com/xamarin/Xamarin.Forms/issues/7602#issuecomment-535998142)

> The next release of 4.2 will be built against VS 2017 so that it can still be used on VS 2017 but 4.3 is going to require you to have at least 16.3

So your project is obsolete as 16.3 has their Hotreload and later they will have [Hot Restart](https://devblogs.microsoft.com/xamarin/xamarin-hot-restart/) which reloads code, not in realtime, but faster.

**Comment by AndreiMisiukevich** [comment]
@MagicAndre1981 yes, that's true)
I will consider archiving this project
