### ISSUE TITLE
ResourceDictionary reloading issue

### ISSUE THREAD

**Issue by lolohouse** [AndreiMisiukevich/HotReload#94]
My application uses ControlTemplate in all the pages and controls .. but it is not possible to make changes in execution and see them with HotReload.

**Comment by AndreiMisiukevich** [comment]
very small example please

**Comment by AndreiMisiukevich** [comment]
Works fine for me, just validated

**Comment by AndreiMisiukevich** [comment]
http://www.giphy.com/gifs/gHbpcAD9dXLlzvQWOT

**Comment by lolohouse** [comment]
Sorry, my job has not left me, prepare a test project ..
I annex it now.
[lolo.zip](https://github.com/AndreiMisiukevich/HotReload/files/3416030/lolo.zip)

**Comment by AndreiMisiukevich** [comment]
Hmm, seems reloader doesn't work with your project at all!

**Comment by AndreiMisiukevich** [comment]
@lolohouse check newest nuget version. Will be available in 20-30 mins

**Comment by lolohouse** [comment]
thanks
