### ISSUE TITLE
HotReloader.Current.Start(This) is Obsolete

### ISSUE THREAD

**Issue by lordlagon** [AndreiMisiukevich/HotReload#95]
Today I updated the HotReload, and Start is obsolete. What parameters should I put in Start?
Version 1.4.13

![image](https://user-images.githubusercontent.com/21324347/61389684-b4494080-a88f-11e9-8f90-ff0571b19cdf.png)

**Comment by lordlagon** [comment]
I use HotReloader.Current.Run(this). it worked out.

**Comment by AndreiMisiukevich** [comment]
great)
