### ISSUE TITLE
doesn't work with XF 4.0 in Windows (no Shell)

### ISSUE THREAD

**Issue by seba47** [AndreiMisiukevich/HotReload#96]
In some cases it freeze VS or does not allow to open Xaml files.
I had to downgrade to XF 3.4

**Comment by AndreiMisiukevich** [comment]
Hi, do you have exact steps how to reproduce it ?

**Comment by AndreiMisiukevich** [comment]
are you sure it's hotReload trouble?

**Comment by AndreiMisiukevich** [comment]
it's definitely not a HotReload problem. And it cannot be XF problem too.
It's something related to VS i think

**Comment by IoTFier** [comment]
HI @seba47 , I am using hotReload with XF 4.1 and it is working fine.

**Comment by AndreiMisiukevich** [comment]
@seba47 so, update your VS

**Comment by seba47** [comment]
Hi, sorry for the delay!
Well It was happening in a windows machine from a partner. With your feedback I will try to fix that.

Thanks in advance
