### ISSUE TITLE
Stopped Working

### ISSUE THREAD

**Issue by DwainSnickles** [AndreiMisiukevich/HotReload#98]
After it stopped working I believe because the command prompt was starting as it was most likely for adb.exe. I downloaded and ran your sample file couldn't get it to make changes either. I added the adb.exe to the system environment as discussed restarted pc but still no command prompt. Is there a way to initialize and force adb.exe to start or verify if it is started.

**Comment by AndreiMisiukevich** [comment]
yes, just call ```adb forward tcp 8080 tcp 8080``` in command line

also make sure that you enabled extension!

**Comment by DwainSnickles** [comment]
Running it from command prompt gives me the following error 
adb server version (41) doesn't match this client (40);
Most likely because after I had the problem I upgraded the Android SDK.
