### ISSUE TITLE
System.Reflection.TargetParameterCountException: 'Parameter count mismatch.'

### ISSUE THREAD

**Issue by Saccomani** [AndreiMisiukevich/HotReload#99]
I am getting the following error: 

System.Reflection.TargetParameterCountException: 'Parameter count mismatch.'

I am using HotReload in Windows working with UWP Xamarin Forms

![image](https://user-images.githubusercontent.com/3049349/61630978-82552700-ac5f-11e9-89dc-e17d4bf502de.png)

**Comment by AndreiMisiukevich** [comment]
Hi,
What is the version of nuget?
Did it work before ?

**Comment by AndreiMisiukevich** [comment]
BTW you didn't disable xmlc

![image](https://user-images.githubusercontent.com/10124814/61633060-f65ef180-ac96-11e9-8670-a2777732d541.png)

**Comment by Saccomani** [comment]
> Hi,
> What is the version of nuget?
> Did it work before ?

    <PackageReference Include="Xamarin.Forms" Version="3.4.0.1008975" />
    <PackageReference Include="Xamarin.HotReload" Version="1.4.14" />

i remove xaml compile , just same error

**Comment by AndreiMisiukevich** [comment]
@Saccomani have it ever been working for you?

**Comment by AndreiMisiukevich** [comment]
@Saccomani could you please click "view details" and show me the stacktrace ?

**Comment by AndreiMisiukevich** [comment]
CI is creating 1.4.15
